### PR TITLE
Support JULES5.0 + HyMAP2 run

### LINKED ISSUE #1285: Enable JULES 5.0 with HYMAP2 router
JULES.5.0+HYMAP2 router is not supported.

### PR DESCRIPTION
**Pull request by yyoon4**
### Description

Add codes to run JULES 5.0 with HyMAP2 router

Resolves #1285

### Testcase

/discover/nobackup/yyoon4/lis7/Testcase/hymap_jules50

### CODE REVIEW

**Comment by emkemp** [comment]
Hi @yyoon4 

Is this pull request intended for LISF 7.5?

**Comment by dmocko** [comment]
Yes, the 557 WW LIS-7.5 MR system needs to run JULES-5.0 and HyMAP2.

Perhaps it should go into the support/lisf-557ww-7.5 branch.

**Comment by emkemp** [comment]
Hi @dmocko:

Yes, the destination branch was why I was asking.  We can change it to support/lisf-557ww-7.5.

We'll also need to issue a patch release once this is merged in.  Which we were not expecting (I thought the MR related patches coming in were for the GALWEM-GE forcing.)

**Comment by yyoon4** [comment]
> 

Yes, it should go into the support/lisf-557ww-7.5 branch. I selected wrong branch ;;

**Comment by dmocko** [comment]
I have a minor unrelated quality-of-life fix to the support/lisf-557ww-7.5 branch that I was going to make.

Let me get that PR in as well, so at least we can put them both into the next patch release.

**Comment by cmclaug2** [comment]
Hi @yyoon4,

I was able to run your testcase.  Can you please grant me read permission to the output in `/discover/nobackup/yyoon4/lis7/Testcase/hymap_jules50` so I can compare? 

Thanks!

**Comment by yyoon4** [comment]
@cmclaug2 
I have changed the permission!!

**Comment by jvgeiger** [comment]
Closing this pull request.  It was made on the wrong branch and rebasing led to issues.  These commits were reworked into PR #1294.

**Pull request closed without merging**
