### PR TITLE
Add support for SNODAS DA in NoahMP4.0.1

### LINKED ISSUE #760: Add support for SNODAS DA
Replace this text with a concise description of the proposed enhancement.

### PR DESCRIPTION
**Pull request by mlwrzesien**
### Description

Adds support to use SNODAS snow depth as a DA dataset with NoahMP 4.0.1. LIS DA plugin has been updated

Resolves #760 

### Testcase
Testcase available at /discover/nobackup/mwrzesie/LIS_testCases/SNODASda

### CODE REVIEW

**Comment by bmcandr** [comment]
Hi @mlwrzesien, there is a conflict in _lis/plugins/LIS_DAobs_pluginMod.F90_ that must be resolved before we can continue with this pull request. We want to keep both sets of changes that are "in conflict". It is a simple change so you can resolve these in your web browser by clicking on the "Resolve conflicts" button below, deleting lines 289, 294, 299, 899, 910, and 917, and clicking the "Mark as resolved" button.

Let me know if you need any assistance!

**Comment by mlwrzesien** [comment]
Thanks for the explanation @bmcandr. I just took care of that!

**Comment by mlwrzesien** [comment]
@bmcandr I committed the changes to the LIS LSM DA plugin file that you mentioned yesterday.

**Comment by bmcandr** [comment]
Thanks @mlwrzesien! I see some lingering merge conflict markers in _lis/plugins/LIS_DAobs_pluginMod.F90_  so I've cleaned those up on my side. I also went ahead and reverted the first set of SNODAS registration calls back to AMSR2 in _lis/plugins/LIS_lsmda_pluginMod.F90_ (see below) so that we don't break the AMSR2 DA when we merge. We can then wrap that section in an `#if ( defined ... )` call in a subsequent PR to clean it up.

I changed...
```fortran
call registerlsmdainit(trim(LIS_noahmp401Id)//"+"//&
        trim(LIS_SNODASobsId)//char(0),noahmp401_dasnow_init)
...
```

back to

```fortran
call registerlsmdainit(trim(LIS_noahmp401Id)//"+"//&
        trim(LIS_GCOMW_AMSR2L3sndobsId)//char(0),noahmp401_dasnow_init)
...
```

I will push my changes after confirming that they compile and run.

**Comment by mlwrzesien** [comment]
Thanks @bmcandr. I was just preparing a new PR for the AMSR2 changes, but I'll hold off on that for now until these SNODAS changes are brought into eis-freshwater.

**Review by bmcandr — APPROVED** [review]

**Comment by bmcandr** [comment]
@mlwrzesien, I successfully tested these changes and reproduced your output so I will go ahead and merge.

**Pull request merged**
