### PR TITLE
Feature/crocus ldt glacier fraction

### PR DESCRIPTION
**Pull request by LIS-navari**
This pull request is part of the Crocus implementation within the LIS framework. The updated LDT provides the parameter file to run the Crocus in LIS. The code computes the glacier fraction. 

A test case can be found in 
/discover/nobackup/mnavari/my_projects/thp/ldt_testcase/yy_hma
./ldt.config_test_glcier_frac
./run.job.ldt

### CODE REVIEW

**Review by bmcandr — CHANGES_REQUESTED** [review]
Hi @lis-navari,

I understand this feature is still under development, but I'm requesting a few minor changes for now:

* Document config options in _configs/ldt.config.adoc_ (perhaps with note that this feature is still under development?):
    * `"Glacier fraction data source:"`
    * `"Glacier fraction map:"`
    * `"Glacier fraction spatial transform:"`
* In _ldt/core/LDT\_paramProcMod.F90_: the comment at line 2285 in the original file was deleted and should be replaced (now at line 2295), `!  This routine writes the parameter data to file`
* In _ldt/params/glacier/setGlacierFracParmsFullnames.F90_: change calls to `print` to `write(LDT_logunit,*)` and calls to `stop` to `LDT_endrun()`
* In _ldt/params/glacier/set\_glacierfraction_attribs.F90_: change calls to `print` to `write(LDT_logunit,*)` and calls to `stop` to `LDT_endrun()`

I tested the code as-is with Intel 19 and GNU4 and I did not encounter any compile or runtime errors. I do see small differences in some output fields (see examples below). Can you let me know which module file and compile settings you used when generating the testcase? 

image
image

**Comment by bmcandr** [comment]
@LIS-navari, it turns out it was just a configure flag. I initially compiled with strict checks to check the code, but didn't recompile with defaults for testing. Sorry about that. Once requested the changes are pushed I'll retest and merge.

**Comment by LIS-navari** [comment]
Test cases are here.   

LDT from master branch
/discover/nobackup/mnavari/my_projects/thp/ldt_testcase/hma_master
 
LDT from development branch
/discover/nobackup/mnavari/my_projects/thp/ldt_testcase/yy_hma
 
Plotting scripts
/discover/nobackup/mnavari/my_projects/thp/ldt_testcase/yy_hma
ldt_cro.xdf
ldt_orig.xdf
plot.gs


Screen Shot 2021-01-27 at 5 48 05 PM

**Review by bmcandr — APPROVED** [review]

**Comment by bmcandr** [comment]
Hi @LIS-navari, thanks for making these changes. The test output still looks good.

I fixed the formatting in the _ldt.config.adoc_ changes and updated the domain bounds/resolution descriptions. For example, I changed:

`Glacier fraction lower left lat:` -89.995

To:

`Glacier fraction lower left lat:` specifies the lower left latitude of the LIS model output.

Let me know if these changes look ok to you.

**Comment by LIS-navari** [comment]
Thanks

**Comment by bmcandr** [comment]
Great, I'll go ahead and merge.

I recommend opening a new Issue regarding the clean-up and/or other work this feature needs so we can keep track of that.

**Pull request merged**
