### PR TITLE
Support for compiling on SLES 12

### PR DESCRIPTION
**Pull request by jvgeiger**
To compile LISF on discover running SLES 12, I had to replace the JasPer library with openJPEG.  This pull request contains the changes needed to support either JasPer or openJPEG.

It also contains two modulefiles in a new env directory: 

lisf_7_intel_18_0_3_222 for discover running SLES 11.3
lisf_7_intel_19_1_0_166 for discover running SLES 12.3

### CODE REVIEW

**Comment by jvgeiger** [comment]
I was able to compile with this branch on discover, both SLES 11.3 and SLES 12.3, as well as on conrad.

**Comment by emkemp** [comment]
Hi Jim:

I'm working on this now.  Question:  Do we want to merge this capability into the 557WW branch?

**Comment by jvgeiger** [comment]
I do not believe that this is needed in the 557WW branch for the 7.3 release.

**Comment by emkemp** [comment]
Thanks Jim!

Code compiles on both SLES 11 and 12.  No problems detected.  I approve.

**Pull request merged**
