### PR TITLE
LIS 7.5.11 557WW - final S2S updates

### PR DESCRIPTION
**Pull request by karsenau**
@jvgeiger and @emkemp: 

We are submitting our latest S2S updates for the LIS 7.5.11 PR.

This update includes -
1)  Final fixes to BCSD scripts
2)  Final CF-compliance updates for s2spost and s2smetric scripts

Submitting on behalf of the GHI-S2S team.

### CODE REVIEW

**Comment by emkemp** [comment]
I've started reviewing the S2S changes.  An immediate question for @jvgeiger:   Should the new copyright blocks in new scripts say "LISF 7.5" and "Copyright 2023"?  Or are "7.4" and "2022" acceptable?

**Comment by emkemp** [comment]
Something else I notice:  There is a Python script authored by Shrad Shukla that now has a NASA Copyright comment block in it.  That doesn't sound right to me.  Did Shrad assign copyright to NASA?

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/bcsd_stats_functions.py

**Comment by jvgeiger** [comment]
I told Sarith that he could use "LISF 7.4" or "LISF 7.5" because the copyright notice reflects the public release.  I will update all the notices to "LISF 7.5" when we create the next public release.

**Comment by jvgeiger** [comment]
> Something else I notice: There is a Python script authored by Shrad Shukla that now has a NASA Copyright comment block in it. That doesn't sound right to me. Did Shrad assign copyright to NASA?
> 
> lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/bcsd_stats_functions.py

That does not seem right.  Thanks for catching it.  I will look into this.

**Comment by karsenau** [comment]
> > Something else I notice: There is a Python script authored by Shrad Shukla that now has a NASA Copyright comment block in it. That doesn't sound right to me. Did Shrad assign copyright to NASA?
> > lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/bcsd_stats_functions.py
> 
> That does not seem right. Thanks for catching it. I will look into this.

Thanks for catching this.  I believe the copyright blocks were recently added to all the python scripts recently, regardless of authorship, by our team.  We may not have understood the difference of when to apply or not.
Thanks!

**Comment by emkemp** [comment]
Thanks @jvgeiger and @karsenau!

Here is a list of the scripts that originated from Shrad and have NASA Copyright blocks added in this pull request.

lis/utils/usaf/s2s/s2s_app/download_nmme_hindcasts.sh

lis/utils/usaf/s2s/s2s_app/download_nmme_precip.sh

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/bcsd_stats_functions.py

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/bias_correction_modulefast.py


lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/bias_correction_nmme_modulefast.py

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/calc_and_write_forecast_climatology.py

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/calc_and_write_nmme_forecast_climatology.py

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/calc_and_write_observational_climatology.py


lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/combine_sub_daily_downscaled_forcings.py

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/shrad_modules.py

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/temporal_disaggregation_6hourly_module.py

lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/temporal_disaggregation_nmme_6hourly_module.py

lis/utils/usaf/s2s/s2s_modules/s2smetric/metrics_library/convert_dyn_fcst_to_anom.py


lis/utils/usaf/s2s/s2s_modules/s2smetric/metrics_library/convert_dyn_fcst_to_sanom.py

lis/utils/usaf/s2s/s2s_modules/s2smetric/metrics_library/metricslib.py


lis/utils/usaf/s2s/s2s_modules/s2smetric/postprocess_nmme_job.py # “Based on Postprocess_NMME_job.sh and job_run_convert_Dyn_FCST_to_postproc.scr”

**Comment by emkemp** [comment]
An additional, minor question:  For those scripts that should have a NASA copyright block, should that block be before or after the comment block summarizing the contents of the script?

That is:

# NASA Copyright block

"""
This module does blah
"""

Or vice versa?  Or does it matter?

**Comment by emkemp** [comment]
I have no other concerns with the code (all the changes are to Python and shell scripts, and config files).  We just need to resolve the copyright block questions.

**Comment by jvgeiger** [comment]
Thanks Eric.  I will work on the copyright notices.

**Comment by emkemp** [comment]
@jvgeiger  Do you want me to accept the PR before you work on the copyright notices, or will you push fixes to Sarith's branch first?

**Comment by jvgeiger** [comment]
I will push onto this PR first.  Thanks.

**Comment by karsenau** [comment]
> I will push onto this PR first. Thanks.

Thanks, guys!

**Comment by jvgeiger** [comment]
@smahanam, would you please select "Allow edits and access to secrets by maintainers"?  I have a commit that corrects the copyright notices to push onto this branch.  Thanks.

**Comment by jvgeiger** [comment]
Sorry, @karsenau, would you please select "Allow edits and access to secrets by maintainers"?

**Comment by jvgeiger** [comment]
@smahanam, Kristi could not find it either.  Perhaps it is only available when the pull request is created.  I will accept this pull request as is.  Then I will submit a follow on pull request with my commit.  Thanks for trying.

**Pull request merged**
