### PR TITLE
Modify IMERG reader to ingest V07A Final products

### LINKED ISSUE #1394: Update IMERG Reader for v07
The IMERG metforcing reader will be updated to ingest V07 files. The reprocessing of the V07 Final products began in July 2023, and the Early and Late runs are expected in Fall 2023. 

https://gpm.nasa.gov/sites/default/files/2023-07/IMERG_V07_ReleaseNotes_final_230713.pdf

### PR DESCRIPTION
**Pull request by jerlingi**
### Description

The IMERG reader was modified to read the newly released V07 products. Only Final IMERG V07A products are available at this time (August 2023), but Early and Late products are anticipated in Fall 2023. In V07 and subsequent versions, variable names have changed. Please see https://gpm.nasa.gov/sites/default/files/2023-07/IMERG_V07_ReleaseNotes_final_230713.pdf for more documentation. 

Resolves #1394 

### Testcase

A testcase is available at /discover/nobackup/projects/lais/sharespace/imergv07_forcing_testcase

### CODE REVIEW

**Comment by cmclaug2** [comment]
@jerlingi Thank you for the packaged testcases.  I have been able to:

- compile your code with the intel compiler with strict checks.  
- compile your code with the gnu compiler with strict checks. 
- Read in IMERG V07A and replicate your testcase output.


Before merging, I would like to point @jvgeiger's attention to a few things for approval. 

In  **`read_imerg.F90`**:
- Line 150 and 156.  `len` is defined as a specific length.  Is that fine or is `len=*` preferred? 

In **`readcrd_imerg.F90`**
-  Line 57 and 59.  LIS defaults to reading IMERG V06B.  Should this be changed to V07A, or left as is?  In either case, I will add an additional note in the documentation before merging. 

All else looks good to me.

**Comment by jvgeiger** [comment]
Thanks @cmclaug2.  I will look at that.

Also, @emkemp should look at this.  He is also reviewing IMERG V7 for our USAF project.

**Comment by jerlingi** [comment]
I agree that @emkemp should have a look too. In my opinion, we shouldn't change the default to V07A until the Early and Late versions are released (~Fall 2023) because it will fail unless Final is selected.

**Comment by jvgeiger** [comment]
@cmclaug2 When you pass a string into a Fortran routine, you may declare the length of the string as (len=*).  See line 148.  Fortran knows the length.  Here, the string filename was first declared in the calling routine at line 74 with a specific length (len=LIS_CONST_PATH_LEN).  So, in the called routine, you may use (len=*).

For local variables, you must specify the length.  dsetname and vlname are local to read_imerghdf. So, at lines 150 and 155, a specific length is needed.

**Comment by emkemp** [comment]
I reviewed the changes by @jerlingi.  I think the code can be improved slightly by using a formatted read '(I)' instead of the unformatted *. 

However, I have more fundamental concerns about the subroutine (not @jerlingi 's fault).  Presently a return statement will be executed if any non-zero error code is returned by HDF5, *without* calling any HDF5 "close" subroutines to clean up under the hood.  I don't think that's acceptable -- h5close_f should always be called if there was a successful h5open_f call; h5fclose_f should be called if there was a successful h5fopen_f (to close the file!); and h5dclose_f should be called if there is a successful h5dopen_f call.  

I think a subsequent pull request is in order to fix these issues.

**Comment by jvgeiger** [comment]
Good catch - I agree.  One more suggestion: all processes should log status messages, not just LIS_masterproc. (Again, not @jerlingi 's fault.)

**Comment by jvgeiger** [comment]
I made the `'(I)'` the LIS_masterproc changes.  I will look into the various `h5?close_f` calls.

**Comment by emkemp** [comment]
Thanks.  I started setting up a work directory to test changes, but I've now been sucked into emergency Air Force S2S work.   I think that has the higher priority. :-(

**Comment by emkemp** [comment]
I had some time today so I made and tested some code improvements.  Please let me know what you think.

**Comment by jvgeiger** [comment]
@emkemp Your commit looks good.  I added one commit on top of yours.

**Comment by jvgeiger** [comment]
What versions of IMERG do we support?

V06B: early, late, final
V07A: final

**Comment by emkemp** [comment]
Latest code compiles, and documentation looks fine.  I accept.

**Pull request merged**
