### PR TITLE
Fix GNU Fortran compiler error

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

Fix compiler error raised by the GNU gfortran compiler.

### CODE REVIEW

**Comment by emkemp** [comment]
Why is the format set to I4?  Only a single digit is being read in.

(And as I think about it now, it should be two digits (V07A), which requires a change to the substring parsing.)

**Comment by jvgeiger** [comment]
We are reading string into an integer.  As I understand it, the statement `read(vlname, '(*)') vnum` the format `'(*)'` specifies the default size of the integer.  We switched to using `'(I)'`, but GNU does not like that.  I changed it to `'(I4)'` because the target value is an integer*4.

I lost my Fortran reference book, and I cannot find the online source for my "understanding".  I will defer to your reference book.

**Comment by emkemp** [comment]
Yeah, the language in my Modern Fortran book is not as clear as I would like.  But I have an older Fortran 90 book that describes "Iw" (where w is an unsigned int) as "Read the next w characters as an integer".  So I think it should match the number of characters being provided.

I compiled a proposed change, and the test job is stuck in the queue.  Hopefully it will run overnight and I can push.

**Comment by emkemp** [comment]
This code runs w/o issue.  Let me know what you think.

**Pull request merged**
