### PR TITLE
Adds support for Mutual Information metric in LVT

### LINKED ISSUE #497: Add mutual information metric within LVT

### PR DESCRIPTION
**Pull request by sujayvkumar**
This updates adds the support for mutual information metric in LVT.

Mutual Information values are calculated as:
      I(X;Y)=Sum_x Sum_y PXY(x,y)log [PXY(x,y)/(PX(x)PY(y))]
Note that time series calculations are not enabled for this metric.
Also this metric only should be used to analyze one variable at a time.

Resolves #497

### CODE REVIEW

**Comment by sujayvkumar** [comment]
An example test case is available at  /discover/nobackup/svkumar/LISF_testing/497

**Comment by bmcandr** [comment]
Hi @sujayvkumar I successfully compiled and ran LVT based on your testcase. While the output of my run is identical to yours, the log contains this warning before successfully completing:

`[WARN] LIS file ./LIS_OUTPUT/SURFACEMODEL/200202/LIS_HIST_200202010000.d01.nc does not exist`

The warning can be resolved by altering lines 18 and 19 in `lvt.config` to end the run on 1/31 rather than 2/1. LVT is looking for data in `./LIS_OUTPUT/SURFACEMODEL/200202/` which does not exist, hence the error.

**Comment by bmcandr** [comment]
Hi @sujayvkumar. Jim and Eric looked over this PR with me and pointed out a few more things to bring to your attention before we can merge this. Please:

* Document "Mutual information:" in `lvt/configs/lvt.config.adoc`
    *  See line 231 in `lvt/core/LVT_readMetricsAttributes.F90`
* Remove debugging print statements:
    * See lines 617-619, 630-635 in `lvt/metrics/LVT_MutualInformationMod.F90`

Jim explained that the warning I described in my previous comment is acceptable and may not need repair if you're OK with it.

Thanks,
B

**Comment by bmcandr** [comment]
Thanks, Sujay.

* Configure, compile, and run results:
    - [x] SLES11/Intel 18 - *PASS*
    - [x] SLES11/GNU 4 - *PASS*

@jvgeiger @emkemp, let me know if this looks good to you and I will merge.

**Pull request merged**
