### PR TITLE
Update file name for APHRODITE product for 2007-2015

### PR DESCRIPTION
**Pull request by yyoon4**
Support APHRODITE-2  V1101EX_R1 (2007-2015), Monsoon Asia

### CODE REVIEW

**Comment by yyoon4** [comment]
Test case:
/discover/nobackup/yyoon4/lis7/Testcase/aphro_ma

**Comment by dmocko** [comment]
Yeosang,

This one looks pretty straight-forward, but we don't have permissions to the "Data" sub-directory in your nobackup directory.  Can you please open it up?

Thanks,

David

**Comment by yyoon4** [comment]
I changed folder permissions. Thanks!

**Comment by dmocko** [comment]
I ran the testcase and was able to reproduce your results.  Merging and closing this pull request.

**Pull request merged**
