### PR TITLE
lai_da for noahmp.4.0.1 and MODIS MCD15A2H LAI reader for LIS

### PR DESCRIPTION
**Pull request by KathyNie**
add features supporting assimilating MCD15A2H LAI product into Noah-MP.4.0.1, including:

1. lai_da for Noah-MP.4.0.1 contributed by Sujay
2. a reader for the MODIS MCD15A2H LAI product

### CODE REVIEW

**Comment by bmcandr** [comment]
Hi @KathyNie,

I have a few questions based on my initial testing results.

1. The target output provided with your testcase includes output for 3 days, but the *lis.config* file specifies a run period from 2007-2020. Similarly the target *lislog.0000* indicates the run ended prematurely. Did you cut the LIS run short intentionally when building the testcase because we're focused on the DAOBS output and therefore do not need a long run?

2. I was able to reproduce your target DAOBS output (👍), but I'm seeing differences in some fields in the *SURFACEMODEL* output. While troubleshooting I noticed that my log files are missing [`[INFO] Finished assimilating Observations using EnKF`](https://github.com/NASA-LIS/LISF/blob/03d136c068484928128423575b2e2cb5ad9abec3/lis/dataassim/algorithm/enkf/enkf_Mod.F90#L557) messages  that  are present in your logs. This seems unrelated to your changes, but still worth bringing up. @sujayvkumar any thoughts? Stepping through the code shows that `fresh_incr` never gets set to `true` so the block beginning at [line 500](https://github.com/NASA-LIS/LISF/blob/03d136c068484928128423575b2e2cb5ad9abec3/lis/dataassim/algorithm/enkf/enkf_Mod.F90#L498) is never run.

For comparison here's an excerpt from your target log:

```sh
 [INFO] Reading HDF5 IMERG precipitation data from 
 ./IMERG/Early_V06B/200704/3B-HHR-E.MS.MRG.3IMERG.20070401-S000000-E002959.0000.
 V06B.RT-H5          
 Obtained IMERG precipitation data from 
 ./IMERG/Early_V06B/200704/3B-HHR-E.MS.MRG.3IMERG.20070401-S000000-E002959.0000.
 V06B.RT-H5
 [INFO] Reading 
 ../LS_PARAMETERS/MODIS/MCD15A2H.006/2007/MCD15A2H.006_LAI_2007089.nc4
 [INFO] Opening climo file 
 ../LS_PARAMETERS/MODIS/MCD15A2H.006/MCD15A2H.006_LAI_YYYY089.nc4
 [INFO] Reading 
 ../LS_PARAMETERS/MODIS/MCD15A2H.006/2007/MCD15A2H.006_LAI_2007097.nc4
 [INFO] Opening climo file 
 ../LS_PARAMETERS/MODIS/MCD15A2H.006/MCD15A2H.006_LAI_YYYY097.nc4
 [INFO] Finished assimilating Observations using EnKF                            <----missing from test log
[INFO] LIS cycle time: 04/01/2007 00:30:00
```

And an excerpt from my test run log:

```
[INFO] Reading HDF5 IMERG precipitation data from 
 ./IMERG/Early_V06B/200704/3B-HHR-E.MS.MRG.3IMERG.20070401-S000000-E002959.0000.
 V06B.RT-H5          
 Obtained IMERG precipitation data from 
 ./IMERG/Early_V06B/200704/3B-HHR-E.MS.MRG.3IMERG.20070401-S000000-E002959.0000.
 V06B.RT-H5
 [INFO] Reading 
 ./INPUT/LS_PARAMETERS/MODIS/MCD15A2H.006/2007/MCD15A2H.006_LAI_2007089.nc4
 [INFO] Opening climo file 
 ./INPUT/LS_PARAMETERS/MODIS/MCD15A2H.006/MCD15A2H.006_LAI_YYYY089.nc4
 [INFO] Reading 
 ./INPUT/LS_PARAMETERS/MODIS/MCD15A2H.006/2007/MCD15A2H.006_LAI_2007097.nc4
 [INFO] Opening climo file 
 ./INPUT/LS_PARAMETERS/MODIS/MCD15A2H.006/MCD15A2H.006_LAI_YYYY097.nc4
[INFO] LIS cycle time: 04/01/2007 00:30:00
```

**Comment by KathyNie** [comment]
> Hi @KathyNie,
> 
> I have a few questions based on my initial testing results.
> 
> 1. The target output provided with your testcase includes output for 3 days, but the _lis.config_ file specifies a run period from 2007-2020. Similarly the target _lislog.0000_ indicates the run ended prematurely. Did you cut the LIS run short intentionally when building the testcase because we're focused on the DAOBS output and therefore do not need a long run?
> 2. I was able to reproduce your target DAOBS output (👍), but I'm seeing differences in some fields in the _SURFACEMODEL_ output. While troubleshooting I noticed that my log files are missing [`[INFO] Finished assimilating Observations using EnKF`](https://github.com/NASA-LIS/LISF/blob/03d136c068484928128423575b2e2cb5ad9abec3/lis/dataassim/algorithm/enkf/enkf_Mod.F90#L557) messages  that  are present in your logs. This seems unrelated to your changes, but still worth bringing up. @sujayvkumar any thoughts? Stepping through the code shows that `fresh_incr` never gets set to `true` so the block beginning at [line 500](https://github.com/NASA-LIS/LISF/blob/03d136c068484928128423575b2e2cb5ad9abec3/lis/dataassim/algorithm/enkf/enkf_Mod.F90#L498) is never run.
> 
> For comparison here's an excerpt from your target log:
> 
> ```shell
>  [INFO] Reading HDF5 IMERG precipitation data from 
>  ./IMERG/Early_V06B/200704/3B-HHR-E.MS.MRG.3IMERG.20070401-S000000-E002959.0000.
>  V06B.RT-H5          
>  Obtained IMERG precipitation data from 
>  ./IMERG/Early_V06B/200704/3B-HHR-E.MS.MRG.3IMERG.20070401-S000000-E002959.0000.
>  V06B.RT-H5
>  [INFO] Reading 
>  ../LS_PARAMETERS/MODIS/MCD15A2H.006/2007/MCD15A2H.006_LAI_2007089.nc4
>  [INFO] Opening climo file 
>  ../LS_PARAMETERS/MODIS/MCD15A2H.006/MCD15A2H.006_LAI_YYYY089.nc4
>  [INFO] Reading 
>  ../LS_PARAMETERS/MODIS/MCD15A2H.006/2007/MCD15A2H.006_LAI_2007097.nc4
>  [INFO] Opening climo file 
>  ../LS_PARAMETERS/MODIS/MCD15A2H.006/MCD15A2H.006_LAI_YYYY097.nc4
>  [INFO] Finished assimilating Observations using EnKF                            <----missing from test log
> [INFO] LIS cycle time: 04/01/2007 00:30:00
> ```
> 
> And an excerpt from my test run log:
> 
> ```
> [INFO] Reading HDF5 IMERG precipitation data from 
>  ./IMERG/Early_V06B/200704/3B-HHR-E.MS.MRG.3IMERG.20070401-S000000-E002959.0000.
>  V06B.RT-H5          
>  Obtained IMERG precipitation data from 
>  ./IMERG/Early_V06B/200704/3B-HHR-E.MS.MRG.3IMERG.20070401-S000000-E002959.0000.
>  V06B.RT-H5
>  [INFO] Reading 
>  ./INPUT/LS_PARAMETERS/MODIS/MCD15A2H.006/2007/MCD15A2H.006_LAI_2007089.nc4
>  [INFO] Opening climo file 
>  ./INPUT/LS_PARAMETERS/MODIS/MCD15A2H.006/MCD15A2H.006_LAI_YYYY089.nc4
>  [INFO] Reading 
>  ./INPUT/LS_PARAMETERS/MODIS/MCD15A2H.006/2007/MCD15A2H.006_LAI_2007097.nc4
>  [INFO] Opening climo file 
>  ./INPUT/LS_PARAMETERS/MODIS/MCD15A2H.006/MCD15A2H.006_LAI_YYYY097.nc4
> [INFO] LIS cycle time: 04/01/2007 00:30:00
> ```

Hi @bmcandr,

1. Yes I intentionally terminate the process after it generates a few output files as the goal for this new feature is to assimilate the LAI dataset into the model. So once I saw the observation gets assimilated at daily interval, it should be fine. And that means, the message of " [INFO] Finished assimilating Observations using EnKF" is important, from which I can tell that the MCD15A2H.006 files gets assimilated into the model! I'm sorry for the confusion.

2. Hmm... I haven't seen this issue before. It seems to me that the MCD15A2H.006 files get read in but not assimilated. I'm wondering whether it might be worth to check the LAI variable in the output...Do you see big difference between my target output and your test output?

**Comment by bmcandr** [comment]
Hi @KathyNie 

Thanks for the info. There are *very* small differences between the target and test output in the *lai_tavg* field. For example:





What compiler and optimization did you use to create your output?

**Comment by KathyNie** [comment]
> Hi @KathyNie
> 
> Thanks for the info. There are _very_ small differences between the target and test output in the _lai_tavg_ field (rounding errors most likely). For example:
> 
> 
> 
> 
> 
> What compiler and optimization did you use to create your output?

Hi @bmcandr,

Ah...Ok, it looks that the observation does get assimilated, or else we should see significant difference between the two for that day you are plotting out. I compile the model at the default optimization level (=2) with the private module that Jim provided. Below is the module list:

Currently Loaded Modules:
  1) comp/gcc/9.2.0          3) mpi/impi/20.0.0.166
  2) comp/intel/19.1.0.166   4) lisf_7_intel_19_1_0_166

**Comment by bmcandr** [comment]
Gotcha. I'm using the newer Intel 19 module available in [LISF/env/discover](https://github.com/NASA-LIS/LISF/tree/master/env/discover) and had compiled with -1 to debug. I'll try again with your settings to see if that helps.

**Review by bmcandr — CHANGES_REQUESTED** [review]
Hi @KathyNie 

Good news! I was able to reproduce your output using the *lisf_7_intel_19_1_0_166* module. I am investigating the source of the differences with the new module, but for now I have a few simple revision requests related to formatting and documentation. They should not affect how the code runs at all:

* In `lis/dataassim/obs/MCD15A2H_LAI/MCD15A2Hlai_Mod.F90`:
    * Complete module description at line 14
    * Add `k` to argument descriptions (~line 98)
* In `lis/dataassim/obs/MCD15A2H_LAI/read_MCD15A2Hlai.F90`:
    * Add documentation of subroutine arguments (e.g., `k`, `climofile` `laiobs_ip` at lines 42, 323, 559)
    * Indent code within `if` blocks for readability (see lines 117, 121, 124)
    * Remove commented code at lines 523-526
* In `lis/dataassim/obs/MCD15A2H_LAI/write_MCD15A2Hlai.F90`:
    * Add description for `MCD15A2H_laiobsname` routine and arguments (line 92)

Thanks!

**Comment by KathyNie** [comment]
Hi @bmcandr, 

Glad to hear that you are able to replicate the output using the same modules. I've revised the formatting and description as suggested. Please take a look!

Best,
Wanshu

**Comment by bmcandr** [comment]
Thanks @KathyNie! Looks like you may have missed the module description at line 14 in `lis/dataassim/obs/MCD15A2H_LAI/MCD15A2Hlai_Mod.F90` that trails off:

```f90
! This module contains interfaces and subroutines to
! handle 
```

Once that's fixed the pull request will be ready to merge!

**Review by bmcandr — APPROVED** [review]

**Comment by KathyNie** [comment]
Hi @bmcandr,

Thanks for pointing this out. I've added it now. Thanks a lot for merging this to the master branch!

Best,
Wanshu

**Comment by dmocko** [comment]
Hi - sorry to comment on a closed pull request, but there should be a tweak to the lis/configs/lis.config.adoc file.

The section header is not appearing correctly, and the formatting is also not correct.

Furthermore, the documentation indicates that this section is for "devonly".  Is this correct?

Attaching an example of what the section looks like:

MCD15A2H_LIS-User-Guide

David

**Comment by bmcandr** [comment]
Thanks @dmocko. Jim set the `devonly` attribute to true ahead of the 7.3 release and is working towards removing it (see #662). Since this feature made it to master, it should not be behind hidden as `devonly`.

I've got this cleaned up and will push shortly.

**Comment by KathyNie** [comment]
Thanks David and Brendan. Sorry I'm a bit confused about the section header, do I need to modify anything from my side?

**Comment by bmcandr** [comment]
No worries, it's all taken care of! No action needed on your end.

**Pull request merged**
