### PR TITLE
Back merge NASA_SMAPvod reader updates

### PR DESCRIPTION
**Pull request by jvgeiger**
I cherry-picked LIS NASA_SMAPvod commits on the master branch into the support/lisf-557ww-7.3 branch. These commits contain updates to add support for assimilating NASA SMAP VOD retrievals in LIS.

### CODE REVIEW

**Comment by emkemp** [comment]
This compiles, and I have no objection to the code.  However, I do not have a test case.  Should I merge the pull request anyway?

**Comment by jvgeiger** [comment]
See PR #191.  Thanks.

**Comment by emkemp** [comment]
It looks like the SMAP L2 data for this case has been deleted.  The /discover/nobackup/projects/lis/RS_DATA/SMAP/SPL2SMP_E.002/ directory no longer exists.  

@sujayvkumar , do you have this data archived somewhere?

**Comment by bmcandr** [comment]
@emkemp, Sujay updated the test case a bit further down in #191 that points to: /discover/nobackup/svkumar/LISF_testing/191

It relies on SPL2SMP_E.00**3** which still exists from what I can see.

**Comment by emkemp** [comment]
Oops.  Thanks for pointing that out.  (I'm regretting my decision to give up caffeine....)

**Comment by emkemp** [comment]
Okay, I ran the test case from /discover/nobackup/svkumar/LISF_testing/191, and I have output with no NaNs.  However, I do not see sample output in that directory to compare with mine.  @bmcandr do you have sample output from the #191 test case stashed away somewhere?

**Comment by bmcandr** [comment]
I sure do. You can find it in: /discover/nobackup/projects/lis/PR_TESTCASES/191/from_svkumar

**Comment by emkemp** [comment]
Thanks @bmcandr !

I see no visual differences in my results and those in the PR_TESTCASES directory.  So I will declare victory and accept the pull request.

**Pull request merged**
