### PR TITLE
Resolve compiling errors on Cray/SLES 15.4/PrgEnv 8.3.3 using Intel 2022.2.1

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

These changes resolve compiling errors in RDHM and VIC 4.1.1 encountered when compiling LISF on narwhal after its upgrade to Cray/SLES 15.4/PrgEnv 8.3.3.

I was able to successfully run our VIC 4.1.1 testcase on narwhal.

### CODE REVIEW

**Comment by jvgeiger** [comment]
Sorry about the diff.  GitHub is a bit confused.  The file vic411_read_vegparam.c was renamed to vic411_read_vegparam_lis.c, and the file vic411_read_vegparam.c.origin was renamed to vic411_read_vegparam.c.

**Comment by emkemp** [comment]
Hi @jvgeiger:

I've been testing this pull request on Narwhal.  First test (all LSMs) compiles fine with optimization level 2.  However, when I try again with -3 (full on debugging), the Intel C compiler objects to some of the compiler flags and halts.  It appears some of the command line syntax has changed.

icx: error: unknown argument '-check=conversions,stack,uninit'; did you mean '-fcheck=conversions,stack,uninit'?
icx: error: unknown argument '-ftrapuv'; did you mean '-ftrapv'?
icx: warning: Note that use of '-g' without any optimization-level option will turn off most compiler optimizations similar to use of '-O0' [-Wdebug-disables-optimization]

I'll play with the new flags and see if these are backward compatible.

**Comment by emkemp** [comment]
Update:  I made a mistake with the optimization level 2 test (rdhm.3.5.6 wasn't included in the compilation, so some of the changed files weren't compiled).  A new test with rdhm included does compile, but debugging shows some issues in gen_frzst.c

../surfacemodels/land/rdhm.3.5.6/frz/gen_frzst.c:108:11: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
       if(abs(xx) > tolerance) {
          ^
../surfacemodels/land/rdhm.3.5.6/frz/gen_frzst.c:108:11: note: use function 'fabsf' instead
       if(abs(xx) > tolerance) {
          ^~~
          fabsf
../surfacemodels/land/rdhm.3.5.6/frz/gen_frzst.c:108:11: note: include the header <math.h> or explicitly provide a declaration for 'fabsf'
../surfacemodels/land/rdhm.3.5.6/frz/gen_frzst.c:210:11: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]

**Comment by emkemp** [comment]
Another complaint (though this seems really picky).

../surfacemodels/land/vic.4.1.1/vic411_read_vegparam_lis.c:423:25: warning: while loop has empty body [-Wempty-body]
  while( (*c++ != END) );
                        ^
../surfacemodels/land/vic.4.1.1/vic411_read_vegparam_lis.c:423:25: note: put the semicolon on a separate line to silence this warning
../surfacemodels/land/vic.4.1.1/vic411_read_vegparam_lis.c:431:25: warning: while loop has empty body [-Wempty-body]
  while( (*c++ != END) );
                        ^
../surfacemodels/land/vic.4.1.1/vic411_read_vegparam_lis.c:431:25: note: put the semicolon on a separate line to silence this warning
2 warnings generated.

**Comment by jvgeiger** [comment]
Hello.  I saw that last warning, and the code is actually correct.  All the work is being done in the while statement itself.

**Comment by jvgeiger** [comment]
Hello.  And I also ignored the warnings about abs in RDHM.  I was focusing on compiler errors.

**Comment by emkemp** [comment]
I pushed a change to lis/arch/Config.pl to disable the Intel debug flags that icx objects to.  The code compiles on both Discover (Intel and GNU) and Narwhal.  I accept.

**Pull request merged**
