### PR TITLE
Expand filename char length in LIS forcing readers

### PR DESCRIPTION
**Pull request by karsenau**
Expanded the length of character data types for filename
  paths read in for some LIS forcing readers, going from 80
  or 99 to 140 characters, so users may not encounter
  "missing" files when directory+filename length is specified
  longer than what the "get" routines support.

 Addresses LISF git ticket #533.

### CODE REVIEW

**Comment by karsenau** [comment]
Hi @bmcandr -
Thanks so much for checking these commits and that one file that I had made a change to for another purpose.  Yes, I will set this one as a new commit and pull request with updated info accompanying it.  It is a minor update but will do that anyways.

Yes, for the "get_cmap.F90" routine, I thought it best to leave in those two commented lines to show the differences from before, as this routine used more specific formatting in setting up the filename path.

**Comment by emkemp** [comment]
I strongly propose expanding the character limit to 255.  This is the maximum path limit specified by the POSIX standard (more or less obeyed by Linux and Windows at least).

**Comment by bmcandr** [comment]
Thanks for the reminder that you mentioned this in #371 @emkemp!

**Comment by jerrywegiel** [comment]
Hi,

Unless there is a good reason not to, I concur with Eric's recommendation to just migrate to the maximum value of 255.

Rationale: 557 WW often uses explicit paths which ultimately lead to very long file names.  This is done for the eventual situation where their HPC system stability is interrupted and the symbolic links go away/break.

Jerry


Jerry Wegiel, Ph.D.

Principal Investigator, DoD-/IC- components of LIS: https://lis.gsfc.nasa.gov<https://lis.gsfc.nasa.gov/>

NASA/GSFC Hydrological Sciences Laboratory: http://science.gsfc.nasa.gov/earth/hydrology/

SETA Research Scientist Senior Principal

101 Nelson Drive

Offutt AFB, NE 68113-1023



402-232-7690 (Office)

240-261-8457 (New Mobile)

SIPRNET: jerry.w.wegiel.ctr@mail.smil.mil<mailto:jerry.w.wegiel.ctr@mail.smil.mil>

https://www.linkedin.com/in/jerrywegiel

________________________________

**Comment by karsenau** [comment]
Thanks for your feedback on this and also linking back to issue #371, as @dmocko did.  

I am fine with this, though I feel expanding all these filenames to 255 character lengths might be best to retest the metforcing readers (and any other input data readers that you expand as well, like outlined in #371).

**Comment by karsenau** [comment]
One other quick side note:  The IMERG reader currently has 99 characters for the file pathname; however some users did not realize why IMERG reader was not reading in files ... the filename itself is so long that it was truncating the filepath and the user wasn't aware.

**Comment by karsenau** [comment]
@bmcandr: Thanks for working on completing that code update and pull request for us.

**Comment by bmcandr** [comment]
Glad to contribute, @karsenau! I grepped the metforcing directory and it looks like there are additional instances of hardcoded filepath char limits in readers for the following metforcing datasets:

* 3B42RTV7
* ALMIPII **(retiring?)**
* Bondville
* FASSTsingle **(retiring?)**
* Loobos
* RFE2gdas
* chirps2
* climatology
* cmap
* cmorph
* coop **(retiring?)**
* ecmwf
* gdas3d **(retiring?)**
* gefs
* genEnsFcst
* genMetForc
* imerg
* nldas1 **(retiring?)**
* nldas2
* pet_usgs
* pptEnsFcst
* scan
* snotel
* vicforcing.4.1.2

Should these be updated to use `LIS_PATH_LEN` as well? (excluding those readers slated for retirement per the *LISF Metforcing CLean Up* spreadsheet)

While issue #371 suggests there are hard coded filename char lengths in other components (e.g., LDT), this PR is focused on the metforcing readers so perhaps those can be addressed in additional PRs in future.

**Comment by karsenau** [comment]
Thanks, @bmcandr! And thanks for compiling that list of metforcing readers in LIS. I think if we can complete updating the metforcing readers (that we plan to retain going forward), that would be great.  That should complete this issue ticket #533.

We also have the DA obs readers and dyn. parameter readers that should be updated, but perhaps we can open a separate issue for those, and another for LDT and LVT, separately as well?

**Comment by bmcandr** [comment]
Sounds good to me. I'm happy to update the remaining metforcing readers and I'll talk to Jim and Eric about testing during our call tomorrow.

**Comment by bmcandr** [comment]
Hi all,

I circled back around on this pull request, sorry for the delay. These new commits expand the filename char length for all LIS metforcing readers **except**:

* readers in the *usaf/* directory
* readers slated for removal on the metforcing clean up spreadsheet
* some odd cases (gdasT1534, gswp1, gswp2)
    * the way the [filenames are constructed](https://github.com/NASA-LIS/LISF/blob/37c4f928ea6c877209be9aa3aaed8ecf627eb463/lis/metforcing/gswp1/get_gswp1.F90#L209) in these readers would require more modifications

I ended up expanding the filename length to 300 char in most cases based on the comments here and in #371. My rationale is as follows. In nearly all of the readers the `filename` variable ends up holding the full path to the file (path + filename). The max line length of 250 char in the lis.config file effectively constrains the length of the path to the data source directory. Therefore, my thinking is that the `filename` vars must be *at least* 250 char plus a 50 char buffer for the filename itself.

I decided to stick with the hard-coded length for now because I couldn't identify a good location to place a global integer parameter for this purpose. Any ideas?

Let me know if there are any questions or suggestions for improvement.

## Testing
I have successfully tested all the readers for which we have testcases with Intel 19:
<details>
<summary>Click to expand</summary>

* 3B42RT
* 3B42V6
* 3B42V7
* agrradps
* Bondville
* cmap
* cmorph
* ecmwf
* gdas
* gdas_lb
* geos5fcst
* gldas
* imerg_v05bfinal
* imerg_v06blate
* merra2
* mettemplate
* mrms-mask
* mrms-nomask
* nam242
* nldas2
* pals
* pet_usgs
* princeton
* princetonV3
* rfe2daily
* rfe2daily_lb
* rfe2gdas
* stageii
* stageiv
* wrfout
</details>

**Comment by bmcandr** [comment]
I need to update this PR to...
- [ ] resolve the conflict indicated below
- [ ] expand the char length of the directory variable in some of the reader structs such as line 78 below:

    https://github.com/NASA-LIS/LISF/blob/9eb0559b70ae82c0af3f31ffc78dd7aaf4f20614/lis/metforcing/merra2/merra2_forcingMod.F90#L72-L80

**Pull request closed without merging**
