### PR TITLE
Adds the support for ERA5 in LVT

### LINKED ISSUE #645: Add support for ERA5 data in LVT

### PR DESCRIPTION
**Pull request by sujayvkumar**
This commit includes the datastream plugin to process the ERA5
meterological data

Resolves #645

### CODE REVIEW

**Comment by sujayvkumar** [comment]
A testcase can be found at : 
/discover/nobackup/svkumar/LISF_testing/646

**Comment by bmcandr** [comment]
Hi @sujayvkumar,

The gridded output contains only nodata values in the *TotalPrecip* field. Is that expected?

**Comment by sujayvkumar** [comment]
Yes. The current support is only for precipitation (as noted in the inline documentation).

**Comment by bmcandr** [comment]
Thanks, I saw that note in the documentation and wanted to double-check.

Code and output looks good. Should the ERA5 options be added to the documentation at this point? If so, I can add it if you like. If not I'll go ahead and merge.

**Comment by sujayvkumar** [comment]
> Thanks, I saw that note in the documentation and wanted to double-check.
> 
> Code and output looks good. Should the ERA5 options be added to the documentation at this point? If so, I can add it if you like. If not I'll go ahead and merge.

Please add the documentation (thank you!)

**Pull request merged**
