### PR TITLE
Fix/lisf 557ww 7.3

### PR DESCRIPTION
**Pull request by shugongwang**
Some snow output variables have been renamed for JULES, Noah-MP, Noah, and CLSM. "layered" snow variables have been renamed into "prof" to be consistent with the ALMA standard. More snow output entries are added for supporting 3-layer JULES snow physics. To run these models, users need to update LIS output table according to the variable names in LIS_histDataMod.F90.

### CODE REVIEW

**Comment by emkemp** [comment]
This will have to be REJECTED.

You forked off of master and are trying to merge back into support/lisf-557ww-7.3, dragging many unrelated changes along the way.  (There are 4451 changed files!).  And you are trying to change CLSM, which is not used by 557WW, and which I argue is not a critical bug fix for 557 purposes.

I'm going to close the pull request.  Perhaps this should go into master instead, but I would still wait until we have a basic working LIS-JULES-GALWEM workflow in LIS 7.3.  We can then tackle the question of variable renaming.

**Comment by shugongwang** [comment]
Hi Eric,

I am confused. I tried carefully to folk from support/lisf-557ww-7.3 when I worked on the code. I have to find out the wrong step. I am surprised by the 4451 changed files

Since the snow variables are used by CLSM, we have to modify CLSM accordingly.

No matter which branch to go, the modification is already here. Hopefully, my time will not be wasted.

Thanks,

Shugong

**Comment by bmcandr** [comment]
Hi @shugongwang,

I took a look at your fork and it appears that you may have merged master into support/lisf-557ww-7.3 at some point.  You can see [here](https://github.com/shugongwang/LISF/tree/support/lisf-557ww-7.3) that your version of the support/lisf-557ww-7.3 branch is several hundred commits _ahead_ of the branch in the NASA-LIS/LISF upstream repo. You can fix this by force pulling from the upstream then force pushing to your fork:

```sh
git pull -f upstream support/lisf-557ww-7.3
git push -f origin support/lisf-557ww-7.3
```

Then you can create a new branch off of that and cherry pick your two commits for this PR onto the new branch. At that point you should be able to open a cleaner pull request. Let me know if you'd like any assistance on this!

**Comment by bmcandr** [comment]
Update: these instructions may not be correct. Let me identify the correct procedure.

**Comment by bmcandr** [comment]
Sorry for any confusion. Here's the correct procedure:

```sh
git checkout support/lisf-557ww-7.3
git fetch upstream support/lisf-557ww-7.3
git reset --hard upstream/support/lisf-557ww-7.3
git push -f origin support/lisf-557ww-7.3
```

That will do the following:
1. Check out the local support/lisf-557ww-7.3 branch
2. Download, but don't merge the updates from the 557 branch on the NASA-LIS/LISF fork
3. Reset the local support/lisf-557ww-7.3 branch to match the upstream
4. Push the local support/lisf-557ww-7.3 branch to your fork

From there you can create a new branch off support/lisf-557ww-7.3 and cherry pick the two commits from the fix/lisf-557ww-7.3 branch.

**Comment by shugongwang** [comment]
Thanks a lot Brendan! I sort of understand what I was wrong. I need to learn more about github.

**Comment by shugongwang** [comment]
Hi Brendan,

Sorry for replying you late and many thanks for your help!

Thanks,

Shugong

**Comment by bmcandr** [comment]
No worries, I'm happy to help!

**Comment by emkemp** [comment]
In looking at the change set, it appears the relevant changes are in the final two commits (8079948 and 
6691e1e).  So we can cherry pick (or if necessary, cut and paste) the relevant updates into a new branch.

But there are other issues:
(1) We will need to test these changes against Noah, NoahMP, and CLSM cases, not just JULES.  This may require assistance from Jim, Brendan, and David.
(2) I will need to update LVT to reflect these new changes.  This likely would need to be part of the same pull request.
(3) Would LDT need to be changed as well?  If so, those would also need to be part of the same pull request.

**Pull request closed without merging**
