### PR TITLE
CRITICAL BUG FIX:  Added "-" units for RelSMC in LVT

### PR DESCRIPTION
**Pull request by emkemp**
Added "-" units for RelSMC in LVT.

This is an operational requirement for AFW.

### CODE REVIEW

**Comment by emkemp** [comment]
PLEASE HOLD OFF ON ACCEPTING THIS COMMIT

I forgot to update the valid max and min for the extra unit option.  But I cannot work on this right now--maybe Thursday afternoon.

**Comment by dmocko** [comment]
A few requests:

1) I'd prefer to see the old code removed, instead of commented out.

2) valid_min and valid_max will also need to be updated for RELSMC.  The first valid_max value should be 100.0 (for percentage) - and we need a 3rd value for the min and max on this line.  It can also be 0.0/1.0, as it is for m3/m3.

3) Don't we also need to add units of [-] to RelSMC in LVT_histDataMod.F90?

David

**Comment by emkemp** [comment]
Pull request still  not ready yet.  Please stand by for further updates.

**Comment by emkemp** [comment]
I believe this pull request is ready for review and (hopeful) acceptance.

**Comment by dmocko** [comment]
Looks good to me.  One small request.  Instead of changing [ERR] to [ERR1], [ERR2], etc. - can you change it so the message says something similar to: '[ERR] binary output routine to diagnose....' ?

**Comment by emkemp** [comment]
Whoops!  Those changes were for debugging.  I'll fix them.

**Comment by dmocko** [comment]
Thanks for all the modifications.  Code is ready for merging.

**Pull request merged**
