### PR TITLE
More fixes to creating output directories

### PR DESCRIPTION
**Pull request by emkemp**
(1) Make sure only master process creates directory
(2) Simplify check of stat function call

### CODE REVIEW

**Comment by dmocko** [comment]
In lis/core/LIS_readConfig.F90, should we print an [ERR] log message when ios is not equal to zero?

Note we didn't log an error message before this pull request, but should we now take the opportunity to add one?

I'm referring to Line 105.

**Comment by emkemp** [comment]
I added the requested code.

**Comment by dmocko** [comment]
Thanks.  Instead of just "flush", shouldn't we "call LIS_flush"?

**Comment by emkemp** [comment]
I added calls to the LIS_flush subroutine.

(I will add that that LIS_flush is unnecessary in Fortran 2003, which now has the intrinsic library function 'flush'.  But this is not the time to remove LIS_flush from the LIS code.)

**Comment by dmocko** [comment]
Code looks good and runs fine on Discover.  If Jim's testing also looks good, then we can approve.

**Pull request merged**
