### PR TITLE
Feature/ldtwpsmode

### PR DESCRIPTION
**Pull request by sujayvkumar**
Merge the changes back to the main trunk

### CODE REVIEW

**Comment by sujayvkumar** [comment]
The testcase is staged at: 
/discover/nobackup/svkumar/LISF_testing/377

**Comment by emkemp** [comment]
Hi Sujay:

GOOD:  The code runs fine with both Intel and GCC compilers.

BAD:
(1) Your changes to ldt/core/LDT_LSMparams_Ftable.c on the use of malloc and strcpy clobber recent changes by Jim as part of the 557 security scan.  We need to reconcile this first before merging.  I will add Jim as a reviewer.

(2) ldt/core/LDT_LMLCMod.F90:  Need to update comments for LMLC_init_LIS and LMLC_init_LISHydro (subroutine names differ from comment blocks).  Some cleanup needed in LMLC_init_LISHydro, LMLC_writeHeader_LISHydro, LMLC_writeData_LISHydro to remove commented out code.

(3)  ldt/core/LDT_paramProcMod.F90:  Need to update comments for paramProcInit_LIS, paramProcInit_LISHydro, readProcParamInit_LIS, readProcParamInit_LISHydro, readParamSpecs_LISHydro, paramProcWriteHeader_LIS, paramProcWriteHeader_LISHydro, paramProcWrite_LIS, paramProcWrite_LISHydro (subroutine names differ from comment blocks).  Some cleanup needed in readParamsSpecs_LISHydro, paramProcWriteHeader_LIS, paramProcWriteHeader_LISHydro (remove some commented out code).  Remove 'use mpi' from writeParamData_LISHydro.

(4) ldt/core/LDT_soilsMod.F90:  Need to update comments for soils_init_LIS, soils_init_LISHydro (subroutine names differ from comment blocks).  Some cleanup needed to soils_init_LISHydro, soils_writeData_LIS, soils_writeData_LISHydro (remove some commented out code).

(5) ldt/core/LDT_historyMod.F90:  Some cleanup needed for writeNETCDFdataHeader_LISHydro, writeNETCDFdata_LISHydro (remove some commented out code).

(6) General comment for ldt/params/${LSMNAME}/${LSMNAME}_parmsMod.F90:  I recommend adding warning or error messages if the LISHydro output option is selected for a LSM that isn't supported.

**Comment by sujayvkumar** [comment]
Thanks Eric. All comments except 1) have been addressed.

**Comment by jvgeiger** [comment]
I must review this further.  I was trying to resolved the single conflict, but I seem to have performed a merge.

**Comment by jvgeiger** [comment]
Sorry, I confused myself.  Merging master into feature is step in resolving a merge conflict.

Sujay, would you please rerun your test.  The results now differ.  I suspect the differences are due to the recent LDT domain updates, in particular the ones involving Lambert domains.

**Comment by sujayvkumar** [comment]
The test has been updated at /discover/nobackup/svkumar/LISF_testing/377

**Pull request merged**
