### PR TITLE
Rename 'LDTSI' da observation in LIS configuration to 'USAFSI'

### PR DESCRIPTION
**Pull request by yyoon4**
For this, please change the below lines in 'lis.config' for USAF-SI DA

Data assimilation set:                               "LDTSI"   -> 
Data assimilation set:                               "USAFSI"

LDTSI data directory:       ->
USAFSI data directory:                            

If the USAFSI file output will be needed to change from "ldtsi_yyyymmddhh.nc" to "usafsi_yyyymmddhh.nc", further changes are required in LIS, as well as LVT.

### CODE REVIEW

**Comment by emkemp** [comment]
Can you update the lis/configs/lis.config.adoc file to reflect these changes?

**Comment by emkemp** [comment]
Hi Yeosang:

Friendly reminder:  Please update the lis.config.adoc file.  Thanks.

**Comment by yyoon4** [comment]
I add an option to the lis.config to specify the USAFSI DA observation name, similar to #430.
Also, update the lis.config.adoc file.

**Comment by emkemp** [comment]
@yyoon4 I pushed code updates to your branch.  These changes replace 'LDTSI' with 'USAFSI', and also changes the lis.config setting for the USAFSI prefix to:

USAFSI netcdf filename prefix:

This also updates the documentation.

**Comment by emkemp** [comment]
NOTE:  A separate pull request exists for the restricted-lisf-jules repository to handle analogous changes to the JULES DA system.

**Pull request merged**
