### PR TITLE
[GHI] Bug fixes for Medium Range Forecasts

### PR DESCRIPTION
**Pull request by emkemp**
### Description

Bug fixes for Medium Range Forecasts

* Fixed GALWEM-GD reader to increase maximum run length to 240 hours; allow runs as 06Z, 12Z, and 18Z; and correct intervals between GALWEM-GD output files.
* Added 557WW medium range forecast convention for output files.
* Updated FOC files.
* Updated documentation.

### CODE REVIEW

**Comment by cmclaug2** [comment]
This compiles with strict checks using intel and gnu compilers.  I will wait for @yyoon4's approval before accepting.

**Comment by cmclaug2** [comment]
Conflicts are introduced because #1347 was accepted before this PR.  We should be able to simply resolve these conflicts by maintaining the updates that were added in #1347

**Comment by cmclaug2** [comment]
Fixed minor conflict because a line that was edited in #1347 was also edited in this PR.  Maintained the line that held the additional comment that caused the conflict.   This procedure merged support/lisf-557ww-7.5 into fix/lis75_mr_filenames.  

I believe this was the proper way to handle this conflict, however I will consult with @jvgeiger before merging.

**Comment by emkemp** [comment]
I just noticed a problem with the output interval when run at 06Z.  I'll mark this as DRAFT.  Please DO NOT merge until I make more fixes.

**Comment by emkemp** [comment]
Okay, the fix to the problem mentioned earlier is to change the output to three hourly.  This in fact is the requirement, but for whatever reason the FOC files we were using were set to daily output.  Updates have been pushed (no source code changes), and I've replaced the DRAFT label with HIGH PRIORITY.

We cannot wait for @yyoon4 to review, as he is on leave until mid-June and the code must be delivered by then.

I have semi-formal test cases that I used to debug the reader.  Look in /discover/nobackup/projects/usaf_lis/emkemp/AFWA/sample_data/LISF_mr_filenames/work_mr_bugfixes if you wish to run before accepting the pull request.

**Comment by cmclaug2** [comment]
@emkemp,

Thanks @emkemp. I've taken a look at your output and everything looks as expected.   I am going to do a quick validation run and if everything matches, accept.

**Comment by cmclaug2** [comment]
@emkemp After ensuring I used the same compiler settings as you, I successfully reproduced your output.  I accept.

**Pull request merged**
