### PR TITLE
Updated FOC settings for latest patches

### PR DESCRIPTION
**Pull request by emkemp**
### Description

Updates IMERG version and radiation settings, for latest patches to support/lisf-557ww-7.5.

### CODE REVIEW

**Comment by emkemp** [comment]
I'm still waiting for a GO/NO GO decision based on the results of the tests on HPC11, so this is currently a draft pull request.

**Comment by emkemp** [comment]
Jerry just gave the green light based on the results of the NRT, NRT-Streamflow, and MR test results.  So I am upgrading this PR from "draft".

**Comment by emkemp** [comment]
This is the last PR needed before shipping LISF 7.5.15 for 557 WW.

**Comment by jvgeiger** [comment]
Hello @emkemp.

lis/utils/usaf/s2s/global_usaf_forc/input/lis.config.template uses './input/restarts/'.  The other lis.config files were changed to use './input/rstfiles'.

Is that an issue?

**Pull request merged**
