### PR TITLE
USAFSI updates, including support for SST GRIB1 backup support

### PR DESCRIPTION
**Pull request by emkemp**
### Description

USAFSI updates for Air Force.

* Added support for FNMOC GRIB1 SST files if GOFS is missing
* Added write statements to better log which files are being searched for, and which are missing
* Minor bug fix to LVT for constructing full path to USAFSI netCDF file.
* Updated sample lvt.config file to fix USAFSI related entry
* Updated LVT scripts to reflect current Discover working environment

No test case.

### CODE REVIEW

**Review by jvgeiger — CHANGES_REQUESTED** [review]
Would you please document this new entry, "USAFSI FNMOC SST GRIB1 data directory:", in the ldt.config.adoc documentation?

**Comment by emkemp** [comment]
Good catch.  Looking at this closer also identified an unused ldt.config entry also involving SST.  I am revising and retesting.

**Comment by emkemp** [comment]
Okay, the ldt.config doc and sample have been updated.  Please let me know if you have any other concerns.

**Comment by jvgeiger** [comment]
Looks good.  Thanks!

**Pull request merged**
