### PR TITLE
Feature/swchanges

### PR DESCRIPTION
**Pull request by sujayvkumar**
### Description

This pull request includes a number of surface water related updates: 
1. assimilation of water level data
2. urban flood model
3. two-way coupling in HyMAP2
4. tide data input as a boundary condition to HYMAP2

### CODE REVIEW

**Comment by bmcandr** [comment]
Compiles and runs without issue with Intel19 compilers. Regression tested with:
* _noah36_ open loop testcase (from internal suite)
* THySM testcase from #756 with HYMAP2 enabled

I will go ahead and merge into _eis-freshwater_.

**Comment by sujayvkumar** [comment]
Thanks @bmcandr

**Comment by bmcandr** [comment]
Hi @NASA-LIS/lsm team, can you please review the changes to the files below? We are working to get these changes merged into master to enable Augusto to continue work on a 557 deliverable. Thanks!

```
lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmpdrv_401.F90
lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
```

**Comment by karsenau** [comment]
Hi @bmcandr,
Is the branch those two NoahMP401 physics routines are in -- NASA-LIS:eis-freshwater?

**Pull request merged**
