### PR TITLE
Enables calibration interfaces in NoahMP401

### LINKED ISSUE #514: Add calibration support within NoahMP401

### PR DESCRIPTION
**Pull request by sujayvkumar**
This updates includes the following changes:
1. NoahMP401 has been updated to enable spatially distributed specification of model parameters
2. This also allows the parameters to be exposed for optimization
3. Added interfaces for parameter estimation within Noahmp401
4. Added support for University of Arizona snow data for use in parameter estimation

Resolves #514

### CODE REVIEW

**Comment by sujayvkumar** [comment]
A testcase is at :  /discover/nobackup/svkumar/LISF_testing/514

**Comment by bmcandr** [comment]
Hi Sujay,

I have reviewed your changes and found the following issues to review/address:

* Minor conflict in `lis/make/default.cfg` (likely due to recent changes merged in #509)
* File `lis/optUE/type/paramestim/obs/UAsnow/UAsnow_obsMod.F90`
    * 74: Add Description?
    * 119-133: hard coded grid projection variables
        * Add comment describing grid data being used?
        * Include technical information, reference to paper if it exists?
        * Indicate that `lis/core/LIS_PRIV_rcMod.F90` describes what is going on with `gridDesc`?
* File `lis/optUE/type/paramestim/obs/UAsnow/read_UAsnowobs.F90`
    * 102-105: Add comment describing purpose of if-then block? (i.e., why `mm = 10`)
* File `lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_setup.F90`
    * 572-585: add comment describing hard coded values (where did they come from?)
* File `lis/surfacemodels/land/noahmp.4.0.1/pe/NoahMP401_peMod.F90`
    * 100, 102, 124-125: remove commented code if not needed
    * 613-624: change `print` call to `write(LIS_logunit, *)`?
* File `lis/surfacemodels/land/noahmp.4.0.1/pe/NoahMP401_set_pedecvars.F90`
    * 100, 184-185, 187, 189, 468, 475: remove commented code if not needed
* File `lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmpdrv_401.F90`
    * 706: remove commented code if not needed

**Comment by sujayvkumar** [comment]
All updates have been done except: 

> File lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_setup.F90
> 572-585: add comment describing hard coded values (where did they come from?) -

These came from the NoahMP physics

> File lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmpdrv_401.F90
> 706: remove commented code if not needed

These commented lines are left as is for posterity (and to let the users know that it was moved for exposing model parameters for OPTUE)

**Comment by bmcandr** [comment]
The changes look good and they pass compile and run tests. Merging.

Compile and run results:

    - [x] SLES 11/Intel 18 -- *PASS*
        * Results identical to target
    - [x] SLES 11/GNU 4 -- *PASS*
        * Results ~identical to target

**Pull request merged**
