### PR TITLE
GRACE DA for NoahMP (updates 3.6, adds 4.0.1)

### PR DESCRIPTION
**Pull request by bailinglee**
fix in read perturbation restart file from Wanshu; code changes related to scale and descale TWS components in da_tws;
fixes in LDT for reading 0.25 degree GRACE data

### CODE REVIEW

**Comment by emkemp** [comment]
Hi Bailing:

Can you provide two simple test cases, one for LDT and one for LIS, so I can test replicating your results?

**Comment by bailinglee** [comment]
Hi Eric,
   It’s not simple to test GRACE data assimilation.  But let’s try.
   I put two configure files in /discover/nobackup/bli/share/forEric.  The test for LDT is over the global domain and the one for LIS is for a small central CA domain.  All the “input” in the config files point to  /discover/nobackup/projects/lis/.  Links for the restart file for running LIS and GRACE data are also provided in the directory.

Let me know if you run into any issues,

Bailing

**Comment by bailinglee** [comment]
Forgot one link.  The GRACE data directory for running LIS is /discover/nobackup/projects/wldas/bli/da_runs/ldt_run/OUTPUT_0125/

Bailing


From: Li, Bailing (GSFC-617.0)[UNIVERSITY OF MARYLAND]
Sent: Friday, August 2, 2019 2:27 PM
To: NASA-LIS/LISF <reply@reply.github.com>; NASA-LIS/LISF <LISF@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [EXTERNAL] Re: [NASA-LIS/LISF] NoahMP36_readrst.F90 from Wanshu (#216)

Hi Eric,
   It’s not simple to test GRACE data assimilation.  But let’s try.
   I put two configure files in /discover/nobackup/bli/share/forEric.  The test for LDT is over the global domain and the one for LIS is for a small central CA domain.  All the “input” in the config files point to  /discover/nobackup/projects/lis/.  Links for the restart file for running LIS and GRACE data are also provided in the directory.

Let me know if you run into any issues,

Bailing

**Comment by emkemp** [comment]
Hi Bailing:

I don't have permission to access CSR_GRACE_GRACE-FO_RL06_Mascons_all-corrections_v01.nc (this is a symbolic link that points to /discover/nobackup/projects/wldas/bli/da_runs/ldt_run/grace_da_irr/

**Comment by bailinglee** [comment]
Ok, try it again.

**Comment by emkemp** [comment]
Thanks!

New problem:  Where is the input LIS data for LDT?  I don't see a run_ecmwf_ol_scl/OUTPUT directory.

**Comment by bailinglee** [comment]
Sorry.  That one is in /discover/nobackup/projects/ms_snow_da/bli/.  You should have the permissions.

**Comment by emkemp** [comment]
Thanks!

New problem:  I don't have read permission for /discover/nobackup/emkemp/LIS/grace_da_noahmp3.6/LIS/wwao/ldt_run/lis_input_noahmp36_cenCal_0.125.nc

**Comment by bailinglee** [comment]
Try it again.

**Comment by emkemp** [comment]
Thanks!

I compiled LDT and LIS with Intel 18 and GNU 7.3 compilers--no compile-time problems noticed.  LDT appears to run w/o issue, but I don't have a way to visualize the output.

LIS fails with Intel 18 (compiled with -O2) with this error:

[INFO] LIS cycle time: 10/01/2002 09:00:00
 [INFO] getting file2a.. 
 ./wwao/input/MET_FORCING/NLDAS2.FORCING/2002/274/NLDAS_FORA0125_H.A20021001.100
 0.002.grb
 [WARNING] more than half of the ens violate the bounds           4
 [ERR] Ensemble structure violates physical bounds 
 [ERR] Please adjust the perturbation settings ..
 [ERR] endrun is being called

Did you see this with your run?

**Comment by bailinglee** [comment]
I see that error too.  That actually means the code is running.  To avoid this error which is due to too dry conditions, turn off “Apply perturbation bias correction”.

Bailing

**Comment by bailinglee** [comment]
Hi Eric,
    If it helps, I created a Grads control file for viewing GRACE OBS created by LDT:
/discover/nobackup/bli/share/forEric/GRACE_obs.ctl

Bailing

**Comment by emkemp** [comment]
Good morning Bailing:

I dusted off this pull request and started over with a fresh clone and fresh work directory, copying files provided by you.  At the moment I am working with LDT.  The output appears reasonable, but I don't see anything in your directories to check against.  Please provide a set of GRACE_obs_*.bin files for comparison and incorporation until a new test case.

**Comment by emkemp** [comment]
Regarding the LIS code changes:  There are several locations in surfacemodels/land/noahmp.3.6/da_tws/noahmp36_settws.F90 where 'print*' and 'stop' were added.  These need to be changed to 'write(LIS_logunit,*)' and 'call LIS_endrun', respectively.

**Comment by emkemp** [comment]
DISREGARD PREVIOUS MESSAGE ABOUT PRINT* AND STOP.

The objectionable code is in master, and the version in this pull request removes it.  (I got the file versions confused.)

**Comment by bailinglee** [comment]
Hi Eric,
     What was the directory that I sent to you?  Sorry. It’s been too long.

Bailing

**Comment by emkemp** [comment]
Hi Bailing:

The original directory is /discover/nobackup/bli/share/forEric.  One of the files in there is linked to /discover/nobackup/projects/wldas/bli/da_runs/ldt_run/grace_da_irr/, but the files in that directory do not appear to be for the global LDT domain.

**Comment by bailinglee** [comment]
Hi Eric,
     Did I mention global somewhere?  I have only tested the DA/Noah-MP on a small central CA and a CA domain and have never tried it globally.

Bailing

**Comment by emkemp** [comment]
Hi Bailing:

The LDT test you provided in /discover/nobackup/bli/share/forEric is global.

**Comment by bailinglee** [comment]
Hi Eric,
     The test case is for CLSM.  Yes, I have the global GRACE obs output in /discover/nobackup/projects/nca/bli/run_ecmwf_da_rl06/ldt_run/GRACEOBS/.

Let me know if you have problems accessing the files,

Bailing

**Comment by emkemp** [comment]
Hi Bailing:

I resumed work on the NoahMP36 GRACE pull request (#216).  I compared the GRACEOBS files produced by running LDT with those you provided in /discover/nobackup/projects/nca/bli/run_ecmwf_da_rl06/ldt_run/GRACEOBS.  The output are very similar but not identical--I see differences in Greenland and in South America. This is with Intel 18 with optimization turned on.  Do you happen to remember what compiler you used for your testing?

**Comment by emkemp** [comment]
Hi Bailing:

Regarding LIS testing for pull request #216, do you have sample LIS output I can compare too?

**Comment by bailinglee** [comment]
Hi Eric,
  Based on the configure file I provided, you can use output from this directory for comparison:
/discover/nobackup/projects/wldas/bli/da_runs/OUTPUT_0125/EXP019

Bailing

**Comment by bailinglee** [comment]
Hi Eric,
    I used Intel 18 with -O2.  Are you using the GRACE file I used? If you are using a newer version of GRACE data, you might see some changes.

Bailing

**Comment by emkemp** [comment]
Hi Bailing:

It turns out I do not have access permission to /discover/nobackup/projects/wldas/bli/wwao/NOAHMP36_OUTPUT_LIST.TBL.dyn.noforcing, so my LIS test run is not producing any output.  Can you please update the permissions for that file path?

**Comment by emkemp** [comment]
Hi Bailing:

My copy of CSR_GRACE_GRACE-FO_RL06_Mascons_all-corrections_v01.nc is identical to your copy in /discover/nobackup/projects/wldas/bli/da_runs/ldt_run/grace_da_irr/CSR_GRACE_GRACE-FO_RL06_Mascons_all-corrections_v01.nc

**Comment by bailinglee** [comment]
Done.  Sorry about that.

**Comment by bailinglee** [comment]
Hi Eric,
   The ldt configure file I provided to you is for CLSM, not Noahmp.  Are there two tickets related to GRACE DA? One is for LDT and another is for LIS?

Bailing

**Comment by emkemp** [comment]
Hi Bailing:

You provided two test cases for pull request #216.   Please see https://github.com/NASA-LIS/LISF/pull/216 to review.

**Comment by emkemp** [comment]
Hi Bailing:

I'm now seeing similar but not identical results from LIS compared to your provided results.

Since both LIS and LDT differ, I suspect the data you provided in your test cases was not generated with the exact same code as in the pull request.  Could you please regenerate your test case output files using the code in your feature/grace_da_noahmp3.6 branch and point me to the new files?

**Comment by bailinglee** [comment]
Hi Eric,
    What directory did you compare for the LDT output?  The output I generated should be here:
/discover/nobackup/projects/nca/bli/run_ecmwf_da_rl06/ldt_run/GRACEOBS/
    I will see if I can find the LIS output.

Bailing

**Comment by emkemp** [comment]
Hi Bailing:

Yep, those are the files I'm comparing to.  GraDS shows very close but not identical results.  Take a look in /discover/nobackup/emkemp/LIS/grace_da_noahmp3.6/work_ldt.  GRACE_obs.ctl points to my output, GRACE_obs_bli.ctl points to yours.

**Comment by bailinglee** [comment]
Hi Eric,
     I noticed the Ending year in the LDT file I provided is 2010 while the GRACE baseline ending year is 2018.  If this is what you used to run LDT, can you change 2010 to 2018 and run it again?

Bailing

**Comment by emkemp** [comment]
Hi Bailing:

My extended LDT run fails in 2017, due to a read permission problem:

./run_ecmwf_ol_scl/OUTPUT//SURFACEMODEL/201702/LIS_HIST_2017
 02020000.d01.nc

(My run_ecmwf_ol_scl is symbolically linked to /discover/nobackup/projects/ms_snow_da/bli/run_ecmwf_ol_scl; the earlier files are readable).

Can you update the permissions for the later open loop history files?

**Comment by bailinglee** [comment]
Hi Eric,
    Can you change the open loop dir to: /discover/nobackup/projects/nca/bli/run_ecmwf_ol_scl/OUTPUT/
   ?
    Sometime after I sent you the testcase, we have moved all files to projects/nca.

Bailing

**Comment by emkemp** [comment]
Hi Bailing:

Switching to the new open loop dir fixes the extension problem, and I now see identical results from LDT.  Progress!

**Comment by bailinglee** [comment]
Excellent!

**Comment by emkemp** [comment]
Okay, I reran the LIS test, and I'm still getting differences from your LIS results.  I'll try to review my setup again next week to see if I made a mistake.  Stay tuned.

**Comment by bmcandr** [comment]
Hi @bailinglee and @emkemp, I'd like to check in on the status of this pull request since it has been sitting for quite a while. Have there been any updates since the last effort to get this resolved? I combed through the thread and collected what I believe to be the correct input and target data. Using these files I was able to reproduce the LDT output, but not the LIS output as Eric mentioned.

**Comment by bailinglee** [comment]
Hi Brandan,
   No, I have no update on this ticket.  I think Eric was trying to test the LIS fix more than a year ago but didn't go through it.
   The timing of your email is perfect.  I am planning to check the GRACE DA code that I implemented for LIS/NoahMP4.01. into GitHub.  At least two users are waiting for this implementation.   It's been a while since I created that pull request.  Do I need to create a pull request before checking out code and where do I do that?  I do have Jim's tutorial on how to check out code from GitHub.

Thanks,
Bailing

**Comment by bmcandr** [comment]
Hi Bailing,

Great! You do not need to open a new pull request to checkout the code, just run `git checkout feature/grace_da_noahmp.3.6` from within your Git repository. I see that your fork of LISF is a bit behind the NASA-LIS master branch so I would recommend bringing it up to date before continuing your work. Let me know if you need any assistance with that.

**Comment by bailinglee** [comment]
Hi Brandan,
     Hmm, what does the git checkout command you provided do? Should I run this first before updating my LISF from the NASA-LIS branch?   I think I need your help as I don't want to mess it up which would cause more trouble for you.  Let me know when it's a good time for you.  We can talk over Teams.

Thanks,
Bailing

**Comment by bmcandr** [comment]
This pull request is being closed to separate fixes from new features.

**Pull request closed without merging**
