### PR TITLE
feature/CCIupdate

### PR DESCRIPTION
**Pull request by TimLahmers**
### Description

Updates ESA-CCI soil moisture reader to include capability to specify sensor type. This change permits users to specify the sensor type when using the ESA-CCI dataset. This is useful for Soil Moisture DA, as the current set "COMBINED" dataset normalizes CCI data to GLDAS, which is not optimal for DA.

This is specified by a new variable in both the ldt.config and lis.config files:
ESA CCI soil moisture sensor type:
Valid Options Include: 'passive', 'active', and 'combined' 

Resolves Issue #1134 

### Testcase

LIS and LDT Tested by Pang Liu:
/discover/nobackup/projects/eis_freshwater/pliu/WORKING/EIS_FIRE/ldt_run
/discover/nobackup/projects/eis_freshwater/pliu/WORKING/EIS_FIRE/lis_run

### CODE REVIEW

**Comment by TimLahmers** [comment]
Some bugs in the configuration of LIS for the test-runs required in this PR were uncovered and corrected. The latest test directories are listed below:
/discover/nobackup/projects/eis_freshwater/pliu/WORKING/EIS_FIRE/ldt_run
/discover/nobackup/projects/eis_freshwater/pliu/WORKING/EIS_FIRE/lis_run

These issues only affected the configuration and, and no code changes were required to resolve them.

**Comment by jvgeiger** [comment]
Hello @TimLahmers 

First, I resolved the conflict that GitHub mentioned above.  So you may ignore that.

I am trying to run LDT.  I see 5 ldt.config files in ldt_run.  I suspect that I need to use ldt.config_010.ccicombined because none of the others contain the new `ESA CCI soil moisture sensor type:` configuration option.  Unfortunately, I cannot read that file.  Would you set the permissions to 644 for that file?

Thanks,
Jim

**Comment by TimLahmers** [comment]
@jvgeiger Thanks for the update! Pang ran these LDT simulations, so I will direct your message to him. I will let you know his response (I am not sure what his GitHub account name is).

**Comment by TimLahmers** [comment]
@jvgeiger I have an update from Pang. There are two ldt.config files that he suggests you test. They are ldt.config_010.ccicombined and ldt.config_010.ccipassive. The ldt.config file for "combined" is the old default configuration (it will produce the same CCI results before I made the change since CCI used to be set to "combined" automatically). The ldt.config file for "passive" is one of the new options and the configuration we are using for the EIS-Freshwater project. Please let me know if you have issues accessing these files or any questions about the configuration.

**Comment by jvgeiger** [comment]
Thanks.

**Comment by jvgeiger** [comment]
Hello @TimLahmers 
Would you please give me read permission (chmod 644) to the files in /discover/nobackup/projects/eis_freshwater/pliu/WORKING/EIS_FIRE/ldt_run/OUTPUT?

Thanks,
Jim

**Comment by jvgeiger** [comment]
Hello @TimLahmers,

Would you please reset some file permissions?

```
cd /discover/nobackup/projects/eis_freshwater/pliu/WORKING/EIS_FIRE/lis_run
chmod 644 forcing_variables_v2.txt
chmod 755 OUTPUT_CCIDA
find OUTPUT_CCIDA -type d -exec chmod 755 \{\} \;
find OUTPUT_CCIDA -type f -exec chmod go+r \{\} \;

cd /discover/nobackup/projects/eis_freshwater/pliu/WORKING/EIS_FIRE/ldt_run
chmod 644 LIS_EnRST_NOAHMP401_201312312330.WSU.d010.nc
```

Thanks, Jim

**Comment by TimLahmers** [comment]
@jvgeiger I was away from my email during the weekend, but it looks like Pang was able to fix these permissions issues. Please let me know if you have any other issues with datasets or model settings for this PR.

**Pull request merged**
