### PR TITLE
Added LVT reader to support SMAP-E-OPL data

### LINKED ISSUE #1327: LVT reader for SMAP-E-OPL
We are enhancing the LVT to read the new SMAP retrieval product (SMAP-E-OPL). 

--assignee @LIS-navari

### PR DESCRIPTION
**Pull request by LIS-navari**
### LVT reader for SMAP-E-OPL

This PR adds support to read new SMAP retrieval product (SMAP-E-OPL). 

Resolves #1327

### Testcase
/discover/nobackup/projects/usaf_lis/mnavari/AF/SMAP_E_OPL/analysis_mn/SMAP_E_OPL_vs_NRT_PR_1328

### CODE REVIEW

**Comment by cmclaug2** [comment]
@LIS-navari I was able to compile your updates with intel and gnu compilers.  I was also able to run your testcase and replicate your output.  I will perform a final code review.  

Before accepting, the following items will need attention:

- Copywrite notices at the top of your new SMAP datastream files need to be updated.
- The new SMAP retrieval product needs to be added as an "analysis data source" in the lvt.config.adoc file. 

Thanks!

**Comment by LIS-navari** [comment]
Hi @cmclaug2 
Could you please elaborate on the following
"Copywrite notices at the top of your new SMAP datastream files need to be updated."

Thanks

**Comment by cmclaug2** [comment]
@LIS-navari,
 
Please update the copywrite year in `./readSMAPEOPL_SMObs.F90` and `./SMAPEOPL_SM_obsMod.F90` to 2022.

**Comment by cmclaug2** [comment]
@LIS-navari,

I made a minor edit to the config file and fixed my own typo. This PR is completed and ready to merge.  Thank you.

**Pull request merged**
