### PR TITLE
Feature/s2s/lisf 557ww 7.5

### PR DESCRIPTION
**Pull request by smahanam**
### Description

Replace this text with a concise description of *what* was changed and *why*.

### CODE REVIEW

**Comment by smahanam** [comment]
Hi @emkemp @jvgeiger @karsenau, @razamora-nasa 

We are happy to open this PR.
I'll let @karsenau take over from here.
Thanks,
Sarith

**Comment by karsenau** [comment]
Thanks, @smahanam!

**Comment by jvgeiger** [comment]
Hello,

I have not done a code review, but I believe that the update to env/discover/lisf_7.5_intel_2021.4.0 belongs in its own modulefile.

**Comment by karsenau** [comment]
Thanks @jvgeiger.
Would you like us to make a new commit and PR for that update?

**Comment by emkemp** [comment]
I'm doing a separate test compile of LIS.  Will report results.

**Comment by emkemp** [comment]
Code compiles w/o issue.

@jvgeiger , do you object to accepting this PR?

**Pull request merged**
