### PR TITLE
Fix LVT Max and Min metric time series output

### PR DESCRIPTION
**Pull request by dmocko**
This pull request fixes time series output for the
Max (maximum) and Min (minimum) metrics from LVT.

The MEAN metrics code was cleaned-up as well, but
the output for this metric will not change at all.

A testcase is coming soon.

Resolves: #705

### CODE REVIEW

**Comment by dmocko** [comment]
Testcase (with GrADS .xdf files and scripts) available here:
    /discover/nobackup/projects/lis/tools/pull_requests/706

**Comment by bmcandr** [comment]
The changes look good and testing produced identical output to the target with Intel 19 and GNU4 compilers. I will go ahead and merge. Thanks @dmocko!

**Comment by emkemp** [comment]
I was testing the same pull request, and noticed some differences in the MAX_SUMMARY_STATS.dat file.  I'll double check to see if this was just user error.

**Comment by bmcandr** [comment]
Thanks for the heads up. Diff says the *_SUMMARY_STATS.dat are identical on my end.

**Comment by emkemp** [comment]
I was getting zeros for the different regions (NWFRC, MBFRC, etc).  These are all defined by a Grads binary file, with the path given in TS_LOCATIONS_daily.TBL.

I compiled my LVT test with little endian.  I'm recompiling now with big endian to see if that was the issue.

**Comment by emkemp** [comment]
It was the endianness flag.  When I switch to big endian, the results are identical.

No (retroactive) objections to this pull request.  :-)

**Comment by dmocko** [comment]
Sorry for the trouble, @emkemp 

I shouldn't have included a path to a big_endian file in the TS_LOCATIONS file, especially: 1) without bundling up this file in the testcase tarball, and 2) not specifying to try this testcase with a particular endian-ness.

@bmcandr - If you will be adding this testcase to the suite, I would be glad to change my TS_LOCATIONS file so it doesn't use a binary file, and make new input/output testcase tarballs.  Just let me know.

**Pull request merged**
