### PR TITLE
add features for grace-da with noahmp.4.0.1

### LINKED ISSUE #61: GRACE DA not working properly with Noah_MP
There are a few things related to this issue:
1) some code changes made by Wanshu Nie in NoahMP36_readrst.F90 were not checked into the master branch.   
2) The minimal smc threshold is hard coded in noahmp36_settws.F90 while the min and max values provided in the perturbation attribute file and retrieved in noahmp36_qctws.F90 are not being used.
3)These is no qc check for smc2, smc3, and smc4 in noahmp36_qctws.F90.

### LINKED ISSUE #753: Add GRACE-DA to LIS-NoahMP.4.0.1
Building on Bailing's work to add GRACE-DA feature to NoahMP.4.0.1 in FW branch. 
Tested with GSFC mascon product provided by Bryant.

### PR DESCRIPTION
**Pull request by KathyNie**
### Description

Add the GRACE-DA capability with NoahMP.4.0.1.

Resolves #753 
Potential improvement needed to fully resolve #61

### CODE REVIEW

**Review by jvgeiger — COMMENTED** [review]
Thanks Wanshu.

1) Would you please remove the commented out code, including "#if 0", from these files:

lis/dataassim/algorithm/enksgrace/enksgrace_Mod.F90
lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_descale_tws.F90
lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_scale_tws.F90
lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_settws.F90

2) For lines 80 through 115, in
lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_datws_Mod.F90, does @sujayvkumar  have to provide missing functionality?

3) Does lis/metforcing/imerg/reset_imerg.F90 belong in this pull request?

**Comment by jvgeiger** [comment]
@sujayvkumar, would you please review lis/dataassim/algorithm/enksgrace/enksgrace_Mod.F90?  This is the file that we cleaned up, but Wanshu had to reinstate some of the code.

**Comment by KathyNie** [comment]
> Thanks Wanshu.
> 
> 1. Would you please remove the commented out code, including "#if 0", from these files:
> 
> lis/dataassim/algorithm/enksgrace/enksgrace_Mod.F90
> lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_descale_tws.F90
> lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_scale_tws.F90
> lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_settws.F90
> 
> 1. For lines 80 through 115, in
>    lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_datws_Mod.F90, does @sujayvkumar  have to provide missing functionality?
> 2. Does lis/metforcing/imerg/reset_imerg.F90 belong in this pull request?

Hi Jim,

1. cleaned up.
2. The part of code is never used for my experiments. I will defer to Sujay for this question.
3. Yes, this subroutine is added to support GRACE-DA run driven by IMERG precipitation dataset, which is necessary for this project.

Thanks,
Wanshu

**Comment by sujayvkumar** [comment]
Looks good to me.

**Comment by jvgeiger** [comment]
Hello @sujayvkumar,  in file lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_datws_Mod.F90, lines 81 through 115 are commented out with the comment "TBD: SVK".

Is this old code that should be deleted or are you providing some updates?

**Comment by jvgeiger** [comment]
I am reviewing lis/dataassim/algorithm/enksgrace/enksgrace_Mod.F90 on more time.

**Comment by sujayvkumar** [comment]
> Hello @sujayvkumar, in file lis/surfacemodels/land/noahmp.4.0.1/da_tws/noahmp401_datws_Mod.F90, lines 81 through 115 are commented out with the comment "TBD: SVK".
> 
> Is this old code that should be deleted or are you providing some updates?

Yes, this commented code block can be removed.

**Comment by jvgeiger** [comment]
@KathyNie, I will also remove lines 800 through 867 in lis/dataassim/algorithm/enksgrace/enksgrace_Mod.F90.

Then I will retest.

**Comment by KathyNie** [comment]
Thank you Jim and Sujay!

**Pull request merged**
