### PR TITLE
Feature/era5forc

### PR DESCRIPTION
**Pull request by sujayvkumar**

### CODE REVIEW

**Comment by sujayvkumar** [comment]
LDT and LIS test cases are staged at : 
/discover/nobackup/svkumar/LISF_testing/445

For the LDT testcase, run './LDT ldt.config_noahmp'

**Comment by jvgeiger** [comment]
Hello Sujay,

Please:

* Resolve conflict
  * See Section "4.7.2. Pull request with conflict" in "Working with GitHub" document

* ldt/metforcing/era5/get_era5.F90
  * Replace `write(*,*)` with `write(LDT_logunit,*)`; see lines 188 and 218
  * Replace calls to `stop` with calls to `LDT_endrun`; see lines 189 and 219

* ldt/configs/ldt.config.adoc
  * Document
    * "ERA5 forcing directory:"
    * "ERA5 forcing tile to grid mapping file:"
    * "ERA5 forcing terrain height file:"
    * See ldt/metforcing/era5/readcrd_era5.F90

* ldt/plugins/LDT_param_pluginMod.F90
  * Fix comment at line 1238

* lis/metforcing/era5/get_era5.F90
  * Replace `write(*,*)` with `write(LIS_logunit,*)`; see lines 189 and 220
  * Replace calls to `stop` with calls to `LIS_endrun`; see lines 190 and 221

* lis/configs/lis.config.adoc
  * Document
    * "ERA5 forcing directory:"
    * "ERA5 forcing tile to grid mapping file:"
    * See lis/metforcing/era5/readcrd_era5.F90

* lis/plugins/LIS_metforcing_pluginMod.F90
  * Fix comment at line 890


Thanks,
Jim

**Comment by bmcandr** [comment]
Hi @sujayvkumar, just want to get this PR back on your radar!

**Comment by bmcandr** [comment]
Hi @sujayvkumar,

During testing I'm encountering the following error:

```sh
forrtl: severe (408): fort: (2): Subscript #1 of the array ERA5FORC has value 962 which is greater than the upper bound of 961
```

I am running in parallel with 256 tasks as indicated in the `lis.config` and `lis.job` files contained in your test case directory. There is a difference in the local domains listed our `lislog` files that seems to suggest this error might be related to how the domain is being split out to each process ([log diff here](https://github.com/NASA-LIS/LISF/files/4794222/lislog_cmp.txt)). Any thoughts?

(btw, I'm running LIS with a `lis_input.d01.nc` file created by running LDT compiled from your commits that `nccmp` says is identical to the one you provided)

**Comment by sujayvkumar** [comment]
How many processors are you running with? I am unable to reproduce the error.

**Comment by bmcandr** [comment]
256 processors. Here is my slurm job script that differs only slightly from your `lis.job` file:

```sh
#!/bin/bash
#SBATCH --job-name=run-pr485-intel19
#SBATCH --ntasks=256
#SBATCH -o lis-485-output.%j
#SBATCH -e error-intel19.%j
#SBATCH --time=2:00:00
#SBATCH --account=XXXX

module purge
module load lisf_7_intel_19_1_0_166

echo $DEV_ENV

ulimit -s unlimited

mpirun -np 256 ./LIS.intel19
```

**Comment by sujayvkumar** [comment]
Found the bug!

**Pull request merged**
