### PR TITLE
Feature/ldt mmf groundwater

### PR DESCRIPTION
**Pull request by smahanam**
This PR is related to the LDT updates for Issue [Issue #1037](https://github.com/NASA-LIS/LISF/issues/1037).

**DESCRIPTION**
LDT was updated to produce 5 MMF parameters FDEPTH, RECHLIM, RIVERBED, EQWTD, and HGT_M on LIS tiles using global 1k  GEOGRID data files at:
/discover/nobackup/projects/lis/LS_PARAMETERS/noahmp401_parms/groundwater/

**SOURCE CODE UPDATES**
All updates are in the below directory.
ldt/params/Noah/
i) Noah_parmsMod.F90 was updated
ii)  module_MMF_groundwater.F90 is a new module which serves as the LDT GEOGRID data reader.
iii) read_geogrid.c and write_geogrid.c came with geogrid data that are good to read/write data in GEOGRID format. module_MMF_groundwater.F90 calls read_geogrid.c to read GEOGRID tiles.
iv) core/LDT_paramMaskCheckMod.F90:  MMF scheme is active in lake/water grid cells. Thus, when MMF parameters are being processed, new "leave_good_data" optional argument in SUBROUTINE LDT_contIndivParam_Fill  is used to leave acceptable parameter values in lake/water grid cells intact.

**LDT Config file**
Below text must be added to the LDT config file in order to process MMF parameters.

\#######################################################
\# MMF Groundwater parameters:
\# NOTE: Currently, Noah-MP.4.0.1 is the only model that
\#       supports the MMF groundwater scheme.
\#######################################################

Process Noah-MP-4.0.1 MMF groundwater parameters: .true.

MMF transmissivity dir:                   ./LS_PARAMETERS/noahmp401_parms/groundwater/f/
MMF climatological recharge dir:          ./LS_PARAMETERS/noahmp401_parms/groundwater/recharge/
MMF riverbed elevation dir:               ./LS_PARAMETERS/noahmp401_parms/groundwater/riverbed/
MMF equilibrium water table depth dir:    ./LS_PARAMETERS/noahmp401_parms/groundwater/wtd/
MMF HGT_M dir:                            ./LS_PARAMETERS/noahmp401_parms/groundwater/topo_gmted2010_30s/

MMF raw data are on the30-arcsec  latlon grid and LDT uses UpscaleByAveraging to interpolate to the model grid.
MMF map projection:          latlon
MMF spatial transform:       average

FDEPTH fill option:          neighbor
FDEPTH fill radius:          0       # Number of pixels to search for neighbor
FDEPTH fill value:           100.
FDEPTH water value:      100.   # suitable value for lakes/rivers in case GEOGRID didn't have valid data at the location. 

RECHCLIM fill option:        neighbor
RECHCLIM fill radius:        0       # Number of pixels to search for neighbor
RECHCLIM fill value:         -1.
RECHCLIM water value:    -1   # suitable value for lakes/rivers  in case GEOGRID didn't have valid data at the location. 

EQWTD fill option:           neighbor
EQWTD fill radius:           0       # Number of pixels to search for neighbor
EQWTD fill value:            0.
EQWTD water value:       0.   # suitable value for lakes/rivers  in case GEOGRID didn't have valid data at the location. 

HGT_M fill option:           neighbor
HGT_M fill radius:           0       # Number of pixels to search for neighbor
HGT_M fill value:            0.

### CODE REVIEW

**Comment by bmcandr** [comment]
Hi @smahanam, can you please share a full ldt.config file along with the LIS parameter file that you generated? I need these to be able to test your changes.

**Comment by smahanam** [comment]
> Hi @smahanam, can you please share a full ldt.config file along with the LIS parameter file that you generated? I need these to be able to test your changes. You can point to a location on Discover rather than uploading them here.

Hi @bmcandr,
Lambert Conical Grid example:
/gpfsm/dnb32/smahanam/LIS/MMF-GroundWater/ldt_tests/ldt.config.3Rivers_MMF_lambert_Ridges

Lat/Lon case (GLDAS global)
/gpfsm/dnb32/smahanam/LIS/MMF-GroundWater/ldt_tests/ldt.config_noahmp401_gldas20_025d_hymap2.mmf

**Comment by smahanam** [comment]
> 

Hi @dmocko,

I understood and agreed.
Just wondering, do we also need to put a protection in Noah_parmsMod.F90 to ensure LDT does not enter the MMF block unless the land surface model version is:
if  (LDT_rc%lsm == "Noah-MP.4.0.1")

**Comment by dmocko** [comment]
Hi @smahanam 

Yes - please put this protection into Noah_parmsMod.F90.

For the flag that I am suggesting for the ldt.config file, you can add this bit of code to the `call ESMF_ConfigGetAttribute` for this config entry:  `,default=.false.`

One other request, can you please add documentation for all of these config entries into LISF/ldt/configs/ldt.config.adoc file?

**Comment by smahanam** [comment]
> One other request, can you please add documentation for all of these config entries into LISF/ldt/configs/ldt.config.adoc file?

Hi @dmocko, 
LISF/ldt/configs/ldt.config.adoc
Is line 2378 a good place for new entries?

**Comment by smahanam** [comment]
@dmocko, @bmcandr,

Okay ! I have addressed David's comment that we should LDT to Noah-MP-4.0.1.
Also, added those parameters descriptions to ldt.config.adoc

I will put together a testcase later (on Monday). David, I will need your help to write Grads descriptors, I guess it is not a time consuming thing.

**Comment by bmcandr** [comment]
@smahanam, thanks! Don't worry about the GrADs descriptor files. I have a script that writes them given a LIS NetCDF output file.

**Comment by smahanam** [comment]
I created a test case, this covers only the LDT updates presented in this PR.
/discover/nobackup/smahanam/mmfldttest.tar.gz

I reran LDT updates from the unpacked directory after gunzip and tar -xvf the above file. I confirm this mmfldttest.tar.gz is self-contained and able to reproduce the MMF updates.

**Comment by dmocko** [comment]
Thanks @smahanam !

I will try this test case - but @bmcandr , can you also do so with your array of tests?

Since this is a feature (not a bug fix), I believe we should do the full regression testing as well.

I will comment again on this PR once I've finished my test case and reviewed all changes again.
Please don't accept this PR until I also give my approval.

**Comment by bmcandr** [comment]
@dmocko, yes I was also thinking we should run our regression tests given the substantial changes to `ldt/params/Noah/Noah_parmsMod.F90`. I will kick off the test suite before signing off today.

I'm currently editing the config file, but will wait to push the changes until just before merging in case you decide to push any changes in the meantime.

**Comment by dmocko** [comment]
I was able to replicate the testcase - thanks!

After a full review, some additional changes are needed:

1. In ldt/configs/ldt.config.adoc, right after the example _ldt.config_ entry:
`Process Noah-MP-4.0.1 MMF groundwater parameters: .true.`
   Please add the following text:

If this config entry is not present, then it is assumed to be `.false.`, and the Noah-MP-4.0.1 MMF groundwater parameters will not be processed.  Note that these parameters are only needed when running option "5" for the following lis.config entry when running LIS:
`Noah-MP.4.0.1 runoff and groundwater option:  5`
Finally, note that this MMF groundwater option (option 5) is not yet supported in LIS, although the LIS team is nearing completion of its implementation.

2. For all other example _ldt.config_ entries, please give a description of what the config entry represents (similar to how you explain the config entry described in item "1" above).  You can use (and then remove) the descriptions from the examples after the "#" (e.g., "# Number of #pixels to search for neighbor").  When done, the examples won't have any "#" and text after the config value.

3. Speaking of the number of pixels, can you please clarify that the number of pixels searched is within the source groundwater parameter data? And provide the grid spacing of this source data?  I ask because LDT typically does a "fill radius" to fill other parameters, which is the number of LDT domain grid points.  So, users should be aware that the MMF parameter "fill radius" values will need to be much larger, and could vary based on their LDT grid spacing.

4. Please also list config entries for all of the "water value" MMF parameters in ldt.config.adoc.  You should also indicate the default values that will be used if these config entries are not in the ldt.config file.

5. Turning from ldt.config.adoc to the code, it would be great if some more details were dumped into the `Mask-parameter fill diagnostic file:`.  Can you add code similar to this: https://github.com/smahanam/LISF-1/blob/feature/LDT_mmf-groundwater/ldt/params/Noah/Noah_parmsMod.F90#L429-L432
...before each of the five calls starting on this line?
https://github.com/smahanam/LISF-1/blob/feature/LDT_mmf-groundwater/ldt/params/Noah/Noah_parmsMod.F90#L576
The fill details are already printed to the fill diagnostic file, but it would be helpful to have these labels for each section.
Also before each call, add a line similar to this, to print to the ldtlog file the directory path being read for that parameter:
`write(LDT_logunit,*) "Reading data from: ",trim(Noah_struc(n)%mmf_fdepth_dir)`

6. On this line: https://github.com/smahanam/LISF-1/blob/718a1e49d90115c4f06c8a9ab57606238e45e1fc/ldt/params/Noah/Noah_parmsMod.F90#L506 - please change the string in the call to LDT_verify to exactly match the 'MMF transmissivity dir:' label in the previous line.  If they are different, the user won't know the proper config entry to use.  And please add the same "call LDT_verify" for the other directories.  I tested a run with one of these config entries missing and the ldtlog file just gave:
` [ERR] mmf_init: load index failed. Stopping.          19`
The same undescriptive error message is given if one of the directory paths is incorrect, which is another reason why the log statement described in item "5" above will be helpful to the user.

7. The LIS team tries to avoid more than one FORTRAN line on a single line of each file, so you can please separate each line in the below sections into two separate lines?
https://github.com/smahanam/LISF-1/blob/feature/LDT_mmf-groundwater/ldt/params/Noah/Noah_parmsMod.F90#L517-L550
https://github.com/smahanam/LISF-1/blob/feature/LDT_mmf-groundwater/ldt/params/Noah/module_MMF_groundwater.F90#L103-L106
https://github.com/smahanam/LISF-1/blob/feature/LDT_mmf-groundwater/ldt/params/Noah/module_MMF_groundwater.F90#L470

Thanks, David

**Comment by smahanam** [comment]
Sure ! Shall do that.

**Comment by smahanam** [comment]
@dmocko I have addressed the code changes. 
(5) Turning from ldt.config.adoc to the code, it would be great if some more details were dumped into the ....

The modifications are actually in module_MMF_groundwater.F90

**Comment by bmcandr** [comment]
@dmocko, our LDT regression testcases run without issue and reproduce the target LIS parameter files.

**Comment by smahanam** [comment]
> @dmocko, our LDT regression testcases run without issue and reproduce the target LIS parameter files.

@bmcandr 
I guess you used the latest updates for the regression test.
https://github.com/NASA-LIS/LISF/pull/1038/commits/b49230e8dbb7a95e64595e56bf5ceb3d76c6a736

I am going to edit 
/ldt/configs/ldt.config.adoc now to address @dmocko's comments.

**Comment by bmcandr** [comment]
@smahanam, yes I tested with the latest changes you made to the LDT source code.

**Comment by dmocko** [comment]
@bmcandr - I looked at the changes to the code as they were committed, but would like to review again - and try my tests again with the latest codes.  Sorry for the delay, still catching up on things.  Will get to it soon.

**Comment by bmcandr** [comment]
No worries, @dmocko. Take your time.

**Comment by bmcandr** [comment]
@smahanam, I've cleaned up the MMF config documentation. This involved some reorganization so the MMF section is consistent with the rest of the document. You can view the result of my changes here: https://github.com/NASA-LIS/LISF/blob/d0909efab48c2bdb304ffd6e863b8d8a3b1377a9/ldt/configs/ldt.config.adoc

Let me know if anything looks incorrect.

**Comment by dmocko** [comment]
Thanks @smahanam and @bmcandr !

I have re-run the testcase and all my associated tests, and have reviewed the updated code and documentation.

All of my tests passed as they should, and the code and documentation looks great.

I only have just one remaining concern (previously mentioned) about the "fill radius" values for the MMF parameters. 
 Somewhere, the documentation should specify that these values are grid points in the source data - NOT grid points in the LDT grid, as most (all?) other fill radius values use grid points in the LDT grid.  Also, is there any guidance for changing these values based on the grid spacing of the LDT grid being processed?

Once some additional info is added to ldt.config.adoc about the MMF parameter "fill radius" values, this PR can be merged.

**Comment by smahanam** [comment]
> 

From a chat with David:
Sarith - just one more commit to change the documentation in ldt.config.adoc from "1200" to "3" - and then the PR is ready to merged.

**Comment by smahanam** [comment]
Hi David,

I changed radius to 3. and checked in.

**Comment by dmocko** [comment]
Thanks @smahanam !

As discussed in today's meeting, @TimLahmers is going to do one more quick test.

I don't expect any issues, so once he also is satisfied, we get finally merge this in.

**Review by bmcandr — APPROVED** [review]

**Comment by bmcandr** [comment]
Hi @smahanam and @dmocko, thanks for working on this! Do we know if @TimLahmer's test succeeded?

**Comment by TimLahmers** [comment]
@bmcandr Which test are you referring to? For the LIS code, we have a beta-version of LIS-MMF that produces consistent results with HRLDAS-MMF. We still have a bug, where cold starting the model with MMF results in unrealistic water table depth fields. That bug has a temporary work-around for testing and running the model.

**Comment by bmcandr** [comment]
@TimLahmers, I was referring to David's last comment on 5/26:



> Thanks @smahanam !
> 
> As discussed in today's meeting, @TimLahmers is going to do one more quick test.
> 
> I don't expect any issues, so once he also is satisfied, we can finally merge this in.

**Comment by dmocko** [comment]
@TimLahmers - Tim, can you please test running LDT with the fill radius set to 3, instead of 0?  And then run LIS to see any differences.

**Comment by TimLahmers** [comment]
@bmcandr @dmocko I see the earlier comments now, and that test is to demonstrate that setting the Fill Radius values for the new MMF parameters to 3 yields realistic parameter. I ran those tests at the end of May. Increasing the fill radius from 0 to 3 did change the MMF parameter grids, and I think they look less realistic with the larger fill value. Do you want to proceed with the fill radius of 3 to be consistent with other parameters (I can run LIS-MMF to see if the groundwater fields at least look reasonable) or stay with 0?

**Comment by dmocko** [comment]
@TimLahmers Let's take this discussion offline.  Would you mind putting together some slides showing this effect?  You can share them offline with the MMF team, or show them at our meeting this week.

**Comment by TimLahmers** [comment]
@dmocko That sounds good. I will follow up with you offline with parameter plots and model results.

**Comment by bmcandr** [comment]
Hi @dmocko and @TimLahmers, any update on this?

**Comment by TimLahmers** [comment]
> Hi @dmocko and @TimLahmers, any update on this?

@bmcandr Thanks for following up! @dmocko and @smahanam did some more testing on LDT and found some errors that are causing conventional fill radius values (i.e. 3 instead of 0) to have no-data values and unrealistic output fields. We are still working through this issue to find a solution.

**Comment by bmcandr** [comment]
Thanks for the update @TimLahmers!

**Comment by emkemp** [comment]
Hi @dmocko @TimLahmers and @smahanam 

I dusted off this pull request for MMF groundwater preprocessing with LDT.  I ran @smahanam's test case /discover/nobackup/smahanam/mmfldttest.tar.gz with Intel 21 compilers.  I reproduce most of the LDT parameter file, but I see some differences in the MMF_EQWTD, MMF_FDEPTH, and MMF_RIVERBED fields.

Questions:
(1) @smahanam Can you please run your test again with the latest code and see if the results for those three fields changed?  Your test case tarball is dated from 14 Apr.
(2) @dmocko @TimLahmers Do you have any remaining concerns on your end with the present state of the code?  The discussion log indicates there were unsatisfactory results noted when changing the fill radius, but that was before @smahanam committed his latest changes.

**Comment by dmocko** [comment]
Hi @emkemp - thanks for trying this pull request.  The MMF team actually has a meeting at the top of the hour, which will include a discussion of this LDT pull request.

I believe that if @smahanam runs the testcase again with the latest code you won't see differences in those fields.

That said, we still have a concern with the RIVERBED parameter.  This parameter is the only one where the source data is _not_ continuous, so we are seeing some unrealistic fields with certain config settings.  We have reached out to the MMF developers and will try their suggestions to come up with a solution.  But more (likely minor) code changes on this PR are still probable before it should be merged.

**Comment by smahanam** [comment]
@emkemp We made some changes on June 24th and reran the testcase as part of the update as well. I just forgot to update tar-gzipped file.
 
/discover/nobackup/smahanam/mmfldttest.tar.gz
I just created the above file using the June 24th testcase run.

**Comment by emkemp** [comment]
Thanks @smahanam!  I ran your updated test case and reproduced the results.  I also recompiled with strict checks and did not encounter any runtime problems.

I will await further word on resolving the RIVERBED parameter that @dmocko mentioned above.

**Comment by emkemp** [comment]
*PING*

Hello @smahanam, @dmocko, and @TimLahmers:

Is there any news on resolving the RIVERBED parameter?  That seems to be the remaining sticking point for this pull request.

**Comment by dmocko** [comment]
_PONG_

Hi @emkemp - thanks for checking in.

The RIVERBED parameter is used in computing the river conductivity.  Further investigation by @TimLahmers has revealed that this calculation may not be applicable at fine spatial resolutions.  We are exploring in LIS a physically-based river conductivity solution only at river points.  This solution may require additional river channel parameters to be added to LDT.

An argument could be made that the RIVERBED implementation in LDT for this pull request is correct and ready-to-go (maybe with one additional tweak), and that the user should be aware of the above issue when running fine spatial resolutions until resolved in LIS.  We have our MMF internal meeting later this week, and will discuss and report back.

**Comment by emkemp** [comment]
Hi @dmocko:  Any update on resolving the RIVERBED parameter question?

**Comment by dmocko** [comment]
Yes - @smahanam will be making a commit or two to finalize this parameter, and then we can do one last review and, if it looks good, finally merge this PR.

**Comment by smahanam** [comment]
Hi @TimLahmers ,
You said "! I still need to reach out to Gonzalo to confirm that this RIVERBED configuration produces realistic output at 4-km resolution, so we might need to hold off on this for a couple more days"

So are we still waiting for Gonzalo's feedback?

**Comment by TimLahmers** [comment]
@smahanam I am sorry for the delay on this. Gonzalo has been slow to respond, so I will send him another reminder today. Thanks for bringing this up!

**Comment by smahanam** [comment]
I incorporated Tim's suggestion: RIVERBED will always <= HGT_M

**Comment by dmocko** [comment]
Many thanks to @smahanam for these latest changes.  They look great!

Based on our MMF group meeting this afternoon, @smahanam @TimLahmers and I agree that this PR is complete.

@smahanam - Can you please re-run and share the testcase?

@emkemp - If you are satisfied with the code after running the testcase, you can go ahead and merge this PR.

**Comment by smahanam** [comment]
As I have said before, Github does not notify me these comments. 
@dmocko I just saw your request to rerun the testcase.
 
 I reran the testcase:
 /gpfsm/dnb32/smahanam/mmfldttest/

**Comment by cmclaug2** [comment]
Hi @dmocko @emkemp @TimLahmers,

I ran @smahanam older testcase (generated on July 21) at /discover/nobackup/smahanam/mmfldttest.tar.gz using the Intel 21 compiler. I was able to reproduce the LDT parameter file, expect for _small_ differences in the MMF_RIVERBED field. 

I also ran @smahanam's latest test case (generated October 28th, 2022) at /discover/nobackup/smahanam/mmfldttest using the Intel 21 compiler. Again, I was able to reproduce the LDT parameter file, expect for _larger_ differences in the MMF_RIVERBED field.  If my understanding of the ongoing changes to the PR are correct, this difference is expected due to @smahanam's commit to ldt/params/Noah/Noah_parmsMod.F90 on October 11th.

I was also able to compile and run LDT with the Intel compiler with strict checks and with the gnu compiler. 

My interpretation of this conversation is that my successful tests (excluding differences in MMF_RIVERBED) grants approval for this PR.   **I would like to double check with @emkemp to see what he thinks.**

**Comment by TimLahmers** [comment]
@cmclaug2 Thanks for the updates, and those results are expected. The most recent code changes were updates to the MMF_RIVERBED scheme to ensure MMF_RIVERBED <= MMF_HGTM, and are consistent with guidance from Gonzalo Miguez-Macho on setting the parameters.

**Comment by dmocko** [comment]
Yes, thanks @cmclaug2 for testing.

However, I will check with @smahanam to see if he's run the testcase with the latest code.

I believe we are expecting the code to be merged to be identical for all parameters, including MMF_RIVERBED.

**Comment by dmocko** [comment]
One more thing @cmclaug2 - can you please share a figure showing the differences in MMF_RIVERBED between your test and the testcase?

**Comment by cmclaug2** [comment]
Hi @dmocko,

The following image depicts the target field for MMF_RIVERBED in the latest testcase (updated October 28nd):
target


The following image depicts the field for MMF_RIVERBED when I ran the October 28th testcase using the feature branch I checked out this morning:
Result

You can find these files in '/discover/nobackup/cmclaug2/github/PR_1038/work_smahanam/mmfldttest_intel'

**Comment by TimLahmers** [comment]
@dmocko @cmclaug2 The second image looks good! The first image looks like something we were trying earlier in the project, when we considered setting RIVERBED to an unphysical value outside of channels. The second image should be what users are able to derive with normal settings.

**Comment by smahanam** [comment]
My bad @dmocko @TimLahmers @cmclaug2 

I reran my testcase.

**Comment by cmclaug2** [comment]
Thank you for the update @smahanam!  @dmocko, I am now able to reproduce the results of the testcase.  

I would still like to check with @emkemp before confirming this code is ready to be merged.

**Comment by emkemp** [comment]
Good morning @cmclaug2 

Can you tar up and store the test case input and output in /discover/nobackup/projects/lis/PR_TESTCASES/1038?

Once that's done, we can merge the pull request.

**Comment by cmclaug2** [comment]
Hi @dmocko @smahanam,

I was able to reproduce the testcase and the proper documentation is included. This PR is ready to be accepted.  I will be making the changes Eric mentioned above in a separate PR.

**Pull request merged**
