### PR TITLE
Correct interpolation in GEFS reader

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

This resolves an issue where the GEFS reader could misinterpolate both the swdown and the lwdown fields using the budget_bilinear/conservative method.

This also fixes a bug in the temporal interpolation of swdown by initializing zdoy right before calling zterp.

### Reforecast2 type
plot_swdown1 8 before
plot_swdown1 8 after

### Operational type
plot_swdown_f_tavg 7 before
plot_swdown_f_tavg 7 after

### CODE REVIEW

**Comment by karsenau** [comment]
Hi @jvgeiger:

Thank you for checking these fields and making these corrections.   I have reviewed and agree with your updates made.

**Comment by jvgeiger** [comment]
Thanks @karsenau.

**Comment by jvgeiger** [comment]
I placed a copy here: /discover/nobackup/jvgeiger/for/eric/gefsreforecast2/

**Comment by emkemp** [comment]
Thanks @jvgeiger 

Code compiles and runs w/o issue, and I reproduced your results.  Running with strict checks revealed no errors.  Since @karsenau concurs, I will accept the PR.

**Pull request merged**
