### PR TITLE
Fix/410 ldtbuffer

### PR DESCRIPTION
**Pull request by karsenau**
Add new buffer area to LIS target domains in LIS when subsetting parameters and reinterpolating them to the new target grid. 

This new code was applied to remove a bug involved with curvilinear projections (e.g., Lambert conformal). 

Also, an outdated longitude ordering (from E->W) was discovered in some of the ipolates routines, which were corrected to allow longitudinal ordering to go from W->E, as LIS convention follows, fixing issues for projections, like latlon grids crossing the International Dateline.

Testcase was also setup and instructions provided.

### CODE REVIEW

**Comment by karsenau** [comment]
Latest commits include:

Run successfully a Lambert projected grid for an IDL crossing domain in LDT. Some minor modifications were found due to the updates needed to the interp/compute_grid_coord_latlon.F90 routine to account for crossing IDL and lower-left lon to be in 360.

LIS log message updated in calculate_dominant_sfctile subroutine to inform user that no surface type tile fractions exceeded the min. cutoff percentage for sfc type tiles.  This last commit also required an updated lis.config file committed to testcases/domains/latlon_idlcross/

**Comment by emkemp** [comment]
Tested code with both Intel and GNU compilers, and found no problems.  Results match those from the testcase.

Recommend following code improvements before accepting this pull request:

* In ldt/interp/compute_earth_coord.F90:  Replace print* with write(LDT_logunit,*).  Replace stop with call LDT_endrun()
* In ldt/interp/comput_earth_coord_latlon.F90:  Move the rlon1 < 0 if block outside/before the do loop.  No sense in checking this over and over.
* In ldt/interp/compute_grid_coord.F90:  Replace print* with write(LDT_logunit,*).  Replace stop with call LDT_endrun().
* In ldt/params/landcover/read_MODISNative_lc.F90:  Most of the changes in this file are commented-out test code.  Can this be removed?
* In ldt/core/LDT_SurfaceTypeMod.F90:  Change write(*,*) to write(LDT_logunit,*).

**Comment by emkemp** [comment]
Last bullet should read "In ldt/core/LDT_SurfaceTypeMode.F90:  Change write(*,*) to write(LDT_logunit,*).

**Comment by karsenau** [comment]
Thanks for the recommendations. I made the updates to the LDT code and pushed the commit over to this pull request.

**Comment by emkemp** [comment]
Hi Kristi:

I tested your latest changes, and everything still works.

I want to confer with Jim on Thursday about your testcase before merging the code in.  Stay tuned.

**Comment by karsenau** [comment]
Ok, sounds good.
Thank you for the thorough testing, and please let me know if you all have any questions for me.

**Comment by emkemp** [comment]
I talked to Jim, and he gave me the go-ahead to merge in.  I will keep the AddToTestSuite label on this pull request, and Jim will review the requests later and add to his test suite as time permits.

**Pull request merged**
