### PR TITLE
Feature/modislaireader

### PR DESCRIPTION
**Pull request by KathyNie**
Hi Jim and Brendan,

Could you please review this new feature for LDT, which is to read in the latest v006 of MODIS MCD15A2H LAI product. I tried to create this pull request and see whether it works. I will send you a directory of the corresponding testcase on discover via email later on. Thanks a lot for your help!

Best,
Wanshu

### CODE REVIEW

**Comment by dmocko** [comment]
Hi @KathyNie - please add the appropriate documentation for the LDT Users' Guide for this new feature into the ldt.config.adoc file as well.  Thanks!

David

**Comment by KathyNie** [comment]
> Hi @KathyNie - please add the appropriate documentation for the LDT Users' Guide for this new feature into the ldt.config.adoc file as well. Thanks!
> 
> David

Ah, thanks David for the reminder. Will do!

**Review by bmcandr — APPROVED** [review]
Hi @KathyNie,

The code and documentation looks good. I compared against the GLASSlai reader which I assume was used as a template.

Using your testcase I was able to produce identical output across the board:

- [x] SLES 11/GNU 4
- [x] SLES 11/Intel 18
- [x] SLES 12/Intel 19

I will go ahead and merge. Thanks and congrats on your first pull request!

**Comment by KathyNie** [comment]
> Hi @KathyNie,
> 
> The code and documentation looks good. I compared against the GLASSlai reader which I assume was used as a template.
> 
> Using your testcase I was able to produce identical output across the board:
> 
> * [x]  SLES 11/GNU 4
> * [x]  SLES 11/Intel 18
> * [x]  SLES 12/Intel 19
> 
> I will go ahead and merge. Thanks and congrats on your first pull request!

Thank you a lot Brendan!

**Pull request merged**
