### PR TITLE
Add testcase for SMAP soil moisture da

### PR DESCRIPTION
**Pull request by jvgeiger**
See PR #416.

### CODE REVIEW

**Review by bmcandr — APPROVED** [review]
I ran the testcase steps using the tar files added to the test suite directory and the target output was reproduced successfully. ✔️ 

I will go ahead and merge.

**Comment by LIS-navari** [comment]
Hi Brendan,

The test case is not related to SMAP soil moisture data assimilation (DA). This is a test case for the SMAP SM reader in LVT.

Best
Mahdi

**Comment by bmcandr** [comment]
Hi @LIS-navari,

Sorry, I'm a little confused. Are you commenting on the title of this pull request describing the testcase as SMAP sm DA? The README associated with the LVT testcase added in this PR *does* describe it as a SMAP SM reader testcase.

**Comment by LIS-navari** [comment]
Hi Brendan,

The title is not correct.
The test case just read the MSAP L3 SM data.
We have updated the SMAP readers (for LIS, LDT, LVT) to read the MSAP L3 data with the latest release number.
Please see #416 and  #196.

Thanks
Mahdi

**Comment by bmcandr** [comment]
@LIS-navari, gotcha. While the LVT testcase uses the "Data intercomparison" mode to test the SMAP reader, the LDT and LIS testcases added here test the SMAP reader by way of DA, correct? @jvgeiger can confirm/deny as the author of this PR, but I believe that may be the source of the reference to DA in the title.

**Pull request merged**
