### PR TITLE
Adds support for MCD12Q1 landcover

### PR DESCRIPTION
**Pull request by sahmad3**
### Description

Added support for reading MODIS IGBP landcover (MCD12Q1) within LDT that can now use annual landcover datasets

### Testcase
/discover/nobackup/projects/eis_freshwater/sahmad3/LIS_AMAZON/LDT_LCchange_TESTCASE

### CODE REVIEW

**Comment by emkemp** [comment]
Good morning @sahmad3 

Can you provide a test case for this new capability?

**Comment by sahmad3** [comment]
@emkemp sorry it took a bit long, here's the test case for this capability: /discover/nobackup/projects/eis_freshwater/sahmad3/LIS_AMAZON/LDT_LCchange_TESTCASE

**Comment by emkemp** [comment]
Hi @sahmad3 

I don't see any output in the testcase directory, just input.  Can you please rerun your test case and add the lis_input.*.nc file so we can compare?

**Comment by emkemp** [comment]
*PING*

Hi @sahmad3

I don't see any output in the testcase directory, just input. Can you please rerun your test case and add the lis_input.*.nc file so we can compare?

**Comment by sahmad3** [comment]
Hi @emkemp 
Apologies! Due to some reason, I kept missing these messages. I just ran the test case and added the lis_input* there (/discover/nobackup/projects/eis_freshwater/sahmad3/LIS_AMAZON/LDT_LCchange_TESTCASE). 

Please let me know if any other file is needed for comparison.

**Comment by cmclaug2** [comment]
Hi @sahmad3 

I have compiled your code with the intel compiler and have run your testcase.  Can you give me permission to access `/discover/nobackup/projects/eis_freshwater/sahmad3/LIS_AMAZON/LDT_LCchange_TESTCASE/lis_input_AmazonExtn_2001.nc` so I can compare our output? 

Assuming I can replicate your output, before merging, there are three other things that will need to be taken care of:
1. I receive an error when I compile your code with the gnu compiler.   I will message you off github so we can find a time to take a look. 
2.  Documentation in ldt.config.adoc needs to be updated to reflect the new `Landcover data source:` parameter, MCD12Q1.
3.  The minor conflict in LDT_param_pluginMod.F90 will need to be resolved.  I need to consult with Jim on how best to handle that.     
 
Thanks!

**Comment by sahmad3** [comment]
Hi @cmclaug2 

I opened the permission to the lis_input.  Let me know if you want me to update the documentation with this change.

Thanks for your help!

**Comment by cmclaug2** [comment]
Hi @sahmad3,

Thank you!  I confirm I was able to replicate your lis_input*.nc file. 

Yes, can you please update the documentation to reflect the new support for MCD12Q1?

**Comment by sahmad3** [comment]
Hi @cmclaug2,

I added the MCD12Q1 landcover option to the doc. Because the .adoc file in my previous commit was outdated, I pulled the latest file and made changes there. Let me know if you see any issues there that need my attention.

Thanks!

**Comment by cmclaug2** [comment]
This code compiles with intel and gnu compilers.  I am able to reproduce the testcase with the intel compiler.  I am able to nearly reproduce the testcase with the gnu compiler (with minor differences due to floating point calculations).

I accept this pull request.

**Comment by sahmad3** [comment]
Thanks @cmclaug2 for all your help!

**Pull request merged**
