### PR TITLE
Add Irrigation to Noah-MP 4.0.1

### LINKED ISSUE #178: Add Irrigation Routines to Noah-MP 4.0.1
Add Noah-MP 3.6 irrigation interfaces (with groundwater) to Noah-MP 4.0.1

### PR DESCRIPTION
**Pull request by jerlingi**
This pull requests adds the irrigation routines currently in Noah-MP 3.6 to Noah-MP 4.0.1.

A test case is located in /discover/nobackup/projects/wldas/share/noahmp401_irrigation_testcase

Resolves #178

### CODE REVIEW

**Comment by bmcandr** [comment]
Hi Jessica,

The code looks good aside from a few commented lines that can be removed. Please take a look at lines 22, 25, 76, 224-225, 263, 272, 305-307, 400, 410-412, 434 in `lis/surfacemodels/land/noahmp.4.0.1/irrigation/noahmp401_getirrigationstates.F90`.

There is also a small conflict in `lis/make/default.cfg` that you'll need to resolve. It should be pretty straightforward to [fix in the web editor](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github).

Once those changes are commited, I can get to testing. Thanks!

**Comment by bmcandr** [comment]
Hi Jessica,

Since I only requested changes that should not alter the way your code runs, I’ve been trying to test test this code. I’ve encountered issues running LIS that stem from files specified in `lis.config` that seem to be missing.

The first missing file encountered was `./forcing_variables.txt`. As a temporary workaround, I grabbed a forcing variables list file from Step 2 of the LIS test cases. LIS then halted with a new error:

```sh
****** Error ******************************************************
Cannot find file MPTABLE.TBL
STOP
*******************************************************************
STOP in Noah-MP read_mp_veg_parameters
```

This probably occurred because LIS is looking for the following file specified in `lis.config`:

```sh
Noah-MP.4.0.1 MP parameter table:            ./input/LS_PARAMETERS/noahmp401_parms/MPTABLE_UMD.TBL
```

The `noahmp401_parms/` directory does not exist in the input data provided in `noahmp401irrigtest_input_v72.tar.gz`. There *is* a `noahmp_params/` directory, but it only contained `GENPARM.TBL` and `VEGPARM.TBL `. To troubleshoot I copied `noahmp_params/` to `noahmp401_parms/` and added `SOILPARM.TBL` and `MPTABLE_UMD.TBL` from the [LIS data portal](https://portal.nccs.nasa.gov/lisdata_pub/data/PARAMETERS/noahmp_params/) as suggested in [this ModlingGuru thread](https://modelingguru.nasa.gov/message/9672#9672). Unfortunately, that throws a new error:

```sh
forrtl: severe (24): end-of-file during read, unit 15, file <path to>./input/LS_PARAMETERS/noahmp401_parms/MPTABLE_UMD.TBL, line 412, position 0
Image              PC                Routine            Line        Source
LIS.intel18        000000000141F69E  Unknown               Unknown  Unknown
LIS.intel18        000000000145976C  Unknown               Unknown  Unknown
LIS.intel18        0000000000E442AB  noahmp_tables_401        9455  module_sf_noahmplsm_401.F90
LIS.intel18        00000000007482FD  noahmp401_setup_          223  NoahMP401_setup.F90
LIS.intel18        00000000005FF78F  lis_lsmmod_mp_lis         475  LIS_lsmMod.F90
LIS.intel18        0000000000688E25  lis_surfacemodelm         159  LIS_surfaceModelMod.F90
LIS.intel18        00000000011FA8F6  retrospective_run          93  retrospective_runMod.F90
LIS.intel18        0000000000CA4C26  MAIN__                     65  lisdrv.F90
LIS.intel18        000000000041353E  Unknown               Unknown  Unknown
libc-2.11.3.so     00002AAAB41A3C36  __libc_start_main     Unknown  Unknown
LIS.intel18        00000000004133E9  Unknown               Unknown  Unknown
```

At this point I'm stuck and am curious to hear your thoughts :).  Have you encountered anything like this during your testing? I have a call with @jvgeiger and @emkemp this afternoon and I will ask them about this as well.

Apologies for the wall of text!
-B

**Comment by karsenau** [comment]
Hi Andrew,

I wouldn't copy those NoahMP files over for version 4.0.1.  The NoahMP4.0.1 are found on our lis data disk in the directory:

./lisdata/LS_PARAMETERS/noahmp401_parms/

That is the directory and tables that you will need for a successful run.

Please let me or Jessica know if you have any more questions. Thanks!

**Comment by bmcandr** [comment]
@karsenau aha! Thank you. That seems to be working as the run hasn't halted yet.

**Comment by karsenau** [comment]
Ok, great!

I believe Jessica provided sample output to compare your run against?

**Comment by bmcandr** [comment]
She did indeed! I'll report back with the results when the run finishes.

**Comment by bmcandr** [comment]
Hi @jerlingi @karsenau!

I've finished examining the output of a run of LIS compiled on Intel18. I'm seeing some small differences between my output and the target output provided in the testcase files and I want to check whether these differences are acceptable. I've attached some example output from these comparisons for you to look at:
* [SURFMOD_LIS_HIST_201105020000_CMP_t1.txt](https://github.com/NASA-LIS/LISF/files/4635225/SURFMOD_LIS_HIST_201105020000_CMP_t1.txt) : output of `nccmp -dmsf -t1`

* [SURFMOD_LIS_HIST_201105020000_NCCMP_STATS.txt](https://github.com/NASA-LIS/LISF/files/4635230/SURFMOD_LIS_HIST_201105020000_NCCMP_STATS.txt) : output of `nccmp -dfqS`

The differences are generally very small, but I am also seeing some larger differences that a web search suggests might be missing data/nodata values (e.g., +/-9.99999987e+14):

`DIFFER : VARIABLE : Swnet_tavg : ATTRIBUTE : vmin : VALUES : -9.99999987e+14 <> 0`

I'm also seeing this value pop up in the `IRRIGATION/` output comparisons.

If you would like to take a look for yourself, I'm working in `$NOBACKUP/bmcandr1/PR_testing/516/testing` and my output is in `OUTPUT.intel18`.

**Comment by karsenau** [comment]
Thanks, Brendan, for sharing these latest comparison results.

Since Jessica generated the testcase output, I'll let her make the final comment.  But the differences seem small enough (e.g., due to compiler flag options or processor number) and maybe related to mask differences, that I think it may be ok.  How many points had differences?  Also, were you provided the input ldt file?

**Comment by bmcandr** [comment]
@karsenau yes, the LDT input file was provided and the output generated by LDT was identical to the target so everything looks good there.

**Comment by jerlingi** [comment]
These differences look pretty small. My LIS output was generated using the Intel 19 modulefile, so if you want to try running it with that, these differences might be resolved.

**Comment by bmcandr** [comment]
Thanks for taking a look, @jerlingi. I figured these differences weren't problematic, but wanted to check with you to be sure. Per your suggestion I tested on Intel 19  and the output is identical so everything looks good! I think we're ready to merge, but before I can do that you'll have to resolve the minor conflict indicated above.

**Comment by jerlingi** [comment]
Thanks for confirming that a compiler issue was the culprit, @bmcandr! I'll make the other changes.

**Comment by bmcandr** [comment]
Yes, the other changes too! I got ahead of myself in the last comment :)

**Comment by jerlingi** [comment]
Hi @bmcandr ,

I cleaned up lis/surfacemodels/land/noahmp.4.0.1/irrigation/noahmp401_getirrigationstates.F90 on sections I worked on. I have not worked on the flood irrigation portion so maybe @karsenau can comment about removing some of those lines.

I can't quite figure out how to result the conflict in default.cfg in the editor (and Github still flags a conflict when I commit the changes) but it should read (my changes bolded)

[NoahMP.4.0.1]
enabled: True
macro: SM_NOAHMP_4_0_1
path: surfacemodels/land/noahmp.4.0.1,
      surfacemodels/land/noahmp.4.0.1/phys
dependent_comps: virtual_da,
                 virtual_da_obs_snodep,
                 virtual_da_obs_usafsi,
                 virtual_optue,
                 virtual_routing,
                 **virtual_irrigation**
virtual_da path: surfacemodels/land/noahmp.4.0.1/da_soilm,
                 surfacemodels/land/noahmp.4.0.1/da_snow
virtual_optue path: surfacemodels/land/noahmp.4.0.1/pe,
            surfacemodels/land/noahmp.4.0.1/pe/obspred/UAsnow
virtual_routing path: surfacemodels/land/noahmp.4.0.1/routing
virtual_da_obs_snodep path: surfacemodels/land/noahmp.4.0.1/da_snodep
virtual_da_obs_usafsi path: surfacemodels/land/noahmp.4.0.1/da_usafsi
**virtual_irrigation path: surfacemodels/land/noahmp.4.0.1/irrigation**

**Comment by karsenau** [comment]
Hi @bmcandr @jerlingi ,
Thanks for these updates.

As per the commented out lines in the "flood" irrigation code, lines 400, 410-412, I would recommend leaving those as for now as that code will be evaluated soon for another project.  Updates may be coming for those entries. At that time, the commented out code may be able to be removed then.

As for the conflict for the make/default.cfg file, it looks like @jerlingi version has turned off some default "true" settings for some options -- see:
https://github.com/NASA-LIS/LISF/pull/516/commits/75ebca82018efaf95f08f337a1fc6e9939fa3c08

The ones highlighted in red should be turned back to the lines highlighted in green to remove conflicts with master, I believe.

**Comment by bmcandr** [comment]
Hi @jerlingi @karsenau, thanks for the explanation re: the suggested changes. Sounds good to me.

Re: the conflict
@jerlingi it looks like your local feature branch may not be up to date with the master so your local git thinks there is more conflict than there really is. For example, `git diff` between your latest commit and upstream/master shows that the `[PE OBS UAsnow]` section as "missing", but this is because it was only just added on 5/14 in #517.

You should be able to quickly resolve the conflict with the web editor by clicking "Resolve Conflicts" above and deleting lines 1143 and 1147-1150, then clicking the "mark as resolved" button in the top right of the editor. This will create a new commit with the changes that should resolve the conflict while preserving the latest version of `default.cfg` (i.e., the changes from #517 will be preserved).
```
<<<<<<< feature/noahmp401_irrig2                 # delete
                 virtual_optue,
                 virtual_routing,
                 virtual_irrigation
=======                                          # delete
		 virtual_optue,                  # delete
                 virtual_routing                 # delete
>>>>>>> master                                   # delete
```

The [NoahMP.4.0.1] section should then match your comment above:
```
[NoahMP.4.0.1]
enabled: True
macro: SM_NOAHMP_4_0_1
path: surfacemodels/land/noahmp.4.0.1,
      surfacemodels/land/noahmp.4.0.1/phys
dependent_comps: virtual_da,
                 virtual_da_obs_snodep,
                 virtual_da_obs_usafsi,
                 virtual_optue,
                 virtual_routing,
                 virtual_irrigation
virtual_da path: surfacemodels/land/noahmp.4.0.1/da_soilm,
                 surfacemodels/land/noahmp.4.0.1/da_snow
virtual_optue path: surfacemodels/land/noahmp.4.0.1/pe,
            surfacemodels/land/noahmp.4.0.1/pe/obspred/UAsnow
virtual_routing path: surfacemodels/land/noahmp.4.0.1/routing
virtual_da_obs_snodep path: surfacemodels/land/noahmp.4.0.1/da_snodep
virtual_da_obs_usafsi path: surfacemodels/land/noahmp.4.0.1/da_usafsi
virtual_irrigation path: surfacemodels/land/noahmp.4.0.1/irrigation
```

I hope that was clear! Let me know if you have any questions.

**Comment by jerlingi** [comment]
I think it should be fixed now! I didn't push "commit merge" when I tried to do it in the editor last night, and I think that was the problem.

**Comment by bmcandr** [comment]
Aha! That makes sense. Thanks for your help throughout this PR. The code looks good and I'm able to reproduce the target output so I will go ahead and merge.

**Pull request merged**
