### PR TITLE
The SMAP reader was modified to read the SMAP L3 file with the latest Release number and largest CRID Version Number

### PR DESCRIPTION
**Pull request by LIS-navari**
We had to redo this pull request.  Please see #196 for the full history of this pull request.

Test case for LVT SMAP reader is available at
/discover/nobackup/mnavari/my_projects/op/test_new_smap_reader4lvt

Test case for soil moisture DA using new reader is available at /discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader

Test case for LDT:
/discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader_ldt

### CODE REVIEW

**Comment by jvgeiger** [comment]
I am reviewing and testing.

**Comment by jvgeiger** [comment]
Running LIS in parallel yields different results than running serially.  In particular, LIS (running in parallel) does not produce LISDAOBS_201603251300.a01.d01.1gs4r, LIS_DA_EnKF_201603251300_incr.a01.d01.nc, nor LIS_DA_EnKF_201603251300_innov.a01.d01.nc files.

I am investigating.

**Comment by LIS-navari** [comment]
Hi Jim,

I have submitted to parallel jobs for before and after changes.
I’ll let you know if my results were different.

Thanks
Mahdi

**Comment by LIS-navari** [comment]
Hi Jim,

My results from parallel simulations are the same.

Out put

/discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader/

drwxrwxr-x 6 mnavari s1458      512 Dec  2 15:13 SMAPDA_OUTPUT.af.parallel

drwxrwxr-x 6 mnavari s1458      512 Dec  2 15:13 SMAPDA_OUTPUT.bf.parallel



evaluation

/discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader/eval_reader_parallel/

Thanks
Mahdi

**Comment by jvgeiger** [comment]
I have made some additional updates to this commit.  Everything tests ok for me.

@LIS-navari , would you please review my updates?

**Comment by LIS-navari** [comment]
@jvgeiger 
1- The LVT SMAP reader for soil moisture was tested and I got identical results.
test case available at 
/discover/nobackup/mnavari/my_projects/op/test_new_smap_reader4lvt/ars_final_test

2- A soil moisture DA test case was performed using the updated SMAP reader and results were identical. 
test case available at /discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader

3- I **was not able** to generate identical results for LDT 
discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader_ldt

4- SMAP reader for LISF/lvt/datastreams/SMAPvwc/ and LISF/lvt/datastreams/SMAP_L3TB/ have not been updated.

**Comment by jvgeiger** [comment]
Mahdi and I were able to reproduce the LDT results.

"4- SMAP reader for LISF/lvt/datastreams/SMAPvwc/ and LISF/lvt/datastreams/SMAP_L3TB/ have not been updated." will be addressed in a separate issue.

**Pull request merged**
