### PR TITLE
Updates the GEFS forcing plugin

### LINKED ISSUE #698: Update the GEFS forcing plugin to support the operational data stream

### PR DESCRIPTION
**Pull request by sujayvkumar**
Updates the GEFS forcing plugin to support the new operational data streams

Resolves #698

### CODE REVIEW

**Comment by sujayvkumar** [comment]
A sample testcase is at : /discover/nobackup/svkumar/LISF_testing/698

**Comment by bmcandr** [comment]
Hi @sujayvkumar, I'm hitting an undefined reference error while compiling:

```sh
ld: get_gefs.o: in function `get_gefs_':
get_gefs.F90:(.text+0x14d6): undefined reference to `read_gefs_operational_'
ld: get_gefs.F90:(.text+0x1d3d): undefined reference to `read_gefs_operational_'
```

Is there a _read_gefs_operational.F90_ that goes with these changes?

**Comment by sujayvkumar** [comment]
> Hi @sujayvkumar, I'm hitting an undefined reference error while compiling:
> 
> ```shell
> ld: get_gefs.o: in function `get_gefs_':
> get_gefs.F90:(.text+0x14d6): undefined reference to `read_gefs_operational_'
> ld: get_gefs.F90:(.text+0x1d3d): undefined reference to `read_gefs_operational_'
> ```
> 
> Is there a _read_gefs_operational.F90_ that goes with these changes?

Just added the missing file.

**Comment by bmcandr** [comment]
Hi @sujayvkumar,

Testing produced identical results on Intel 18 and "close enough" results on Intel 19 and GNU4. For the latter cases, the differences I'm seeing are:

```sh
LIS_HIST_202101290600.d01.nc
DIFFER : VARIABLE : Qle_tavg : POSITION : [0,0] : VALUES : 0.216147 <> 0.216145
LIS_HIST_202101290300.d01.nc
DIFFER : VARIABLE : Qle_tavg : POSITION : [0,0] : VALUES : 0.19659 <> 0.196587
LIS_HIST_202101290900.d01.nc
DIFFER : VARIABLE : Qle_tavg : POSITION : [0,0] : VALUES : 0.453968 <> 0.453966
LIS_HIST_202101291200.d01.nc
DIFFER : VARIABLE : Qle_tavg : POSITION : [0,0] : VALUES : 0.571844 <> 0.571845
LIS_HIST_202101291500.d01.nc
DIFFER : VARIABLE : Qle_tavg : POSITION : [0,0] : VALUES : 1.90961 <> 1.90961
LIS_HIST_202101291800.d01.nc
DIFFER : VARIABLE : Qle_tavg : POSITION : [0,1] : VALUES : 45.7783 <> 45.7783
LIS_HIST_202101292100.d01.nc
DIFFER : VARIABLE : Qle_tavg : POSITION : [0,0] : VALUES : 62.0969 <> 62.0968
LIS_HIST_202101300000.d01.nc
DIFFER : VARIABLE : Qle_tavg : POSITION : [0,0] : VALUES : 121.344 <> 121.344
LIS_RST_NOAHMP401_202101300000.d01.nc
DIFFER : VARIABLE : SFCRUNOFF : POSITION : [0] : VALUES : 0.615604 <> 0.615604
```

Should the `GEFS forecast type:` option in the LIS Users Guide be updated? It says only "Reforecast2" is supported at the moment. Let me know and I can update it.

**Comment by sujayvkumar** [comment]
Thanks. I guess these differences are small enough to ignore. 

Yes, the GEFS forecast type: option in LIS users guide should be updated.

**Comment by karsenau** [comment]
Thanks Sujay and Brendan.

If you can add the operational option and retain the "Reforecast2" option in the LIS User's Guide, that would be great.  The "Reforecast2" option can still be supported; just a newer version is presently coming out. Thanks!

**Comment by bmcandr** [comment]
I realized I was running `nccmp -d` so it was stopping after the first difference found. There are more differences than those listed in my comment above. The LIS_HIST differences are mostly small, but the restart files differ quite a bit in some places. Both are probably worth a second opinion before merging. The test and target output is available for comparison in the OUTPUT-* directories here:

/discover/nobackup/projects/lis/PR_TESTCASES/699/testing

Let me know what you think.

**Comment by bmcandr** [comment]
Ok sounds good.

**Pull request merged**
