### PR TITLE
Fix HYMAP2 2-way coupling in parallel mode

### PR DESCRIPTION
**Pull request by dpsarmie**
HYMAP2 2-way coupling was not working properly when run in
parallel. This fix adds dummy subroutines to the land-surface
models which allow the 2-way coupling options to work properly.
A more robust fix might be added in the future.

Resolves: #605

### CODE REVIEW

**Comment by dpsarmie** [comment]
Testcase files are here: /gpfsm/dnb02/projects/p63/dpsarmie/testcase_HYMAP

Let me know if you run into any issues.

**Review by bmcandr — CHANGES_REQUESTED** [review]
Hi @dpsarmie,

I'm waiting for test runs to move out of the queue. For the time being, I will request just one change:

* In `lis/surfacemodels/land/noahmp.4.0.1/routing/noahmp401_getsws_hymap2.F90`:
    * **Lines 48, 49**: change calls to `print` and `stop` to `write(LIS_logunit,*)` and `LIS_endrun()` as in the other `get_sws` files.

Thanks!

**Comment by bmcandr** [comment]
Hi @dpsarmie,

My initial test run failed when attempting to write output for the first day, but there were no informative error messages in the log or stack trace. I looked at the target output you supplied and noticed the `SURFACEMODEL/201010` folder contains a binary file for the first day (10/27) alongside netcdf output for the full run. The supplied `lis.config` file specified binary output so I changed it to netcdf to test again. This second test run has proceeded past the break point of the first run.

Did you encounter issues writing binary output in your testing?

**Comment by dpsarmie** [comment]
I did not encounter any issues when writing in binary for the SURFACEMODEL output. There is no binary option for ROUTING so those files should be Netcdf format only. I can try running it again later today to see if I have any issues writing binary files. I'll also add the needed changes once your testing is completed.

**Comment by bmcandr** [comment]
Hi @dpsarmie,

It turns out that I missed the error message indicating that binary output is not supported for HYMAP2 as it only appeared in some of the log files. My apologies.

I am seeing small differences between my netcdf output and the targets. Note the banding around 33N and gird-like artifacts in the top left:

riverdepth_inst_diff_20011101
riverstor_inst_diff_20011101

Any idea what the source of these differences might be? For reference, I'm testing on SLES12 and compiled with netcdf compression disabled.

**Comment by dpsarmie** [comment]
Hey @bmcandr,
I haven't come across that issue. I'll circle back to this once I get some other things off my plate but I was also on SLES12 but I was using the lisf_7_intel_19_1_0_166 **without** the traceback fix (I should upgrade to 19_1_3_304). That might be an issue assuming you were using the latest version of compiler and libraries. I also used all default LIS configuration options (so Netcdf compression enabled).

**Comment by dmocko** [comment]
Hi @dpsarmie,

Do you think you will be able work on resolving this soon, so we can get it merged?

Without these additions, for example, Noah-MP-4.0.1 can't run the HYMAP2 router in either single-processor or parallel mode.

Also, can you please add lis.config.adoc documentation into the LIS Users' Guide for these two new entries?:

HYMAP2 enable 2-way coupling:
HYMAP2 2-way coupling flooded fraction threshold:

Thanks,

David

**Comment by dpsarmie** [comment]
@dmocko : I'll add those config options to the lis.config file. The current issue is the small differences in the output. I think the next test is to see if there is an issue with compiler versions or something similar.

@bmcandr : I can run a version of the fix if you'd like. Which version of the Intel compiler did you use and you had both the deflate and the shuffle filters set to 0?

**Comment by bmcandr** [comment]
Hi @dpsarmie,

I'll re-run from scratch on my end as well. Let's use the 19_1_3_304 module file, debug optimization, and both deflate + shuffle set to 0.

**Comment by dpsarmie** [comment]
Hey @bmcandr ,
Output for my run is here: /discover/nobackup/dpsarmie/work/gitLIS/HYMAP2_2wayCoupleFix/lis/OUTPUT
If it checks out, I'll add the last bits and update the commit.

**Comment by bmcandr** [comment]
Thanks @dpsarmie! I'm still seeing differences between the routing output files, but they're very small. Here's the output of `nccmp -t 0.1`, for example (files not listed were identical at this threshold):

```sh
TARGET_OUTPUT/ROUTING/200110/LIS_HIST_200110310000.d01.nc
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1028,552] : VALUES : 1847.7 <> 1847.86 : PERCENT : 0.0090965
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1029,553] : VALUES : 543.989 <> 543.817 : PERCENT : 0.0316402
TARGET_OUTPUT/ROUTING/200111/LIS_HIST_200111010000.d01.nc
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1028,552] : VALUES : 2765.03 <> 2765.19 : PERCENT : 0.00588898
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1029,553] : VALUES : 1402.08 <> 1401.92 : PERCENT : 0.011031
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1029,554] : VALUES : 987.02 <> 986.917 : PERCENT : 0.0104444
TARGET_OUTPUT/ROUTING/200111/LIS_RST_HYMAP2_router_200111010000.d01.nc
DIFFER : VARIABLE : RIVSTO : POSITION : [661125] : VALUES : 2765.03 <> 2765.19 : PERCENT : 0.00588898
DIFFER : VARIABLE : RIVSTO : POSITION : [662324] : VALUES : 1402.08 <> 1401.92 : PERCENT : 0.011031
DIFFER : VARIABLE : RIVSTO : POSITION : [663522] : VALUES : 987.02 <> 986.917 : PERCENT : 0.0104444
TARGET_OUTPUT/ROUTING/200111/LIS_HIST_200111020000.d01.nc
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1028,552] : VALUES : 3442.29 <> 3442.4 : PERCENT : 0.00321275
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1029,554] : VALUES : 1947.92 <> 1947.77 : PERCENT : 0.0075075
TARGET_OUTPUT/ROUTING/200111/LIS_HIST_200111030000.d01.nc
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1028,577] : VALUES : 4203.56 <> 4203.72 : PERCENT : 0.00376341
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1028,1697] : VALUES : 12744 <> 12744.2 : PERCENT : 0.00144827
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1028,1698] : VALUES : 7552.47 <> 7552.57 : PERCENT : 0.00135121
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1029,554] : VALUES : 3052.67 <> 3052.57 : PERCENT : 0.00328702
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1029,577] : VALUES : 1340.16 <> 1339.92 : PERCENT : 0.0180078
DIFFER : VARIABLE : RiverStor_inst : POSITION : [1029,1695] : VALUES : 171.342 <> 170.995 : PERCENT : 0.202323
TARGET_OUTPUT/ROUTING/200111/LIS_RST_HYMAP2_router_200111030000.d01.nc
DIFFER : VARIABLE : RIVSTO : POSITION : [663522] : VALUES : 3052.67 <> 3052.57 : PERCENT : 0.00328702
DIFFER : VARIABLE : RIVSTO : POSITION : [691075] : VALUES : 4203.56 <> 4203.72 : PERCENT : 0.00376341
DIFFER : VARIABLE : RIVSTO : POSITION : [691076] : VALUES : 1340.16 <> 1339.92 : PERCENT : 0.0180078
DIFFER : VARIABLE : RIVSTO : POSITION : [2030440] : VALUES : 171.342 <> 170.995 : PERCENT : 0.202323
DIFFER : VARIABLE : RIVSTO : POSITION : [2032835] : VALUES : 12744 <> 12744.2 : PERCENT : 0.00144827
DIFFER : VARIABLE : RIVSTO : POSITION : [2034033] : VALUES : 7552.47 <> 7552.57 : PERCENT : 0.00135121
```

I'm also still seeing a bit of that banding above 39N.

image

Do these differences look acceptable to you? @dmocko what do you think?

**Comment by agetiran** [comment]
Hi @bmcandr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbmcandr&data=04%7C01%7Caugusto.getirana%40nasa.gov%7C9c81499a21f1433bbeac08d8b265270f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637455494821782717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z2FRl3PQjd1d28EAMn5cLewDm%2BHwz%2FU9Nm3jhBrCww4%3D&reserved=0>,
These differences seem to be very small to me.
In the 2-way coupling code, some key variables with high values are divided then multiplied by parameters when they are transferred to the LSM and back to HyMAP. These differences could be a residue resulting from real*4 approximations.

Augusto

**Comment by bmcandr** [comment]
Thanks @agetiran!

@dpsarmie, seems like we should be good to merge once the changes are pushed up.

**Comment by dmocko** [comment]
Hi @bmcandr @agetiran @dpsarmie 

I would like this to still be resolved.  I agree that the magnitudes of the differences are sufficiently small, but they are not random, and the banding is concerning.

Did one of you run with a single-processor and one in parallel?  The configure.lis files and "git log --oneline" should be compared.  It's probably an difference with how the two runs are done, instead of an issue with the code.  But I think that we should confirm this.

David

**Comment by bmcandr** [comment]
@dmocko, ok that makes sense. Since this is a fix for running HyMAP2 coupling in parallel mode I ran in parallel mode and I imagine Daniel did the same. The original lis.config used 8 processes, but I upped it to 28 for my test runs. I diffed my configure.lis with Daniel's (in the parent directory of the newest target output) and they are identical.

**Comment by dpsarmie** [comment]
I kept my runs at 8. Is it worth rerunning and matching number of processors?

**Comment by bmcandr** [comment]
I just submitted an 8 proc job to get it in the queue in case it's worth exploring.

**Comment by bmcandr** [comment]
Update: the 8 processor run produced identical output to the target.

**Comment by dmocko** [comment]
Hi @bmcandr 

Great - thanks for the confirmation.

I now am fine with this pull request being merged.  Many thanks for @dpsarmie for adding this much-needed fix and for @agetiran for his comments and continued development for HyMAP2.

Two additional items:

1) This PR is fine to be merged into master, but should also be included in the next public-7.3 patch release.

2) If a different number/configuration of processors is giving different answers from HyMAP2, then we should open this as a separate issue.  While the differences are small for this short testcase, they may grow over a longer simulation.

David

**Comment by dpsarmie** [comment]
Thanks @bmcandr for confirming the # of processors issue. I've updated the lis.config.adoc with the options that David mentioned.

**Comment by bmcandr** [comment]
@dpsarmie, thanks for updating adding the documentation. Are the changes I asked about [earlier ](https://github.com/NASA-LIS/LISF/pull/632#pullrequestreview-529509804) not needed? Just want to confirm before merging.

**Comment by bmcandr** [comment]
@dpsarmie sorry, one more request. Can you also edit this PR to target to the support/lisf-public-7.3 branch instead of master? After speaking with Jim, we will be actively supporting the public release and bugfixes such as this will need to be merged there.

Thanks for pushing the changes and your patience!

**Comment by dpsarmie** [comment]
Ok @bmcandr . I've changed the base for the commit and added the changes you requested. 

I understand that the variable is set to zero and the errors will never be called, but the 2-way implementation is still being worked on. I would say leave them since the subroutines are placeholders anyways but I can be swayed if you or someone else feels strongly against leaving those statements there.

**Comment by dmocko** [comment]
Thanks @dpsarmie for all the additions.  The lis.config details are helpful.

I'm worried that without the errors actually being called, users will try to enable 2-way coupling in the lis.config file and never know that it's not doing anything.  It's not clear which LSMs support 2-way coupling, and which are just placeholders.  By allowing those error messages to be sent to the log file, the run will stop, and users will know.

David

**Comment by agetiran** [comment]
I agree with David. I’m implementing 2-way coupling with other LSMs and am removing the error message when the implementation is complete for each of them.

For now, NoahMP36 is the only model 2-way coupled with HyMAP in the latest LIS version. I recently did the implementation for Noah36 and NoahMP401 (not yet committed) and will do the same for other models.

Augusto

**Comment by bmcandr** [comment]
Hi @dpsarmie, I'd like to get this merged today if possible. Once the `enable2waycpl = 0` lines are removed from the CLSMF2.5 and NoahMP-4.0.1 routines it should be good to go!

**Comment by dpsarmie** [comment]
Sorry @bmcandr. Thought we were good to go after the discussion of keeping the error calls in the code. I've removed the lines you mentioned from those files. Let me know if there's anything else needed.

**Comment by bmcandr** [comment]
No worries! I think I owe you an apology as I have another question: Should the following calls precede the `if(enable2waycpl==1)` check in each of the `_getsws_hymap2` routines?

```fortran
call ESMF_AttributeGet(LIS_runoff_state(n),"2 way coupling",&
       enable2waycpl, rc=status)
call LIS_verify(status)
```

These calls are present in the `noah36_getsws_hymap2` routine and hidden behind the `#if 0` preprocessor check in `noahmp401_getsws_hymap2`. They are missing from the `clsmf25_getsws_hymap2` routine.

**Comment by dpsarmie** [comment]
Ok, those files were modified. Let me know if there are any issues.

**Comment by bmcandr** [comment]
Thanks again. I'm going to to a quick test and I'll merge if all goes well.

**Review by bmcandr — APPROVED** [review]

**Comment by jvgeiger** [comment]
I am merging into master.

**Comment by jvgeiger** [comment]
Testing was good.  I have merged this into master.

**Pull request merged**
