### PR TITLE
Add GEFS forcing reader

### PR DESCRIPTION
**Pull request by karsenau**
- Added new GEFS forcing reader
 - Updated documentation included
 - Testcase also included within:
    lis/testcases/metforcing/gefs

Testcase input/output files are located here:
LDT:  /discover/nobackup/projects/lis/Projects/LDT/LISF_Testcases/GEFS_Forcing/LDT_Test/testcase_ldt_input.tar.gz
LIS-Input:  /discover/nobackup/projects/lis/Projects/LDT/LISF_Testcases/GEFS_Forcing/LIS_Test/testcase_lis_input.tar.gz  
LIS-Output:  /discover/nobackup/projects/lis/Projects/LDT/LISF_Testcases/GEFS_Forcing/LIS_Testtestcase_lis_output.tar.gz

Addresses ticket issue #195

### CODE REVIEW

**Comment by emkemp** [comment]
Hi Kristi:

I tested the code with both Intel and GNU compilers, and found no run-time issues.

One suggested change:  in lis/configs/lis.config.adoc, remove the "devonly" markings for the new GEFS material.  I say this because the GEFS metforcing is supported by the build system by default.

**Comment by karsenau** [comment]
Thanks for testing this commit and for the documentation suggestion.

I removed the "devonly" markings.

**Comment by emkemp** [comment]
Hi Kristi:

I want to confer with Jim about your test case before merging this code in.  Otherwise we are ready to approve.

**Comment by karsenau** [comment]
Sure thing, and thanks for confirming that.

**Comment by emkemp** [comment]
I talked to Jim, and he gave me the go-ahead to merge in.  I will keep the AddToTestSuite label on this pull request, and Jim will track it down later and add to his test suite.

**Pull request merged**
