### PR TITLE
The SMAP reader was modified to read the SMAP L3 file with the latest…

### PR DESCRIPTION
**Pull request by LIS-navari**
… Release number and largest CRID Version Number

### CODE REVIEW

**Comment by LIS-navari** [comment]
Test case for LVT SMAP reader is available at 
/discover/nobackup/mnavari/my_projects/op/test_new_smap_reader4lvt
Screen Shot 2019-07-10 at 6 59 19 PM


Test case for soil moisture DA using new reader is available at /discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader
Screen Shot 2019-07-11 at 2 25 52 PM

**Comment by LIS-navari** [comment]
The correct figure for LVT SMAP reader is  the following. Please dismiss the above one. 

Screen Shot 2019-07-11 at 2 24 24 PM

**Comment by emkemp** [comment]
I'm working on this now.  Currently testing LDT with Intel 18.

**Comment by emkemp** [comment]
Okay, I ran LDT w/o issue.  LIS also runs w/o issue, but I had to cut the simulation off at 15 days.  

For LVT, the ARS test case is too long, and the SCAN test case fails with an array bounds error when calculation anomaly correlation.  I'm assuming this error is unrelated to your changes.  Recompiling w/o strict checks brings LVT to successful completion, but I have no SCAN stats to compare against.

I need to pivot to a 557 ticket.  I will resume testing when I can.

**Comment by emkemp** [comment]
Working on this again.  GNU test runs of LDT and LIS look fine.

I'm going to try testing LVT again with Intel, this time using the ARS case.

**Comment by LIS-navari** [comment]
Test case for LDT: 
/discover/nobackup/mnavari/my_projects/op/US_10km/new_smap_reader_ldt

**Comment by emkemp** [comment]
I'm reassigning this to Jim since there are conflicts between this new code and code on the master branch.

It will probably be necessary to clarify the status of current test cases.

**Comment by LIS-navari** [comment]
We have resolved these conflicts by creating a new branch.  We are closing this pull request and opening a new one. Please see #416.

**Pull request closed without merging**
