### PR TITLE
Update LIS documentation

### PR DESCRIPTION
**Pull request by karsenau**
- Fixed a wrong unit entry for the "forcing_variables.adoc" file
 - Added "Openwater" option for surface model types (may have been forgotten in the past)

Note: No issue was opened for this commit, since minor updates and easy to compare and merge.

### CODE REVIEW

**Comment by emkemp** [comment]
Hi @karsenau 

Are these errors also in the support/lisf-public-7.3 branch?  If so, I think this should go into that branch rather than master.

**Comment by karsenau** [comment]
Hi @emkemp,

Yes, these omissions and errors are also in support/lisf-public-7.3 branch.

Should I check out a fresh support/lisf-public-7.3 branch and push the commits / PR there?

Thanks!

**Comment by emkemp** [comment]
Hi @karsenau 

Yes, please checkout support/lisf-public-7.3, change the appropriate files, and make a new PR.  That way only these specific changes will be marked by git for merging.

@jvgeiger will then migrate these back into master, covering both branches.

**Comment by karsenau** [comment]
Hi @emkemp,

I have added and pushed the new commits via the support/LIS 7.3 branch (from a checkout from the support/LIS7.3 branch, with PR #881.

So if you want to go ahead and delete this pull request, or please guide in the best method to undo these commits and PR.
Thanks!

**Pull request closed without merging**
