### PR TITLE
Adds the support for LPRM vod retrievals

### LINKED ISSUE #172: Add support for LPRM VOD data in LDT

### PR DESCRIPTION
**Pull request by sujayvkumar**
This plugin adds the support for processing vegetation optical depth
retrievals from the Land Parameter Retrieval Model (LPRM). The data
was obtained from Dr. Richard de Jeu and vandersat.com

Resolves #172

### CODE REVIEW

**Comment by emkemp** [comment]
Hi Sujay:  Do you have a test case for this new feature, so we can compare the output?

**Comment by sujayvkumar** [comment]
You can find a test case (and output) at: 
/discover/nobackup/projects/lis_aist17/svkumar/SMAP_VOD_DA/procDA_CDF_LPRM_X

**Comment by emkemp** [comment]
Thanks!

Now can you add read permissions for /discover/nobackup/projects/lis_aist17/svkumar/SMAP_VOD_DA/data?  It looks like a landmask file in that directory is needed for this test.

**Comment by sujayvkumar** [comment]
Done. Please try again.

**Comment by emkemp** [comment]
I'm running a final test with the GNU compilers, and the results should be ready tomorrow morning.

One problem I notice:  You did not update ldt/configs/ldt.config_master to add the new config options for LPRM.  This should be corrected before the pull request is merged.

**Pull request merged**
