### PR TITLE
Incorporate SnowModel and MicroMet model code

### PR DESCRIPTION
**Pull request by karsenau**
- Implemented Glen Liston's SnowModel Code,
    MicroMet routines, and interface with NoahMP401.
 - Several new features are included, and the
    model is incorporated in the new subLSM layer,
    which Crocus v8.1 snow model is also found in.

 This code commit supports and addresses LISF GitHub
  issue #813 and #814;
  https://github.com/NASA-LIS/LISF/issues/813
  https://github.com/NASA-LIS/LISF/issues/814

 Test case available for full LDT and LIS-SnowModel
  testing for the pull request. The LDT and LIS testcases,
  along with target outputs and log files, can be found here:

  /discover/nobackup/karsenau/LISF_PR/LISF_SnowModel

  Both LDT and LIS have been run with the latest Intel 2021
  private module.  For the LIS test run, 72 processes are used
  and run on a checked out compute node. SnowModel will
  be run for 1-year with daily output and takes about 30-minutes
  to run with 72 processes.

### CODE REVIEW

**Comment by karsenau** [comment]
Note:
LIS-SnowModel will not compile without the following compiler  FFLAGS and FFAGLS77 flag:
-mcmodel=medium

Also, for LDT, please select "little-endian" when running the ./configure script.

The LDT and LIS config.adoc files have been updated with the config options and descriptions.  Please let me know if you need any further information for configure or compiling either LDT of LIS with SnowModel.

**Comment by emkemp** [comment]
Hi @karsenau 

Can you point us to your SLURM submission script?  Our test runs are failing, and I wonder if we need to limit the number of processes per node and/or target specific compute nodes.

**Comment by karsenau** [comment]
@emkemp:

Please check out the slurm script:   slurm_sm_test.job 
(in same testcase directory)

Also, make sure you compiled with:
LIS-SnowModel will not compile without the following compiler FFLAGS and FFAGLS77 flag:
-mcmodel=medium

**Comment by emkemp** [comment]
Hi Kristi:

So @cmclaug2 is running your test case.  The case fails as-is because of a missing lis.config entry (SnowModel preprocess code option: is not in the config file).  When we add it and set it to 1, LIS stops in the preprocess code.

It seems your test case is not necessarily up to date given the problem with the lis.config file.  Can you (as time permits) try running the case again on your end?

BTW, @jvgeiger merged master back into your branch to resolve two merge conflicts.

**Comment by karsenau** [comment]
Hi @emkemp and @cmclaug2:

Thank you for letting me know about the issue that you ran into with the lis.config file for this test case. 

I will definitely run again on my end and let you know when the updated test case is ready.

**Comment by karsenau** [comment]
Hi @emkemp and @cmclaug2:

Please try rerunning the testcase again - I have placed the updated files here (with a slurm script):
/discover/nobackup/karsenau/LISF_PR/LISF_SnowModel

**Comment by cmclaug2** [comment]
Hi @karsenau:

I was able to use the updated files to reproduce the results for the LDT and LIS testcases.  I was also able to compile LDT and LIS with the gnu compiler. 

Before merging, I want to double check with @emkemp that this is ready to go.

**Comment by emkemp** [comment]
Hi @cmclaug2 

We need to confer with @jvgeiger to decide how to handle that special compiler flag.  I'll take this into e-mail.

**Comment by emkemp** [comment]
Hi @karsenau 

We have concerns about the runtime performance and memory requirements when using -mcmodel=medium with non-Snowmodel cases.  @jvgeiger will run some experiments with the existing test suite to see if any surprises occur.  In the meantime, we plan to turn snowmodel *off* by default (same as with Crocus).  @cmclaug2 will also make a few tweaks to ensure consistent character variable lengths for some strings.

**Comment by karsenau** [comment]
Hi @emkemp, @jvgeiger and @cmclaug2:

Thank you for testing the SnowModel and MicroMet implementations. 

I definitely understand the hesitation to include the "-mcmodel=medium" addition for the library flags. SnowModel has difficulty compiling/ running without it. Also, that makes sense to turn off snowmodel in default.cfg setup.

Please let me know if you have any other questions or issues. Thanks!

**Pull request merged**
