### PR TITLE
Add new river routing model (RAPID)

### PR DESCRIPTION
**Pull request by yyoon4**
### Description

**Add a new river routing model, RAPID (Routing Application for Parallel Computation of Discharge).**

See issue #1227 for the detailed information and environmental setting

### Testcase
/discover/nobackup/yyoon4/lis7/Testcase/rapid_noah39

### CODE REVIEW

**Comment by emkemp** [comment]
Update on this pull request:

Code compiles with GNU and Intel compilers.  I now have a test run submitted to the queue on Discover.

**Comment by emkemp** [comment]
Hi @yyoon4 

I reproduced the results for the LIS-Noah39-RAPID test case. 

HOWEVER, I see this pull request also adds code for interfacing RAPID with NoahMP 4.0.1 and Jules 5.0.  Do you have test cases for those as well?

**Comment by yyoon4** [comment]
Many thanks for your help!! @emkemp 

I have added test cases for NoahMP401 and JULES50:
/discover/nobackup/yyoon4/lis7/Testcase/rapid_noahmp401
/discover/nobackup/yyoon4/lis7/Testcase/rapid_jules50

**Comment by emkemp** [comment]
Good morning @yyoon4 

I successfully reproduced your results for jules50.  I will reach out to @cmclaug2 to see how the noahmp401 tests went.

**Comment by cmclaug2** [comment]
Hi @emkemp.  I successfully reproduced @yyoon4 results for the noahmp401 test.

**Comment by emkemp** [comment]
With all LSM results reproduced, we are ready to merge this pull request in.  I accept.

**Pull request merged**
