### PR TITLE
Implements the joint entropy method

### PR DESCRIPTION
**Pull request by sujayvkumar**
This commmit adds the support for the joint entropy metric
calculation

Related to #524

### CODE REVIEW

**Comment by sujayvkumar** [comment]
A testcase can be found at : /discover/nobackup/svkumar/LISF_testing/524

**Comment by bmcandr** [comment]
Hi @sujayvkumar 

The code looks clean and testing on Intel 18 and 19 as well as GNU4 produced identical results with no compile or runtime errors. Before I merge, I have a question: should Joint Entropy be added to `lvt/configs/METRICS.TBL`?

**Comment by sujayvkumar** [comment]
The documentation has been updated as requested.

**Comment by bmcandr** [comment]
Thanks @sujayvkumar. And thanks for also adding the metrics from recent PRs to the docs as well! I'm still getting a sense of which variables should be explicitly described in the documentation.

This PR looks to be in good shape and I am therefore merging.

**Pull request merged**
