### PR TITLE
feature/WUS_UCLA

### PR DESCRIPTION
**Pull request by TimLahmers**
### Description

A DA reader for the Margulis et al. CONUS Snow Reanalysis dataset is added to the LIS model. This change is required so that this new dataset, which will likely be widely used in the Snow Hydrology community, can be assimilated into the LIS model.

Resolves Issue #1114 

### Testcase
Log Files for two 6-month periods:
/discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_CentralCA_01km_wDA_Test/DA_Margulis_2015TEST
/discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_CentralCA_01km_wDA_Test/DA_Margulis_2018TEST

Output Directory:
/discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_CentralCA_01km_wDA_Test/OUTPUT_CaliforniaColumbiaISRIC_wSWEFix_DA

LIS lis.config File:
/discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_CentralCA_01km_wDA_Test/lis.config_RegionalTemplate_WestUSISRIC_wDA_wRST

Post-Processing lvt.config File:
/discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_CentralCA_01km_wDA_Test/lvt.config

### CODE REVIEW

**Comment by TimLahmers** [comment]
Hi @jvgeiger 

Thanks for the updates. My answers for your questions are below:

1) The weblink for this dataset is below. There is not yet a publication for it. Will that be sufficient for documentation?
https://nsidc.org/data/WUS_UCLA_SR/versions/1

A revised statement could read:
"""
! This module contains interfaces and subroutines to
! handle the Margulis Western US Snow Reanalysis dataset.
Available online at: https://nsidc.org/data/WUS_UCLA_SR/versions/1
"""

2) This line is for debugging. Since we added QC routines to remove extremely large assimilated snow values, it can probably be removed, but I defer to @sujayvkumar 

3) These are for debugging and can be removed.

**Comment by jvgeiger** [comment]
Hello,

Thanks.  Your response for question 1 is good.  I will add that and clean up the code regarding question 3.  I will wait for Sujay's reply regarding question 2.

I am unable to read your output.  Would you please reset some file permissions?

```
cd /discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_CentralCA_01km_wDA_Test
find OUTPUT_CaliforniaColumbiaISRIC_wSWEFix_DA -type d -exec chmod 755 '{}' ';'
find OUTPUT_CaliforniaColumbiaISRIC_wSWEFix_DA -type f -exec chmod go+r '{}' ';'
```

Also, do you have the ldt.config file used to generate lis_input_001ctr_wHyMAP_ISRIC_CaliforniaColumbiaRegion_FullDom.nc?

**Comment by TimLahmers** [comment]
The directory permissions have been updated. 

The ldt.config file is located here. This also relies on some HyMAP parameter files, which are also listed below:
/discover/nobackup/projects/eis_freshwater/lahmers/SHARE/ldt.config_freshwaterRegional_CaliforniaColumbiaRegionWBD_ISRIC_wHyMAP
/discover/nobackup/projects/eis_freshwater/lahmers/SHARE/eis_fire_ca/

**Comment by jvgeiger** [comment]
@TimLahmers ,

Your lvt.config file does not match your lis.config file.  The lvt.config file has

```
Input domain and mask data file: ./lis_input_001ctr_wHyMAP_CaliforniaColumbiaRegion_FullDom.nc
LIS output domain and parameter file:  ./lis_input_001ctr_wHyMAP_CaliforniaColumbiaRegion_FullDom.nc
LIS output methodology:            "2d ensemble gridspace"
```

I believe that it should be

```
Input domain and mask data file: ./lis_input_001ctr_wHyMAP_ISRIC_CaliforniaColumbiaRegion_FullDom.nc
LIS output domain and parameter file:  ./lis_input_001ctr_wHyMAP_ISRIC_CaliforniaColumbiaRegion_FullDom.nc
LIS output methodology:            "2d gridspace"
```

Am I correct?  Did I miss anything else in the lvt.config file?

Thanks,
Jim

**Comment by TimLahmers** [comment]
@jvgeiger Thanks for following up, and that is correct. the lis_input.nc file specified in the lvt.config file should also be ./lis_input_001ctr_wHyMAP_ISRIC_CaliforniaColumbiaRegion_FullDom.nc

The difference between those files is the soil (the correct one is ISRIC while the old one that was specified uses STATSGO), but the dimensions are otherwise the same. Will that affect the post-processing by LVT? If so, do you need me to re-run LVT? All of the raw binary output is still there, so I can do that if needed.

**Comment by jvgeiger** [comment]
@TimLahmers ISRIC vs STATSGO should now affect the LVT processing.  I expect that "2d ensemble gridspace" vs  "2d gridspace" will.  The lis.config file is writing "2d gridspace", so I changed the lvt.config file to match.  Do you see any other inconsistencies between the lis.config file and the lvt.config file?

Thanks,
Jim

**Comment by TimLahmers** [comment]
@jvgeiger Thanks for checking that. There should be no other issues with the lvt.config file. Are you going to re-run it or do you need me to do that? If you re-run LVT, it will need to be run twice (once for 01-OCT-2014 to 01-APR-2015 and once for 01-OCT-2017 to 01-APR-2018). I executed the model with DA for those two time periods to capture a dry (2014-15) and wet (2017-18) winter season.

**Comment by jvgeiger** [comment]
@TimLahmers Would you please rerun LVT for your two seasons?  Right now, I am only processing Oct 2017 to verify that I have  everything set up correctly.

Thanks,
Jim

**Comment by TimLahmers** [comment]
Thanks @jvgeiger I just submitted the jobs to process 2014 and 2017. LVT should over-write the old LIS_HIST************.nc files. To save time, I am using two different lvt.config files (lvt.config2015 and lvt.config2018) so two instances of LVT can run at the same time. I will check to make sure everything ran ok during the weekend, so the new files should be ready first thing on Monday morning. Please let me know if any other outstanding issues with this PR arise.

**Comment by TimLahmers** [comment]
@jvgeiger I checked over the weekend, and I can confirm that the new LIS_HIST************.nc are written for the 2014-2015 and 2017-2018 snow test cases. Please let me know if any other issues arise.

**Pull request merged**
