### PR TITLE
Fix PMW_snow reader to support observation space-based analysis, as w…

### PR DESCRIPTION
**Pull request by yyoon4**
Partially resolving #154 (only PMW_snow case)

Here is the testcase:
/discover/nobackup/yyoon4/lis7/Testcase/pmw_snowda_nam

Yeosang

### CODE REVIEW

**Comment by yyoon4** [comment]
Thanks for your review, Eric,

TODO for HDF4 and HDF-EOS parts: This reader also takes care of HDF4 and HDF-EOS formats, but I do no have any sample datasets for those modules. That's why I did not update the codes yet. I can update the codes, but I can ensure that the codes work correctly.

BTW, I will test codes more securely

**Comment by yyoon4** [comment]
Hi Eric,
Thanks for checking the codes. I fixed the codes following your suggestion. 

Thanks again,
Yeosang

**Comment by emkemp** [comment]
Actually, it looks like the LIS_domain lat and lon values aren't being set either.  (Or at least Valgrind doesn't think so.)  This is a strange bug.

**Comment by yyoon4** [comment]
Update rlat and rlon in PMW_snow_Mod.F90 and read_PMW_snow.F90

**Comment by emkemp** [comment]
There's still a problem with the interpolation.  Valgrind gives this error for processor 001:

==4966== Invalid read of size 4
==4966==    at 0x14AEF2A: polfixs_ (polfixs.F90:66)
==4966==    by 0xAB7102: bilinear_interp_ (bilinear_interp.F90:163)
==4966==    by 0x1596402: read_pmwsnow_hdf5_ (read_PMW_snow.F90:735)
==4966==    by 0x159817D: read_pmw_snow_ (read_PMW_snow.F90:132)
==4966==    by 0x6AC263: readdaobs_ (LIS_dataassim_FTable.c:820)
==4966==    by 0x660EA8: __lis_daobservationsmod_MOD_lis_readdaobservations (LIS
_DAobservationsMod.F90:1470)
==4966==    by 0x16B3A18: __retrospective_runmod_MOD_lis_run_retrospective (retr
ospective_runMod.F90:198)
==4966==    by 0x7C4946: lisrun_ (LIS_runmode_FTable.c:198)
==4966==    by 0xFE3203: MAIN__ (lisdrv.F90:68)
==4966==    by 0xFE32E0: main (lisdrv.F90:55)
==4966==  Address 0x2f274c28 is 0 bytes after a block of size 9,288 alloc'd
==4966==    at 0x11A9508D: malloc (vg_replace_malloc.c:299)
==4966==    by 0x6B0FB5: __lis_domainmod_MOD_readdomaininput (LIS_domainMod.F90:
2443)
==4966==    by 0x6C9FD2: __lis_domainmod_MOD_lis_domain_init (LIS_domainMod.F90:
139)
==4966==    by 0x16B3AF0: __retrospective_runmod_MOD_lis_init_retrospective (ret
rospective_runMod.F90:84)
==4966==    by 0x7C4803: lisinit_ (LIS_runmode_FTable.c:125)
==4966==    by 0xFE3174: MAIN__ (lisdrv.F90:65)
==4966==    by 0xFE32E0: main (lisdrv.F90:55)
==4966== 

This appears to be real.  Print statements show that the expected size of rlat is 2365, but the actual size of the array passed (LIS_domain(n)%lat) is 2322.

**Comment by emkemp** [comment]
Sujay recommends retiring this reader (as of 24 Sep 2019).  We'll discuss in more detail.

**Pull request closed without merging**
