### PR TITLE
S2S CFSv2 script update

### PR DESCRIPTION
**Pull request by karsenau**
- Corrected the year directory placement for January forecast files, where members are made up of December dates of prior year.

 - Also, increased slurm request hours for BCSD hindcast preprocessing. (since time outs have been occurring recently on Discover)

### CODE REVIEW

**Comment by karsenau** [comment]
@emkemp and @jvgeiger:
Submitting PR for latest S2S code update (to go to LIS 7.6 support branch in future)

**Comment by emkemp** [comment]
Hi @karsenau 

Is there any particular reason you "rolled back" the version number and copyright dates of the two scripts?  The earlier versions are marked as LIS Version 7.5 and copyright 2024.  (@jvgeiger should that information be changed?)

**Comment by karsenau** [comment]
@emkemp:

Yes, those should be LIS Version 7.5 and copyright 2024

**Comment by emkemp** [comment]
Thanks @karsenau 

The changes look fine to me.  I approve.

**Pull request merged**
