### PR TITLE
Enables the support for SMAP VOD

### LINKED ISSUE #210: Add support for processing SMAP L2 VOD retrievals in LVT

### PR DESCRIPTION
**Pull request by sujayvkumar**
This commit enables a new plugin for processing the VOD retrievals from SMAP.
Note that the plugin only supports the L2 SMAP data versions, as the L3
versions of the data only contain the MODIS VOD climatology.

Resolves #210

### CODE REVIEW

**Comment by sujayvkumar** [comment]
An example testcase is available at : /discover/nobackup/svkumar/LISF_testing/210 %

**Comment by sujayvkumar** [comment]
Eric, I inadvertently deleted the files in my directory. How do I checkout this feature branch only? 
-S

**Comment by dmocko** [comment]
Sujay,

On the bottom of this page: https://github.com/NASA-LIS/LISF/pull/212

You will see a sentence reading:

You can also open this in GitHub Desktop or view command line instructions.

Click on "command line instructions".

Step 1 shows the two commands to checkout this feature branch.

David

**Comment by emkemp** [comment]
Hi Sujay:

Are you referring to your feature branch?  If so, run:

git clone https://github.com/sujayvkumar/LISF.git LISF.git
cd LISF.git
git checkout feature/SMAPvodLVT

And then run 'git branch' to confirm this branch is on the file system and ready for edits.

**Comment by emkemp** [comment]
Actually, strike that.  I don't think my instructions are correct.

**Comment by sujayvkumar** [comment]
Thanks - I figured it out. Back in business

**Comment by emkemp** [comment]
For future reference if you lose your local repository but have the branch on GitHub:

git clone https://github.com/sujayvkumar/LISF.git LISF.git  # Only gets master branch
cd LISF.git
git fetch origin feature/SMAPvodLVT  # Alerts local repo of remote feature branch
git checkout feature/SMAPvodLVT # Creates local branch that tracks remote branch
git branch # Prints out confirmation on what branch is checked out

After this, you can work, and just type 'git push' to push the local branch changes back to the remote repo *on the existing branch*.  (The instructions in the "Working with GitHub" document assumes the branch doesn't exist yet on GitHub, or that the local repo already is tracking the remote branch.)

**Pull request merged**
