### PR TITLE
Fix GRACE DA for NoahMP.3.6 (LIS) and 0.25 deg GRACE reader (LDT)

### PR DESCRIPTION
**Pull request by bmcandr**
### Description

**Note: all code changes in this pull request were made by @bailinglee and @KathyNie.** I am simply opening this pull request on their behalf because we needed to separate the fixes from the new features introduced together in #216.

Fixes made to LDT and NoahMP.3.6 have been cherry-picked from the original feature branch onto the support/lisf-public-7.3 branch. These changes are introduced here. See the original pull request, commit messages below, and Issue #61 for context on these changes.

### Testcase

* **LDT**: /discover/nobackup/projects/lis/PR_TESTCASES/216/testing_new/ldt

  Compile with default settings, run LDT, and compare to the output found in *TARGET_GRACEOBS* (provided [here](https://github.com/NASA-LIS/LISF/pull/216#issuecomment-580909388)).

* **LIS**: /discover/nobackup/projects/lis/PR_TESTCASES/216/testing_new/noahmp36/new-branch

  Compile with default settings, run LIS, and compare to the output in *TARGET_OUTPUT*. This target output was generated using an executable compiled from the original feature branch to make sure the new branch produces the same output (it is not identical, but _very_ close. Bailing has approved the output used for this comparison.

### CODE REVIEW

**Comment by emkemp** [comment]
I completed testing of LDT, with and without strict checks, and I see no issues with the output.

I am testing LIS now.

**Comment by emkemp** [comment]
LIS fails with this error message:

[ERR] ESMF_DistGridCreate failed: obsgridDG Stopping.
 [ERR] endrun is being called
 
 I'm using the new lisf_7_intel_19_1_3_304, which is using ESMF 8.0.1.  I believe an earlier attempt to use ESMF 8 uncovered a bug in LIS last year that was fixed.  It may be that this pull request doesn't have that fix yet.
 
 I'm going to recompile with an older module and try again.

**Comment by emkemp** [comment]
I recompiled with module lisf_7_intel_19_1_3_304_traceback-work-around, and LIS runs to completion.  However, looking at the output, I see some differences in moisture, temperature, and fluxes in the eastern part of the domain by 200304.

When setting up my test run, I noticed that the original lis.config pointed to a VEGPARM.TBL and GENPARM.TBL table on the LIS project disk in noahmp_parms.  However, that subdirectory doesn't exist.  There are noahmp36_parms and noahmp40_parms, and noahmp401_parms directories, and I substituted the 36 version. 

So, I see two potential causes:

(1) Different environment module.  Do you know which module you compiled and ran LIS with?
(2) Different VEGPARM.TBL and GENPARM.TBL files.  This seems less likely, as I think the only TBL updates for NoahMP were with the SOILPARM.TBL file.  Still, it's possible.

My current test output is in /discover/nobackup/projects/lis_aist17/emkemp/pr/748/work/lis/OUTPUT_0125/EXP019/SURFACEMODEL/200304

**Comment by bmcandr** [comment]
Thanks for reviewing this @emkemp!

>Do you know which module you compiled and ran LIS with?

I was using the current version of [lisf_7_intel_19_1_3_304](https://github.com/NASA-LIS/LISF/blob/master/env/discover/lisf_7_intel_19_1_3_304) in the master branch (uses ESMF 7.1.0, last updated Nov 2020).

Looks like the *noahmp_parms/* directory may have been a casualty of reorganization/spring cleaning. Sorry for not packaging this up as a testcase at the time.

@bailinglee, do you happen to have the param files that used to be in */discover/nobackup/projects/wldas/bli/wwao/noahmp_parms*? If not, can we swap in the param files in /discover/nobackup/projects/wldas/bli/wwao/noahmp for testing?

**Comment by bailinglee** [comment]
I don't have a noahmp_parms directory in my bli/wwao.
I assume Eric is testing the code I checked in this year for the central California testcase.  Then the Noahmp parameter files should be:

Noah-MP.3.6 landuse parameter table:      /discover/nobackup/projects/lis/LS_PARAMETERS/noahmp_params/VEGPARM.TBL
Noah-MP.3.6 soil parameter table:         /discover/nobackup/projects/lis/LS_PARAMETERS/noah3X_parms/SOILPARM.TBL.2016
Noah-MP.3.6 general parameter table:      /discover/nobackup/projects/lis/LS_PARAMETERS/noahmp_params/GENPARM.TBL
Noah-MP.3.6 MP parameter table:           /discover/nobackup/projects/nca/dmocko/configs/noahmp.MPTABLE.new

Let me know if you have other questions,

Bailing

From: Brendan McAndrew ***@***.***>
Sent: Friday, May 14, 2021 3:08 PM
To: NASA-LIS/LISF ***@***.***>
Cc: Li, Bailing (GSFC-617.0)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Fix GRACE DA for NoahMP.3.6 (LIS) and 0.25 deg GRACE reader (LDT) (#748)


Thanks for reviewing this @emkemp<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Femkemp&data=04%7C01%7Cbailing.li-1%40nasa.gov%7C72d1f92a2dbc4233531008d9170ba049%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637566161011341035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BU5xzIQHe9bh6TcUsVKNpSPJmK6Mo39GcIRDWwdJS2I%3D&reserved=0>!

Do you know which module you compiled and ran LIS with?

I was using the current version of lisf_7_intel_19_1_3_304<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fblob%2Fmaster%2Fenv%2Fdiscover%2Flisf_7_intel_19_1_3_304&data=04%7C01%7Cbailing.li-1%40nasa.gov%7C72d1f92a2dbc4233531008d9170ba049%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637566161011350991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=06a27uH2jQGpvGPkh33EZBCcu00zyH4cbtn2d%2BP1HCk%3D&reserved=0> in the master branch (uses ESMF 7.1.0, last updated Nov 2020).

Looks like the noahmp_parms/ directory may have been a casualty of reorganization/spring cleaning. Sorry for not packaging this up as a testcase at the time.

@bailinglee<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbailinglee&data=04%7C01%7Cbailing.li-1%40nasa.gov%7C72d1f92a2dbc4233531008d9170ba049%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637566161011350991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Cu%2FJJ%2Bdc0eKlTJrxtagfx4xJclJgH0x31w9t4nopPaU%3D&reserved=0>, do you happen to have the param files that used to be in /discover/nobackup/projects/wldas/bli/wwao/noahmp_parms? If not, can we swap in the param files in /discover/nobackup/projects/wldas/bli/wwao/noahmp for testing?

-

**Comment by emkemp** [comment]
Hi Bailing:

I believe that is the case.  But:

/discover/nobackup/projects/lis/LS_PARAMETERS/noahmp_params/VEGPARM.TBL

and

/discover/nobackup/projects/lis/LS_PARAMETERS/noahmp_params/GENPARM.TBL

No longer exist.

**Comment by emkemp** [comment]
Thanks @bmcandr  I'll try the older version of  lisf_7_intel_19_1_3_304  and see if I get better luck.

**Comment by bailinglee** [comment]
Hi Eric,
   Then try /discover/nobackup/projects/lis/LS_PARAMETERS/noahmp36_parms/.
    I think David reorganized the directory sometimes this year.

Bailing

From: Eric Kemp ***@***.***>
Sent: Friday, May 14, 2021 3:52 PM
To: NASA-LIS/LISF ***@***.***>
Cc: Li, Bailing (GSFC-617.0)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Fix GRACE DA for NoahMP.3.6 (LIS) and 0.25 deg GRACE reader (LDT) (#748)


Hi Bailing:

I believe that is the case. But:

/noahmp_params/VEGPARM.TBL

and

/discover/nobackup/projects/lis/LS_PARAMETERS/noahmp_params/GENPARM.TBL

No longer exist.

-

**Comment by emkemp** [comment]
I just finished a rerun using the older module.  I get the same answer as with lisf_7_intel_19_1_3_304_traceback-work-around.

I noticed that the PR description notes the output in /discover/nobackup/projects/lis/PR_TESTCASES/216/testing_new/noahmp36/new-branch "was generated using an executable compiled from the original feature branch to make sure the new branch produces the same output (it is not identical, but very close. Bailing has approved the output used for this comparison."  This implies exact matching is not possible.

Can one of you look at my output for a visual "thumbs up"?  It's in /gpfsm/dnb04/projects/p106/emkemp/pr/748/work/lis/OUTPUT_0125/EXP019_save/SURFACEMODEL.

As far as the code is concerned, there are some code in noahmp36_settws.F90 that has some unpleasant formatting (line is too long).  I'll push some edits shortly.

**Comment by bailinglee** [comment]
Hi Eric,
   This should be enough.  The settws file is not identical to what I had before.
    Thanks for closing this request.

Bailing

From: Eric Kemp ***@***.***>
Sent: Friday, May 14, 2021 5:00 PM
To: NASA-LIS/LISF ***@***.***>
Cc: Li, Bailing (GSFC-617.0)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Fix GRACE DA for NoahMP.3.6 (LIS) and 0.25 deg GRACE reader (LDT) (#748)


I just finished a rerun using the older module. I get the same answer as with lisf_7_intel_19_1_3_304_traceback-work-around.

I noticed that the PR description notes the output in /discover/nobackup/projects/lis/PR_TESTCASES/216/testing_new/noahmp36/new-branch "was generated using an executable compiled from the original feature branch to make sure the new branch produces the same output (it is not identical, but very close. Bailing has approved the output used for this comparison." This implies exact matching is not possible.

Can one of you look at my output for a visual "thumbs up"? It's in /gpfsm/dnb04/projects/p106/emkemp/pr/748/work/lis/OUTPUT_0125/EXP019_save/SURFACEMODEL.

As far as the code is concerned, there are some code in noahmp36_settws.F90 that has some unpleasant formatting (line is too long). I'll push some edits shortly.

-

**Comment by emkemp** [comment]
Good morning @bailinglee 

Thanks for reviewing.  I believe we are ready to merge then.  I approve.

**Pull request merged**
