### PR TITLE
Snow DA interface for LIS-JULES5X container

### PR DESCRIPTION
**Pull request by yyoon4**
Snow DA interface (SNODEP & USAFSI) for LIS-JULES5x container. 

Test case (CONUS):
/discover/nobackup/yyoon4/JULES5X/SRC/jules.5.x
lis.config.snodep -> SNODEP DA
lis.config.usafsi    -> USAFSI DA

### CODE REVIEW

**Comment by jvgeiger** [comment]
I do not have access to your SNODEP data.

**Comment by yyoon4** [comment]
@jvgeiger I change the data location and permission. Please try again.

**Comment by jvgeiger** [comment]
Thanks, but I do not have permission to read lis_hma.  Would you please run the cp_snodep.sh script in /home/jvgeiger/for/yeosang?  That will copy the needed files for me.

**Comment by yyoon4** [comment]
@jvgeiger 'cp_snodep.sh' is not working due to space issue e.g. 'cp/discover'
I copy the SNODEP data to my personal nobackup drive. You can access files in here:
/discover/nobackup/yyoon4/JULES5X/SRC/SNODEP

**Comment by jvgeiger** [comment]
Got the data.  Thanks.

**Pull request merged**
