### PR TITLE
Adds the support for the OzFlux in-situ data in LVT

### LINKED ISSUE #493: Add support for OzFlux in-situ data in LVT
In-situ measurements are available from: http://www.ozflux.org.au

### PR DESCRIPTION
**Pull request by sujayvkumar**
Plugin to process the OzFlux in-situ data has been developed in LVT

Resolves #493

### CODE REVIEW

**Comment by sujayvkumar** [comment]
A sample testcase can be found at: 
/discover/nobackup/svkumar/LISF_testing/494

**Comment by jvgeiger** [comment]
Sujay

1) Please document the new LVT config entries:

```
OzFlux observation directory:
OzFlux station list file:
```

2) Please commit your updated lvt/make/Filepath file.

**Comment by bmcandr** [comment]
- [x] Documentation provided
- [x] lvt/make/Filepath committed
- [x] LVT compiled and ran successfully on SLES 11 with Intel-18 based on https://github.com/NASA-LIS/LISF/pull/494/commits/ca1110e755a3d533e0d3f5f38af05711ee812b55

@jvgeiger @emkemp -- please verify and advise on next step, thanks!

**Comment by emkemp** [comment]
I confirm the updated code compiles.

Question:  Has anyone run Sujay's test case yet?

**Comment by bmcandr** [comment]
> I confirm the updated code compiles.
> 
> Question: Has anyone run Sujay's test case yet?

@emkemp I ran the testcase and it appears to have been successful (compared output in STATS.OzFlux/). You can find the output in /discover/nobackup/projects/lis/PR_TESTCASES/494/testcase to check. The raw data can be found in 494/from_svkumar.

**Pull request merged**
