### PR TITLE
Write soil layer global attributes to quilted NetCDF file in LVT "LIS postprocessing" mode

### LINKED ISSUE #1047: LVT's LIS Postprocessing does not write soil layer attributes to quilted NetCDF
### Bug Description

The new LIS Postprocessing mode introduced to LVT does not write soil layer global attributes to the quilted NetCDF file. Related to #1042.

I have a fix ready and will open a PR soon.

### PR DESCRIPTION
**Pull request by bmcandr**
### Description

The "LIS postprocessing" mode introduced to LVT in #1042 does not write `NUM_SOIL_LAYERS` or `SOIL_LAYER_THICKNESSES` global attributes to the quilted NetCDF file because they are not contained in the LIS-generated binary output files. This fix adds optional LVT configuration entries for both attributes so users can write these attributes if they wish.

The `history` attribute is still not written. I'm torn on whether to add support for that too. It does [*not* appear to be required by the CF conventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#description-of-file-contents) and users would have to enter, and update, a properly formatted string in their config file (e.g., `"created on date: 2020-07-17T11:04:15.799"`). Seems prone to error and inaccuracy.

@sujayvkumar, let me know what you think.

Resolves #1047

### Testcase

`/discover/nobackup/projects/lis/PR_TESTCASES/1042/testing/`

### CODE REVIEW

**Comment by sujayvkumar** [comment]
@bmcandr  - The soil layer options can be added as user specific config options in LVT. Once you obtain them, we can add to the attributes. 

I think we can let go of the history attribute.

**Comment by sujayvkumar** [comment]
@bmcandr  : Looks good. Thanks Brendan!

**Comment by dmocko** [comment]
I agree that the history attribute is not needed at this time, but if/when we ever get the point where LVT can generate GES DISC-ready LDAS netCDF files, this attribute will be needed.  We will need to add it back in, along with many other attributes.

**Comment by bmcandr** [comment]
@dmocko, that link indicates that they are not actually required by the CF convention.

>For backwards compatibility with COARDS **none** of these global attributes is required.

**Comment by dmocko** [comment]
@bmcandr,  Good catch - thanks for the clarification.

Yes, probably explains the differences, and I was more following requests from the GES DISC (who were telling me some attributes were for CF compliance) instead of a super-strict read of the text at that link.

So, it's required/requested from the GES DISC, but not for CF compliance.

**Comment by dmocko** [comment]
One other thing about the LDAS datasets at the GES DISC:  Instead of variables with multiple layers (such as soil moisture), which requires a global attribute about listing the soil layer thicknesses - the GES DISC requested each soil layer as a separate variable.

```
        float SoilM_0_10cm(time, lat, lon) ;
        float SoilM_10_40cm(time, lat, lon) ;
        float SoilM_40_100cm(time, lat, lon) ;
        float SoilM_100_200cm(time, lat, lon) ;
```

The layer structure is in the variable name.  This also makes it a little easier to handle if the LSM has a different layer structure for soil moisture layers and soil temperature layers.

**Comment by bmcandr** [comment]
I updated my fix to use the existing LVT config entries for soil moisture and also added support for soil temperature layer attributes. I modified the attribute names to indicate the difference so `NUM_SOIL_LAYERS` is now `NUM_SOIL_MOIST_LAYERS` and `NUM_SOIL_TEMP_LAYERS`, respectively. Same goes for the thickness attributes.

I've added a testcase as well at this location: `/discover/nobackup/projects/lis/PR_TESTCASES/1042/testing/lisrun_clean`

**Comment by emkemp** [comment]
I dusted off this pull request.  The new soil layer thickness output from the test case is in meters, but other parts of LIS and LVT treat this as centimeters.  Do we want to add another option to specify the units in the LVT output file for clarification?

**Comment by emkemp** [comment]
I'm rescinding my earlier comment.  It turns out the soil layer thicknesses are set in the lvt.config, so it is trivial to change the thicknesses from meters to centimeters.

The larger question of whether units should be added as an additional attribute can be handled by a separate pull request.

@dmocko Do you believe the GES DISC requirement of separate 2d arrays for soil fields for each soil layer is important enough to add to this pull request, or can it be addressed separately?

**Comment by emkemp** [comment]
*PING*

Hi @dmocko:

Do you believe the GES DISC requirement of separate 2d arrays for soil fields for each layer is important enough to add to this pull request, or can it be addressed separately?

**Comment by dmocko** [comment]
Hi @emkemp 

The GES DISC request for separate 2d arrays for soil fields for each layer can be addressed in a separate pull request.

I am in favor of having LIS directly output the soil fields as separate 2nd arrays (as a config option) instead of in LVT.

**Comment by emkemp** [comment]
Thanks @dmocko.   I will coordinate with @jvgeiger on handling the test case before approving this pull request.

**Comment by cmclaug2** [comment]
I confirm that the `NUM_SOIL_MOIST_LAYERS` and `NUM_SOIL_TEMP_LAYERS` attributes correctly define the number of soil layers.  I will approve this PR.

**Pull request merged**
