### PR TITLE
Awral

### PR DESCRIPTION
**Pull request by wendyksharples**
@jvgeiger @dmocko @shugongwang, I've marked this as a draft pull request to get feedback.

 Please take a look at the current implementation of AWRAL 6.0.0. I have followed the general template design and merged the latest version of master to my forked repository.

The Australian domain is implemented at 0.05 degree resolution.

I have generated a testcase, see: LISF/lis/testcases/surfacemodels/land/awral.6.0.0

The input and output tarballs are on the er4 project on Raijin:
/g/data/er4/LIS/AWRAL_testcase

### CODE REVIEW

**Comment by wendyksharples** [comment]
@bmcandr @dmocko @shugongwang I've reviewed the comments and tried to address all of them bar the documentation as there is a comprehensive model description report available that I thought we could include? See: [http://www.bom.gov.au/water/landscape/assets/static/publications/AWRALv6_Model_Description_Report.pdf](url)

**Comment by bmcandr** [comment]
Thanks @wendyksharples! I do not have access to Raijin so I cannot get the testcase inputs/outputs. Is there a way that you can share these files with me so I can test? @dmocko @shugongwang, maybe you can pull them over to discover if you have Raijin access?

**Comment by dmocko** [comment]
Hi @bmcandr.  We're exploring another way to get the testcase.  Once I have it, I'll let you know.

**Comment by bmcandr** [comment]
Also, compile fails on discover due to the addition of the libraries `-lsz -ltirpc` on line 826 in `Config.pl`.

**Comment by wendyksharples** [comment]
Hi @bmcandr I took out the libraries and will just have to keep a separate copy of the compilation script for our system unless you advise otherwise.

**Comment by bmcandr** [comment]
Hi @wendyksharples, I have updated the docs to add the configuration and model output options described in your sample config/model output files. A rendered PDF is attached [here](https://github.com/NASA-LIS/LISF/files/5235151/LIS_usersguide.pdf) and the AWRA-L additions can be found on pages 55, 58, 141, and 190.

**Review by bmcandr — APPROVED** [review]
The changes compile and reproduce the target output successfully on SLES12.

**Pull request merged**
