### PR TITLE
Feature/a rnk corr lvt

### PR DESCRIPTION
**Pull request by sujayvkumar**

### CODE REVIEW

**Comment by sujayvkumar** [comment]
A sample testcase is at : /discover/nobackup/svkumar/LISF_testing/519

**Comment by sujayvkumar** [comment]
Updated the code with the changes requested. Please note that: 
1. The commented lines on 540-716 were left alone since it has to do with the vegetation related QC (which we may want to use at some point). 
2. Line 573 in LVT_AnomalyRnkCorrMod.F90 - is related to the formatted print statement a few lines above. 

About the errors in the log : This is related to the way LVT queries the system and then figures out which files to read. You can consider these to be warnings and ignore them.

**Comment by bmcandr** [comment]
@sujayvkumar thanks for the explanation. I will continue testing and disregard those messages.

**Comment by bmcandr** [comment]
I'm encountering runtime segmentation faults on both SLES11/Intel18 and SLES12/Intel19:

```sh
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
LVT.intel19        0000000000C7811A  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAB5F42C10  Unknown               Unknown  Unknown
libiomp5.so        00002AAAB85260FE  Unknown               Unknown  Unknown
libiomp5.so        00002AAAB8525F88  Unknown               Unknown  Unknown
libiomp5.so        00002AAAB8525CCA  Unknown               Unknown  Unknown
libiomp5.so        00002AAAB85264CB  Unknown               Unknown  Unknown
libiomp5.so        00002AAAB84B48C0  Unknown               Unknown  Unknown
ld-2.22.so         00002AAAAAABA888  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAB6186869  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAB61868B5  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAB616F72C  __libc_start_main     Unknown  Unknown
LVT.intel19        00000000004122A9  Unknown               Unknown  Unknown
```

I have a call this afternoon with @jvgeiger and @emkemp and I will get their thoughts on this.

**Comment by sujayvkumar** [comment]
With the update, the code ran successfully (on SLES11) with both debug (-2) and O2 optimization settings. 
-S

**Comment by bmcandr** [comment]
Hi @sujayvkumar,

Good news: I have successfully reproduced output on SLES11/Intel18 and SLES12/Intel19.

Bad news: I am encountering compile-time errors with SLES11/GNU4 with default, -2, and -3 settings. [Here are the error messages I'm seeing.](https://github.com/NASA-LIS/LISF/files/4669978/522_gnu_compile_errors.txt) I also created a lisf_7_gnu_4_9_2_mpiuni modulefile, but that did not work either.

**Comment by sujayvkumar** [comment]
Hi @bmcandr 
These error messages do not seem to be related to the code updates related to this pull request. Can you try doing the same on the main trunk?

**Comment by bmcandr** [comment]
The issues appear to be related to debugging settings for the GNU compiler. -2/-3 result in compile time errors while the default settings result in successful compilation. Identical results are produced with SLES11/GNU4 with default configure settings so I am merging this PR.

**Pull request merged**
