### PR TITLE
Added FOC files and script updates

### PR DESCRIPTION
**Pull request by emkemp**
### Description

This adds FOC files for LISF 7.6 GHI test cases, script updates for Discover Milan nodes, and new HPC11 scripts for the Prod environment.

### CODE REVIEW

**Comment by emkemp** [comment]
I have this marked as Draft, as the FOC files need to be approved by @dmocko.  Also, there is some confusion over whether JULES cases need to be included for the NRT-Streamflow and MR configurations.  Currently no use cases exist, therefore no FOC files exist.

**Comment by dmocko** [comment]
Hi @emkemp 

Thanks for organizing and testing all of these files and scripts!

I approve the ldt.config files for NRT (param, cdf, and ensemble - for all 3 LSMs).

I made some edits to the lis.config NRT files (mainly formatting and for consistency).
I placed my suggested versions of these files here:  /discover/nobackup/dmocko

I did not make the suggested changes below, as I have questions about them:
1. Can we move the AUTOTUNED ERROR COVARIANCE SETTINGS into the FORCINGS section, instead of at the bottom?
2. Why are the autotuned values different for Noah-MP-4.0.1 as compared to JULES/Noah-3.9?

I did not review the attribs, JULES namelist, or model "parms" files, as I'm assuming they are the same as the 7.5 FOCs.

If this is not the case, or you would like me to review them anyway, please let me know.

**Comment by emkemp** [comment]
Thanks @dmocko.  I pushed your LIS NRT FOC changes to the branch.

To address your questions:

(1) Moving the autotuned error covariance settings will require changing the autotuning script. Also, it will introduce intermingled updated and static settings (since we don't use SSMI, GEOPRECIP, or CMORPH anymore).  It seemed best to keep all the updated covariance settings together, and putting them at the end of the file with the comment heading allows them to "stand out".  Also, remember these will be changed every run or two, so these are likely not to be looked at by human forecasters.

(2) Hmm. Good catch on the Jules and Noah covariances matching.  I wonder if I copied the wrong OBA files for the Jules case.  In general, I expect some differences between all three LSMs, as LSM snow cover will lead to rejected IMERG assimilation, which in turn will lead to slight differences in the overall data samples.  I will review.

The attribs, JULES namelist, and model "parms" files were all copied from the LISF 7.5 test cases, and should be identical.

**Comment by emkemp** [comment]
The plot thickens:

I went back and looked at the SPD10M OBA files in the spin-ups (these will *not* be affected by LSM snow cover).  I see no differences between Jules50 and Noah39 at all, but I start seeing differences between Jules50 and NoahMP401 at 07Z 15 Sep 2024. This is when I started running the autotuning -- the T2M, RH2M, and SPD10M analyses are a blend of prior analysis and temporally interpolated background field, and always starts 6 hours prior to the "start" of the LIS run to ensure observations).  Unfortunately this means OBA files have been overwritten. (Maybe I should add code to toggle that off for the first few surface analyses.)

For the Jules50 and Noah39 OBA files, there are two additional observations that are missing in the NoahMP401 file. The SPD10M analyses have also diverged between NoahMP401 and Jules50/Noah39 at that point, and the autotuned SPD10M covariances for the 2024091600 run have differences between NoahMP401 and Jules50/Noah39.  I do not have an explanation why this should be.

I'll keep digging.  But this may require rerunning the OBA spin-ups.

**Review by dmocko — APPROVED** [review]
Pending the autotuning test/values, I approve of the FOC and ancillary files added in this PR.

@yyoon4 - Please review and comment/approve on the NRT_STREAMFLOW and MR FOC and ancillary files.

**Comment by emkemp** [comment]
Okay, I was looking in the wrong directories.  When I look in the *actual* spin-up directories w/ static covariances through 00Z 16 Sep, the only differences are with the precip_OBA files, as expected.

I'm guessing I made a mistake somewhere in setting up the "dynamic" spin-up directories, where autotuning and SMAP_E_OPL was turned on.  I'm still investigating.

**Comment by yyoon4** [comment]
> Pending the autotuning test/values, I approve of the FOC and ancillary files added in this PR.
> 
> @yyoon4 - Please review and comment/approve on the NRT_STREAMFLOW and MR FOC and ancillary files.

Thank you for all the effort on the v7.6 delivery. I have reviewed the FOC files, and they are correctly placed.

**Review by yyoon4 — APPROVED** [review]

**Comment by emkemp** [comment]
Thanks @dmocko and @yyoon4.

On my end I completed test reruns of the three LSM spin-ups starting 00Z and 12Z 16 Sep 2024, including reruns of SMAP_E_OPL and rerunning the autotuning.  I now get identical results for OBA and covariance settings for rh2m, spd10m, and t2m (the precip differs as expected, since the LSM snow field affects IMERG assimilation).

I am concluding the differences reported by @dmocko was user error on my part -- I apparently didn't transition from static covariances to autotuning/SMAP_E_OPL consistently between the three LSMs.  This should have no affect on Ops.

@jvgeiger (or @dmocko):  I believe this is ready to merge.  Would one of you like to do the honors?

**Comment by dmocko** [comment]
I will let @jvgeiger do the final review and merging.

**Pull request merged**
