### PR TITLE
Feature/tws update grace

### PR DESCRIPTION
**Pull request by TimLahmers**
### Description

This PR adds the capability for Noah-MP v4.0.1 to assimilate Terrestrial Water Storage (TWS) data from the GRACE mission. TWS DA code is added to the Noah-MP v4.0.1 LSM, and the TWS DA smoother is updated to include this capability.

Resolves Issue #1144 

### Testcase

LIS is tested with TWS DA in the following directories:
/discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_multiVarDA_01km_TESTS/OUTPUT_CaliforniaColumbiaISRIC_TWSda_LSMupdate
lis.config File: /discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_multiVarDA_01km_TESTS/lis.config
Log Files: /discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_multiVarDA_01km_TESTS/TWSda_TESTupdate_LOG2

The 2-month TWS DA simulation may be compared to the control OL simulation for the same time-period:
/discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_01km_OL_LSM/OUTPUT_CaliforniaColumbiaISRIC_wIMERG_OL_LSM

The GRACE Data Files for the rest domain (and the corresponding ldt.config file) are available here:
/discover/nobackup/projects/eis_freshwater/lahmers/SHARE/OUTPUT_GRACE/
/discover/nobackup/projects/eis_freshwater/lahmers/SHARE/ldt.config_freshwaterRegional_CaliforniaColumbiaRegionWBD_ISRIC_GRACEda

### CODE REVIEW

**Comment by TimLahmers** [comment]
@jvgeiger I did some more testing with this model configuration this week, and I am now testing it with multi-variate DA. Please let me know before you start this PR, as I am going to need to make a small modification to this PR after the CCI PR is complete to ensure that all of the DA configurations I am using are supported. I know exactly where the code needs to be changed (it is a plugin), so the update will only take a few minutes to push through.

**Comment by TimLahmers** [comment]
@jvgeiger @sujayvkumar I added some updates to the branch used for the TWS PR, and I need to do some model tests to verify that the results are consistent with earlier multi-variate DA simulations that I have executed. I can confirm by Monday if the changes to this branch are ready to commit into the LIS master.

**Comment by emkemp** [comment]
Hi @TimLahmers:

I do not have permission to look into /discover/nobackup/projects/eis_freshwater.  Any chance this could be opened up so I can test run this pull request?

**Comment by cmclaug2** [comment]
Hi @TimLahmers,

When you have time, can you please rerun you testcase to see if it still works?  I am testing it out now and receiving an error from the file */LISF/lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmp_glacier_401.F90 at line 284. 

Thank you!

**Comment by cmclaug2** [comment]
Hi @TimLahmers,

We have been able to run your pull request, however, we will need to set up a time to review some of the code changes. Specifically, many of the files in the `da_tws` directory need to be discussed.   Jim, Eric, or I will be in touch with you!

In the meantime, would you mind rerunning your testcase?  We noticed two commits have been made since the last time the testcase was run. 

Thanks!

**Comment by TimLahmers** [comment]
@cmclaug2 Thanks for the update, and that sounds good. Please reach out to me if you have any questions.

Regarding the test case, I will re-run the simulation today (it might take a few days due to the current issues with Discover). Since there are other changes to LIS, should I also re-run the control test-case?

**Comment by cmclaug2** [comment]
@TimLahmers,

Great thanks! Yes, can you rerun the control (OL) testcase as well?  We'll only need to look at files within the time window of your DA run (10/2014 - 01/2015)

**Comment by TimLahmers** [comment]
Thanks @cmclaug2 that sounds good! I just submitted the control run with the latest LIS version (waiting for Discover to start), and I brought the feature/twsUpdateGRACE branch up to date with the LIS master. Once I confirm that it runs, I will re-submit the TWS-DA sample job. That job is 12 hours with 720 CPUs, so it may take some time to get started. I will let you know when the new test cases are complete.

**Comment by TimLahmers** [comment]
@cmclaug2 The TWS-DA simulations with updated LIS code are complete. Please let me know if you have any questions about these outputs or the model configuration.
Control:
Output Directory: /discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_01km_OL_LSM/OUTPUT_CaliforniaColumbiaISRIC_wIMERG_OL_ctrlTWS
lis.config File: /discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_01km_OL_LSM/lis.config_LSM_CaliforniaCascades_ISRIC_wIMERG_TWSctrl
Output Log Files: CA_wIMERG_LOG_OL_ctrlTWS

TWS DA:
Output Directory: /discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_multiVarDA_01km_TESTS/OUTPUT_CaliforniaColumbiaISRIC_wIMERG_DA_TWSudpate
lis.config File: /discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_multiVarDA_01km_TESTS/lis.config_RegionalTemplate_WestUSISRIC_daTWS_Update
Output Log Files: /discover/nobackup/projects/eis_freshwater/lahmers/RUN/REGIONAL_multiVarDA_01km_TESTS/TWSda_TESTupdate_LOG2

**Comment by dmocko** [comment]
At a recent LIS monthly tag-up meeting, this PR was discussed and all parties feel that these changes were already merged in via #1305 

I did a code comparison, and the master, public, and eis-freshwater2 branch all have the latest GRACE DA code for Noah-MP-4.0.1 LSM.

Thus, we will be closing and NOT merging this PR.

Leaving open for a few more days for any additional comments.

**Pull request closed without merging**
