### PR TITLE
Corrects the inconsistent time referencing in the LVT readers

### LINKED ISSUE #527: Fix the time referencing conventions in the LVT readers
Several readers use the LVT_rc%yr, LVT_rc%mo, LVT_rc%da ... variables for accessing time information, which is fine in normal circumstances. However, if LVT is used for time lagged computations, these variables should instead use LVT_rc%dyr(source), LVT_rc%dmo(source), .. etc.

### PR DESCRIPTION
**Pull request by sujayvkumar**
Several readers use the LVT_rc%yr, LVT_rc%mo, LVT_rc%da ... variables for accessing time information, which is fine in normal circumstances. However, if LVT is used for time lagged computations, these variables should instead use LVT_rc%dyr(source), LVT_rc%dmo(source), .. etc. This commit correct

Resolves #527

### CODE REVIEW

**Comment by sujayvkumar** [comment]
A testcase for the LPRM soil moisture reader can be found at: 
 /discover/nobackup/svkumar/LISF_testing/528 

No testcase is provided for the other updates (too many to do!). In those readers, the only change is the updating of the time variables as mentioned above.

**Comment by bmcandr** [comment]
Hi @sujayvkumar 

There are a few calls to `stop` and `print` that should be addressed:
* File `lvt/datastreams/SNOTEL/readSNOTELObs.F90`:
    * Lines 174, 187: replace calls to `stop` with `endrun`
    * Lines 164*, 173, 186: replace calls to `print` with calls to `write(LVT_logunit, *)`
        * \*Line 164 is commented out; remove if not needed?

Otherwise the code looks good and I've begun testing!

**Comment by sujayvkumar** [comment]
The requested cleanups have been completed

**Comment by bmcandr** [comment]
Thanks Sujay. The code looks good and produces identical results on Intel18, Intel19, and GNU4 so I will merge.

**Pull request merged**
