### PR TITLE
Fix compiling LIS/RAPID with Cray compilers

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

Fix compiling LIS/RAPID with Cray compilers.

### CODE REVIEW

**Comment by jvgeiger** [comment]
I ran Yeosang's RAPID/Noah39 use case on discover (lis.config.global.noah39.rapid.galwem.0p25deg).  I successfully reproduced his target results.

**Comment by cmclaug2** [comment]
When the PETSc flag is turned on and JULES.5.0 is turned off, this PR compilers with the intel 7.5 compilers, the gnu compilers, and the intel petsc compiler updated in this PR.  I approve.

**Comment by dmocko** [comment]
I was just about to comment on this PR.  I was wondering what was the difference in RAPID_model_main.F90.  It looked like the whole file, so maybe it was just a change in file permissions?

After @cmclaug2 's comment, I have another question.  Do you have to turn off JULES.5.0 compilation to be able to compile RAPID using the PETSc flag?  In other words, we can't run JULES with the RAPID router?

**Comment by dmocko** [comment]
Following up, JULES.5.0 **will** compile with RAPID on HPC-11.  I was using .`/compile -j 8` - and some error messages with RAPID mixed in with JULES messages.  Combine that with @cmclaug2 specifically mentioning that he compiled with JULES.5.0 off, and I thought that was the issue.  But I needed to change a line in RAPID_model_main.F90 which was in this pull request (but not yet in the code I was trying to compile).  There was one line different, and not only a change in the file permissions.

**Pull request merged**
