### PR TITLE
Fix Mosaic LSM nest crash

### PR DESCRIPTION
**Pull request by dmocko**
This pull request resolves a crash for the Mosaic LSM when
looking for the nest value in setting the alarms in lsmMod.

Resolves: #1005

### CODE REVIEW

**Comment by dmocko** [comment]
Hmmmm - not sure why there are those two other commits on this PR.  It should just be the most recent one.

David

**Comment by bmcandr** [comment]
Hmm, sometimes switching the base branch resolves it but it didn't this time. I'll try to figure this out before I merge, but the changes tab only shows the change made by your most recent commit so I suspect it's not problematic.

**Comment by dmocko** [comment]
Ok - if you can't figure it (I certainly couldn't), please let me know and I can take down this PR and try again with a cleaner one.

**Comment by bmcandr** [comment]
I've identified an anomaly: the merge commit from #956 that *should* be present on the NASA-LIS `support/lisf-public-7.3` branch isn't there. Your commit that was merged with that branch *is* present, however. And your public support branch has the merge commit that is missing from the NASA-LIS public support branch which is why it's showing up here. This is a head scratcher...!

Compare:
* NASA-LIS public support log: https://github.com/NASA-LIS/LISF/commits/support/lisf-public-7.3
* dmocko public support log: https://github.com/dmocko/LISF/commits/support/lisf-public-7.3

**Comment by bmcandr** [comment]
I see that #956 was merged just before the branch deletion snafu that occurred on 12/14/21. I wonder if these discrepancies are related to that?

Just to be safe, I recommend updating your fork's version of `support/lisf-public-7.3` to match the one here on NASA-LIS, creating a fix branch off of that, and cherry-picking [370cd08](https://github.com/NASA-LIS/LISF/pull/1006/commits/370cd08c9d1cac63bcbf97fdf01d7846479ec7f7) onto it before opening a new PR.

**Pull request closed without merging**
