### PR TITLE
Add EIS Freshwater Visualization Portal code

### LINKED ISSUE #802: Add EIS Freshwater Visualization Portal code
Add the initial implementation of the visualization portal code.

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

This is the initial commit of the visualization portal code.

Resolves #802

### CODE REVIEW

**Comment by emkemp** [comment]
Before approving:  Are we comfortable committing binary files into the repository?  That's not what git was designed for....

**Comment by bmcandr** [comment]
From what I see, the only binary files are images and we already include images elsewhere in the repo (see Working with GitHub doc).

While git isn't really designed for tracking binary files and it's considered bad practice, it seems to be fairly common practice for small image files to be included in repos--usually in documentation or when hosting a website via GitHub pages ([example](https://github.com/github/government.github.com/tree/gh-pages/assets/img)).

**Comment by bmcandr** [comment]
Oh, and I believe that eventually some of the images being added in this PR will be replaced with linkages to maps/plots served via a webservice like ArcGIS online.

**Comment by emkemp** [comment]
Good point.  I forgot about the images in our docs.

I'll go ahead and approve.

**Pull request merged**
