### PR TITLE
[LDT] Support GMI/AMSR2 PMW datasets for USAF-SI analysis

### PR DESCRIPTION
**Pull request by yyoon4**
Support GMI/AMSR2 PMW datasets and new PMW snow depth retrieval algorithm (Kelly et al., 2009) for USAF-SI analysis (from @yhkwon81).

Please review 'ldt.config.adoc' or 'ldt/USAFSI/ldt.config.sample' to use new capabilities for the analysis.

Testcase:
1. AMSR2
   - with Foster algorithm: /discover/nobackup/yyoon4/lis7/Testcase/ldt_usafsi_pmw/AMSR2_Foster/
   - with Kelly algorithm: /discover/nobackup/yyoon4/lis7/Testcase/ldt_usafsi_pmw/AMSR2_Kelly/
2. XCAL GMI
   - with Foster algorithm: /discover/nobackup/yyoon4/lis7/Testcase/ldt_usafsi_pmw/XCAL_GMI_Foster/
   - with Kelly algorithm: /discover/nobackup/yyoon4/lis7/Testcase/ldt_usafsi_pmw/XCAL_GMI_Kelly/

### CODE REVIEW

**Comment by bmcandr** [comment]
Hi @yyoon4, can you open permissions on the testcase directories? Thanks!

**Comment by yyoon4** [comment]
@bmcandr Thanks for checking.

Done!!

**Comment by emkemp** [comment]
I'm testing the AMSR2_Foster case with strict checks (-3), and I get a allocation error:

forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable SURFLAG when it is not allocated

Image              PC                Routine            Line        Source             
LDT                00000000031DF29F  Unknown               Unknown  Unknown
LDT                00000000018B2197  usafsi_amsr2mod_m         122  USAFSI_amsr2Mod.F90
LDT                00000000019F339F  usafsi_run_               426  USAFSI_run.F90
LDT                0000000001306584  ldt_usafsimod_mp_         606  LDT_usafsiMod.F90
LDT                00000000011FA0F6  ldt_run_usafsi_            25  LDT_run_usafsi.F90
LDT                00000000011FABDE  Unknown               Unknown  Unknown
LDT                00000000014115AC  MAIN__                     46  LDTmain.F90
LDT                0000000000413412  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAB6746725  __libc_start_main     Unknown  Unknown
LDT                0000000000413329  Unknown               Unknown  Unknown


I'm afraid more work is needed.

**Comment by bmcandr** [comment]
Thanks @emkemp. I have test output based on default config settings for Intel 19 and GNU4 compilers; the former is identical, but the latter is showing differences. I'll re-compile with strict checks too.

**Comment by emkemp** [comment]
Update:  I get the same error and stack trace with the AMSR2_Kelly test case.

BTW, I'm using lisf_7_intel_19_1_3_304_traceback-work-around.

**Comment by yyoon4** [comment]
@emkemp Thanks for checking. All of test cases use same LDT codes. I will re-compile the codes and review errors.

**Comment by emkemp** [comment]
Update: I get a different stack trace when I run the XCAL_GMI_Foster case:

forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable SURFLAG when it is not allocated

Image              PC                Routine            Line        Source             
LDT                00000000031DF29F  Unknown               Unknown  Unknown
LDT                0000000001A3E4F0  usafsi_xcalgmimod         123  USAFSI_xcalgmiMod.F90
LDT                00000000019F325C  usafsi_run_               421  USAFSI_run.F90
LDT                0000000001306584  ldt_usafsimod_mp_         606  LDT_usafsiMod.F90
LDT                00000000011FA0F6  ldt_run_usafsi_            25  LDT_run_usafsi.F90
LDT                00000000011FABDE  Unknown               Unknown  Unknown
LDT                00000000014115AC  MAIN__                     46  LDTmain.F90
LDT                0000000000413412  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAB6746725  __libc_start_main     Unknown  Unknown
LDT                0000000000413329  Unknown               Unknown  Unknown

**Comment by emkemp** [comment]
Update:  Same stack trace for XCAL_GMI_Kelly as for XCVAL_GMI_Foster.

**Comment by emkemp** [comment]
For the GMI case, it looks like the surflag array is declared and passed but never used.  It should be straightforward to remove this array entirely.

**Comment by yyoon4** [comment]
@emkemp Thanks Eric! Yes, I knew the reasons and I fixed codes but I have very strange errors when I compile LDT codes ;;;
I will double-check the codes and I will submit the code when I resolve the issues.

**Comment by yyoon4** [comment]
@emkemp @bmcandr 
I update codes. I hope it works well!!

**Comment by emkemp** [comment]
Apologies, but I accidentally deleted USAFSI_2018122000.nc in /discover/nobackup/yyoon4/lis7/Testcase/ldt_usafsi_pmw/AMSR2_Kelly.  Could you please regenerate for comparison?

**Comment by yyoon4** [comment]
@emkemp Done!

**Comment by emkemp** [comment]
Excellent, thank you!

**Comment by emkemp** [comment]
Okay, I reproduced the analyses in the test directories, and the compiler found no problems with the strict check option.

At this point, I have two issues:

(1) I don't see complete references from the different PMW algorithms, just basic citations like Kelly (2009).  Can this be added to the documentation?
(2) I notice there is no support for multiple PMW sensors at the same time -- the user must choose between SSMI, AMSR-2, or GMI.  This may not be a major problem at this point since USAFSI 7.4 can be patched, but I want to run it past Sujay and Jerry before merging into master.  (I'll raise this at the next 557 meeting.)

**Comment by yyoon4** [comment]
@emkemp  Thanks for reviewing!!

(1) I don't see complete references from the different PMW algorithms, just basic citations like Kelly (2009). Can this be added to the documentation?

**Done**

(2) I notice there is no support for multiple PMW sensors at the same time -- the user must choose between SSMI, AMSR-2, or GMI. This may not be a major problem at this point since USAFSI 7.4 can be patched, but I want to run it past Sujay and Jerry before merging into master. (I'll raise this at the next 557 meeting.)

At this point, single PMW data should be used to generate snow depth. It can be possible to use multiple PMW sensors for retrieving snow depth. However, each sensor has different specification and channels, which may make a difficulty of applying.

**Comment by emkemp** [comment]
Thanks @yyoon4.  Are there any other changes you want to make before I merge?

**Comment by yyoon4** [comment]
Nope!! Thank you!!

**Comment by emkemp** [comment]
Pull request is accepted.

**Pull request merged**
