### PR TITLE
Adding two entropy metrics in LVT

### LINKED ISSUE #502: Add support for shannon entropy metric calculations in LVT

### PR DESCRIPTION
**Pull request by sujayvkumar**
The information entropy metric computes the classic shannon entropy metric as
      H(X)= -Sum_x  P(x)log [P(x)]
The conditional entropy metric is calculated as:
      CE(X;Y)=Sum_x Sum_y PXY(x,y)log [PXY(x,y)/(PY(y))]
Together, these metrics can be used to assess the information content and
the information utilization estimates

Resolves #502

### CODE REVIEW

**Comment by sujayvkumar** [comment]
An example testcase is at: /discover/nobackup/svkumar/LISF_testing/502

**Comment by bmcandr** [comment]
Hi @sujayvkumar. We identified the following issues that require your attention before we can merge this PR. Please:

* Change filename of `lvt/metrics/LVT_InformationEntropy.F90` to match module name on line 7: `LVT_InformationEntropyMod`
* Document "Information entropy:" and "Conditional entropy:" in `lvt/configs/lvt.config.adoc`
    * See lines 231 and 235 in `lvt/core/LVT_readMetricsAttributes.F90`
* Add comment explaining purpose of code contained within `if 0` statements
    * See lines 922 and 979 in `lvt/metrics/LVT_InformationEntropy.F90`

Thanks,
B

**Comment by bmcandr** [comment]
Thanks, Sujay.

* Configure, compile, and run results:
    - [x] SLES11/Intel 18 - *PASS*
    - [x] SLES11/GNU 4 - *PASS*

As with #498: @jvgeiger @emkemp, let me know if this looks good to you and I will merge.

**Comment by bmcandr** [comment]
Hi Sujay,

After merging 498 we now have a few conflicts with this PR. Most of them are straightforward and can be resolved by including the changes from both files. The file that will require more attention is `LVT_pluginIndices.F90` as there are some overlapping indices being assigned to multiple variables. Once the conflict is resolved I'll test again and then merge.

Thanks,
B

**Comment by bmcandr** [comment]
Thanks Sujay. The code looks good and passed compile and run tests:

* SLES 11/Intel 18 - *PASS* &#10003;
* SLES 11/GNU 4 - *PASS* &#10003;

**Pull request merged**
