### PR TITLE
Update lisf_7_intel_19_1_3_304 custom modulefile to use ESMF 8.0.1

### LINKED ISSUE #785: Update lisf_7_intel_19_1_3_304 custom module file for ESMF 8.0.1
Update lisf_7_intel_19_1_3_304 custom module file for skylake on discover

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

Update lisf_7_intel_19_1_3_304 custom modulefile to use ESMF 8.0.1.

This includes updating the Intel MPI library to 19.1.3.304.  This
version both correctly produces tracebacks and works on the skylake
compute nodes.

The lisf_7_intel_19_1_3_304_traceback-work-around modulefile is
no longer necessary.  The Intel MPI library 19.1.3.304 now correctly
produces tracebacks.

Resolves #785.

### CODE REVIEW

**Comment by dmocko** [comment]
Per @jvgeiger - this modulefile works on both the haswell and skylake nodes on Discover.

**Comment by emkemp** [comment]
I've found an interesting bug, confirmed with some googling.

While testing the new environment by compiling LIS and LDT, I recurrently see a warning message:

"ifort: command line warning #10006: ignoring unknown option '-fallow-argument-mismatch'"

This command-line flag is not in the configure.lis or configure.ldt file.  Googling led me to evidence that (1) this is specified in the mpif90 script, and (2) we should be using mpiifort instead, since mpif90 assumes by default that gfortran is the underlying compiler.  See the discussion in https://community.intel.com/t5/Intel-Fortran-Compiler/ifort-command-line-warning/td-p/1253461.

Looking at the scripts in /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin on Discover, I confirm the on-line info.

Is it worth changing the LIS/LDT/LVT configure scripts to use mpiifort instead of mpif90 when using Intel?  The code compiles, but the warning message is annoying and may confuse new users.

**Comment by emkemp** [comment]
To clarify:  The new module file uses the mpi/impi/19.1.3.304 environment, which loads the MPI implementation in /usr/local/intel/2020/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin.  The mpif90 script in that directory has the bug (invalid compiler flag meant for gfortran).

The older module file uses mpi/impi/20.0.0.166, which loads the MPI implementation in /usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin.  The mpif90 script in that directory does *not* have the bad flag.  It does, however, assume gfortran by default.

**Comment by jvgeiger** [comment]
Thanks for noticing that.

Yes.  I noticed that as well.  I did confirm that mpif90 was calling ifort under the hood, but I wanted to test with mpiifort.  But then I got distracted.   I will test with mpiifort, and then follow up here.

**Comment by emkemp** [comment]
Hi Jim:

I have a little down time this morning.  Do you want me to take a crack at updating the modulefile to use mpiifort?

**Comment by jvgeiger** [comment]
I just started testing with mpiifort.

**Comment by jvgeiger** [comment]
My testing was good.

**Comment by emkemp** [comment]
This looks good.  Code compiles.  I approve.

**Pull request merged**
