### PR TITLE
[LDT: USAF-SI] Fix typo

### PR DESCRIPTION
**Pull request by yyoon4**
Fix just one minor typo in the USAF-SI reader. For this change, I do not create a test case. However, if you need the test case for verification purposes, please let me know.

### CODE REVIEW

**Comment by bmcandr** [comment]
Hi @yyoon4, the change compiles and the naming scheme appears to match sample data I see in the LIS data directory. I'll go ahead and merge.

**Comment by emkemp** [comment]
Does this need to be ported back the support/lisf-557ww-7.3 branch?

**Comment by yyoon4** [comment]
@emkemp Yes. If you can, please do that.

**Comment by jvgeiger** [comment]
I will do this.  Thanks.

**Comment by yyoon4** [comment]
@jvgeiger Thanks!!

**Pull request merged**
