### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dmocko**
Added a first draft of the CONTRIBUTING document to the LISF repository

### Description

Replace this text with a concise description of *what* was changed and *why*.

### CODE REVIEW

**Comment by dmocko** [comment]
This is still a draft.

See Issue #825

**Comment by bmcandr** [comment]
This is looking great @dmocko! I just made a few minor edits described in my commit message.

I wonder if we should also ask contributors to update the docs if they're adding new config options?

**Comment by dmocko** [comment]
Thanks @bmcandr for the improvements.

Yes, we should specify that users will need to update the appropriate UG if new config options are added.  Great reminder.

I also think that we should indicate that users agree that their contributions will be under the terms of the LIS license:
https://github.com/NASA-LIS/LISF/blob/master/LICENSE.txt

**Comment by dmocko** [comment]
I added a reminder about the Users' Guide(s) and new/modified config entries - and added in a part about the license.

I also added the testcase requirement in a previous commit.

**Comment by bmcandr** [comment]
Just took another pass over this to restructure and simplify it a bit while also adding more details here and there.

The use of questions for the section headers made it tricky to link to each section in the ToC so I simplified them to a single word (e.g., "I am having a problem running LDT/LIS/LVT and would like to ask a question" became "Support"). I'm not married to this change so if we feel the questions are better, we can revert the headers.

Open to edits and suggestions!

**Comment by dmocko** [comment]
Hi @bmcandr 

Great - thanks so much for the changes.  I think it's clearer and the section headers will help repeat visitors to this document re-find whatever is needed.

I agree - I will remove the "draft" label, and am fine with this being reviewed one last time before merging in.

David

**Comment by bmcandr** [comment]
I made changes to `docs/README.md` yesterday in #860 that update the instructions for viewing the Users' Guides and add links to each guide. Therefore, I decided to remove the links to the individual Users' Guides here as they would take users to the unrendered *.adoc file. Instead, this doc will take users to the README which will then point them to the Users' Guides in a readable format (if they follow the instructions 😄).

That said, I'm thinking the documentation section here (or in docs/README?) could be beefed up:
* provide an example of the the config calls that need to be documented if added/modified (e.g., `call ESMF_ConfigFindLabel`)
* describe where else new LSMs and metforcing readers should be documented (e.g., `doc s/LIS_users_guide/user_cfg_table.adoc` and `obtain_source.adoc`?)

These could come in a subsequent PR.

**Comment by bmcandr** [comment]
Merging this for now.

**Pull request merged**
