### PR TITLE
Fix/smap da soil temp bug fix

### LINKED ISSUE #1356: Soil Temperature Bias in Soil Moisture Data Assimilation
### Soil Temperature Bias in Soil Moisture Data Assimilation 

During the update of the SMAP-E-OPL retrieval, we discovered a bias in soil temperature at northern latitudes. We generated DA output in a 2D ensemble grid space and compared each ensemble member with the ensemble mean as well as the unperturbed ensemble (ensemble #12). 
image
 Soil temperature 1st layer 20170713-1200, Ensemble#12 – ensemble mean 
image
Soil temperature 2nd layer 20170713-1200, Ensemble#12 – ensemble mean 

### Steps to Replicate
Run a global SMAP DA test case using the 2D ensemble grid space and compared the soil temperature from the ensemble mean with that of the unperturbed ensemble (ensemble #12).

 
--assignee @LIS-navari

### PR DESCRIPTION
**Pull request by LIS-navari**
### Soil Temperature Bias in Soil Moisture Data Assimilation
In soil moisture data assimilation (DA), we remove biases from soil moisture, which include biases arising from perturbed forcing and perturbation of state variables (soil moisture). However, biases may still persist in other states.

Our investigation shows that the bias in soil temperature is due to state perturbation.

In the DA code, if DA does not occur, we remove the bias from soil moisture. However, we need an additional check to prevent perturbing the state variables if the DA flag (i.e., frozen ground) prevents assimilation. This is particularly important for higher latitudes where the ground freezes during cold seasons. Without this new flag, perturbations in soil moisture can propagate to soil temperature, even when DA does not occur due to frozen ground conditions. Consequently, although we remove the bias from soil moisture since DA does not take place, the bias in soil temperature remains. Therefore, it is crucial to check the frozen ground condition before applying perturbations.
Replace this text with a concise description of *what* was changed and *why*.

Resolves #1356 

### Testcase
Test case for Noah39
/discover/nobackup/projects/usaf_lis/mnavari/AF/SoilMoisture_DA/testcases/pr/noah39/sim
lis.config.da.af.frozen.soil.check
job.DA.frozen.soil.check

Matlab code to plot the results
/discover/nobackup/projects/usaf_lis/mnavari/AF/SoilMoisture_DA/testcases/pr/noah39/analysis/Matlab_code
Read_LIS_2d_ensemble_gridspace_plot_TS_SoilT_Check.m

SoilMoisture_unperturbed_ens_mean_bf_and_af_check_soil_temp

SoilTemp_unperturbed_ens_mean_bf_and_af_check_soil_temp

Test cases for other LSMs are under development.

Test case for NoahMP401

Test case for Jules50

Test case for Noah36

### CODE REVIEW

**Comment by jvgeiger** [comment]
Pending Mahdi's and Armaghan's final testing.

This should be merged into the master branch - not support/lisf-557ww-7.5.

**Comment by LIS-navari** [comment]
Hi Jim,

It should be merged into the support branch. Because it also affects the Jules50.

Thanks
Mahdi

From: James Geiger ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Wednesday, July 19, 2023 at 11:49 AM
To: NASA-LIS/LISF ***@***.***>
Cc: "Navari, Mahdi (GSFC-617.0)[UNIV OF MARYLAND COLLEGE PARK]" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [NASA-LIS/LISF] Fix/smap da soil temp bug fix (PR #1385)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



Pending Mahdi's and Armaghan's final testing.

This should be merged into the master branch - not support/lisf-557ww-7.5.

**Comment by jvgeiger** [comment]
Thanks Mahdi.  The lis/surfacemodels/land/jules.5.0/da_soilm/ files are also in the master branch and keep up to date with the files in the support/lisf-557ww-7.5 branch.

**Comment by aabedelm** [comment]
Here are the results for:

########################################

Test case for Noah36
/discover/nobackup/projects/usaf_lis/aabedelm/AF/SoilMoisture_DA/testcases/pr/noah36/sim
lis.config.da.af.frozen.soil.check
job.DA.frozen.soil.check

Matlab code to plot the results
/discover/nobackup/projects/usaf_lis/aabedelm/AF/SoilMoisture_DA/testcases/pr/noah36/analysis/Matlab_code
Read_LIS_2d_ensemble_gridspace_plot_TS_SoilT_Check.m

SoilMoisture_unperturbed_ens_mean_bf_and_af_check_soil_temp
SoilTemp_unperturbed_ens_mean_bf_and_af_check_soil_temp

########################################

Test case for JULES5
/discover/nobackup/projects/usaf_lis/aabedelm/AF/SoilMoisture_DA/testcases/pr/jules5/sim
lis.config.da.af.frozen.soil.check
job.DA.frozen.soil.check

Matlab code to plot the results
/discover/nobackup/projects/usaf_lis/aabedelm/AF/SoilMoisture_DA/testcases/pr/jules5/analysis/Matlab_code
Read_LIS_2d_ensemble_gridspace_plot_TS_SoilT_Check.m

SoilMoisture_unperturbed_ens_mean_bf_and_af_check_soil_temp
SoilTemp_unperturbed_ens_mean_bf_and_af_check_soil_temp

########################################

Test case for noahmp401
/discover/nobackup/projects/usaf_lis/aabedelm/AF/SoilMoisture_DA/testcases/pr/noahmp401/sim
lis.config.da.af.frozen.soil.check
job.DA.frozen.soil.check

Matlab code to plot the results
/discover/nobackup/projects/usaf_lis/aabedelm/AF/SoilMoisture_DA/testcases/pr/noahmp401/analysis/Matlab_code
Read_LIS_2d_ensemble_gridspace_plot_TS_SoilT_Check.m

SoilMoisture_unperturbed_ens_mean_bf_and_af_check_soil_temp
SoilTemp_unperturbed_ens_mean_bf_and_af_check_soil_temp

**Comment by LIS-navari** [comment]
### Summary of the works:

Upon reviewing Armaghan's results and test cases, I've noticed that the results for Noah39 are not accurate. Even after the second bug fix, there are still some residual biases in the SM field.
Regarding Jules, unfortunately, she did not run any DA. In the DA config file, she set the data assimilation instant to zero (no DA), and she did not generate the CDFs. Her DA runs are actually OL (in the 2D ensemble space). This is the reason she reported an exact match between soil moisture and soil temperature before and after the bug fix.

================================================================================
### Three bug fixes were applied to address issues observed in the NoahMP401 and Noah39 SM DA results:

1- A soil temperature check was implemented to prevent updating the state variable if the ground is frozen.
2- The ensemble flag issue was resolved.
3- A condition was added to compute the delta (sum of the difference between unperturbed ensemble and other ensembles) using total soil moisture (smc) if the ground is frozen, instead of the liquid part of soil moisture (sh2o).

### Results for NoahMP401
image
Spatial Mean of Soil Moisture for the 1st soil layer.

image
Spatial Mean of Soil Temperature for the 1st soil layer.

image
Temporal Mean of Soil moisture for Ensemble #12 (left panels), Ensemble Mean (middle panels), and difference (right panels) for DA test cases: Before Bug Fix (top row), After Soil Temperature Check Bug Fix (middle row), After Soil Temperature and Ensemble Flag Bug Fix, and Applying 3rd bug fix (bottom row).

image
Temporal Mean of Soil Temperature for Ensemble #12 (left panels), Ensemble Mean (middle panels), and difference (right panels) for DA test cases: Before Bug Fix (top row), After Soil Temperature Check Bug Fix (middle row), After Soil Temperature and Ensemble Flag Bug Fix, and Applying 3rd bug fix (bottom row).

### Results for Noah39
image
Spatial Mean of Soil Moisture for the 1st soil layer.

image
Spatial Mean of Soil Temperature for the 1st soil layer.

image
Temporal Mean of Soil moisture for Ensemble #12 (left panels), Ensemble Mean (middle panels), and difference (right panels) for DA test cases: Before Bug Fix (top row), After Soil Temperature Check Bug Fix (middle row), After Soil Temperature and Ensemble Flag Bug Fix, and Applying 3rd bug fix (bottom row).

image
Temporal Mean of Soil Temperature for Ensemble #12 (left panels), Ensemble Mean (middle panels), and difference (right panels) for DA test cases: Before Bug Fix (top row), After Soil Temperature Check Bug Fix (middle row), After Soil Temperature and Ensemble Flag Bug Fix, and Applying 3rd bug fix (bottom row).

### Test cases
1- NoahMP401 
/discover/nobackup/projects/usaf_lis/mnavari/AF/SoilMoisture_DA/testcases/pr/noahmp401/sim
lis.config.da.af.3bug_fix
job.DA.3bug_fix
Matlab code to produce figures
/discover/nobackup/projects/usaf_lis/mnavari/AF/SoilMoisture_DA/testcases/pr/noahmp401/analysis/Matlab_code/Read_LIS_2d_ensemble_gridspace_plot_TS_SoilT_Check_ens_flag_fix_sh2o2smc_fix.m

2- Noah39
/discover/nobackup/projects/usaf_lis/mnavari/AF/SoilMoisture_DA/testcases/pr/noah39/sim
lis.config.da.af.3bug_fix
 job.DA.3bug_fix

Matlab code to produce figures 
/discover/nobackup/projects/usaf_lis/mnavari/AF/SoilMoisture_DA/testcases/pr/noah39/analysis/Matlab_code/Read_LIS_2d_ensemble_gridspace_plot_TS_SoilT_Check_ens_flag_fix_sh2o2smc_fix.m

**Comment by emkemp** [comment]
This is ready for review.  We will also have to cherrypick/rebase to target for LISF 7.6

**Comment by emkemp** [comment]
Hi @LIS-navari 

I do not have read permission for lis.config.da.af.3bug_fix for NoahMP, nor for Noah.  Can you please update the file permissions to give us access?

**Comment by LIS-navari** [comment]
Hi @emkemp 
Sorry for that. Please try now.

**Comment by emkemp** [comment]
Thanks @LIS-navari 

I'm running the two test cases now on the Milan nodes.

**Comment by emkemp** [comment]
Update:  My noah39 run timed out before completing the full range of data in the evaluation.  I saved the output and am rerunning with a longer runtime.

The NoahMP run covers the full period. I will work today on learning how to run the Matlab script.

**Comment by emkemp** [comment]
@LIS-navari 

I'm having trouble running your noahmp matlab script.  (I actually copied and renamed it to change the work directory.) I do get time series plots, but when the script starts plotting the maps of Alaska it throws an error:

Error using load
Unable to find file or directory 'coast'.

Error in matlab (line 370)
load coast ; geoshow(lat,long,'DisplayType', 'line','Color','k','linewidth', 1.5)

Error in run (line 99)
evalin('caller', strcat(script, ';'));

Any suggestions for a workaround?  I'm using module matlab/R2023b.

**Comment by LIS-navari** [comment]
Hi @emkemp,

I utilized MATLAB/R2020a. If it doesn't work, feel free to comment out that line. It plots the border.

**Comment by emkemp** [comment]
An update:  I'm continually running into a problem with insufficient licenses for the MAP_Toolbox.  I can make timeseries plots at the two locations specified in script provided by @LIS-navari, but the surface cross-sections are never drawn.

So far I have partial results for NoahMP.  I'm going to pivot to Noah.

**Comment by emkemp** [comment]
Hi @LIS-navari 

My latest attempt at creating surface plots failed for a new reason:  I do not have read permission to /gpfsm/dnb33/mnavari/my_projects/matlab/functions/b2r.m.  Can you please update the permissions?

**Comment by LIS-navari** [comment]
Hi @emkemp,

Please give it another try. I've granted permission to all Matlab functions now.

Thanks!

**Comment by emkemp** [comment]
Thanks @LIS-navari 

The scripts run now.  I'm studying the plots.

**Comment by LIS-navari** [comment]
Hello @jvgeiger 
Yes, I used them for print statements. you can delete those lines. 
Thanks, 
Mahdi

**Pull request merged**
