### PR TITLE
Address SonarQube findings for LISF 557WW 7.4.0

### LINKED ISSUE #763: Address SonarQube findings for LISF 557WW 7.4.0
### Bug Description

Address SonarQube findings for LISF 557WW 7.4.0

- [x] address `strcpy()` findings in LDT by using `strncpy()`
- [x] fix plotting script in LVT
- [x] update lis/make/user_557ww.cfg file
- [x] given time, address findings in makedep.py utility

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

Address SonarQube findings for LISF 557WW 7.4.0.  See Issue #763 for a list of the findings.

Resolves #763

### CODE REVIEW

**Comment by emkemp** [comment]
I’m testing these changes now with the intel 19 compiler.

 

-Eric

 

Eric M. Kemp (SSAI) 

NASA/GSFC 

Mail Code: 617 

Greenbelt, MD 20771 

301.286.9768 

***@***.***

***@***.***

 

 

From: James Geiger ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Friday, April 23, 2021 at 3:45 PM
To: NASA-LIS/LISF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [NASA-LIS/LISF] Address SonarQube findings for LISF 557WW 7.4.0 (#768)

 
Description
Address SonarQube findings for LISF 557WW 7.4.0. See Issue #763 for a list of the findings.

Resolves #763

You can view, comment on, or merge this pull request online at:
  https://github.com/NASA-LIS/LISF/pull/768
Commit Summary
Remove carriage-return characters
Replace all calls to strcpy() with strncpy()
Replace exit with sys.exit()
Disable compiling CLM2 and RDHM.3.5.6 in the user_557ww.cfg
Remove unneeded finally block
File Changes
M ldt/core/LDT_forcingparms_Ftable.c (6) 
M ldt/core/LDT_irrig_Ftable.c (12) 
M ldt/make/makedep.py (9) 
M lis/make/makedep.py (9) 
M lis/make/user_557ww.cfg (2) 
M lis/surfacemodels/land/jules.5.2/da_soilm/jules52_getsmpred.F90 (7) 
M lis/surfacemodels/land/jules.5.2/da_soilm/jules52_qc_soilmobs.F90 (26) 
M lis/surfacemodels/land/jules.5.3/da_soilm/jules53_getsmpred.F90 (7) 
M lis/surfacemodels/land/jules.5.3/da_soilm/jules53_qc_soilmobs.F90 (26) 
M lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_getsmpred.F90 (7) 
M lis/surfacemodels/land/jules.5.x/da_soilm/jules5x_qc_soilmobs.F90 (26) 
M lvt/make/makedep.py (9) 
M lvt/utils/gnuplot/timeseries/plotTS.py (4) 
Patch Links:
https://github.com/NASA-LIS/LISF/pull/768.patch
https://github.com/NASA-LIS/LISF/pull/768.diff

**Comment by emkemp** [comment]
The code compiles with Intel 19 strict checks (-3) without issue.  NOTE:  I did not try compiling with JULES.

However, I notice the use of both 'print*' and 'stop' in the JULES DA code.  (These weren't introduced in the current change set, but they aren't removed either.) Can you replace these with 'write(LVT_logunit,*)' and 'call LVT_endrun()' respectively, or should that be a separate pull request?

**Comment by emkemp** [comment]
Update:  I compiled with JULES 5.0, and I see no issues.

**Comment by jvgeiger** [comment]
I will update the `print*` and `stop` statements as suggested.

**Comment by emkemp** [comment]
Latest code compiles, and I fixed a few print* and stop usages that were missed.  I approve.

**Pull request merged**
