### PR TITLE
Change the 'LDTSI' to 'USAFSI' in LDT configuration

### PR DESCRIPTION
**Pull request by yyoon4**
Change the 'LDTSI' to 'USAFSI' in the LDT configuration file. Also, update related log messages. However, the output file name is not changed to keep consistency.

### CODE REVIEW

**Comment by emkemp** [comment]
Question for @sujayvkumar 

Is it acceptable if the USAFSI file output continues to use the old "LDTSI" name?  If not, further changes are required in LIS and LVT to accommodate a file name change.

**Comment by jvgeiger** [comment]
Yeosang and I discussed this, and I suggested that we add an option to the ldt.config and lvt.config files to specify the output name.

**Comment by emkemp** [comment]
Okay, I concur.  I will mark this pull request as "incomplete" and wait for the additional LIS and LVT updates.

**Comment by yyoon4** [comment]
I add an option to the ldt.config to specify the output name. And I will update related codes too (e.g. #431)

**Comment by yyoon4** [comment]
@emkemp 
Could you please help me to update for LVT.

**Comment by emkemp** [comment]
@yyoon4  Will do.

**Comment by emkemp** [comment]
I'm going to try changing the source code from LDTSI to USAFSI.  This seems less difficult/time consuming than we originally thought.  I'll coordinate with you on migrating code changes to this pull request.

**Comment by emkemp** [comment]
@yyoon4:  I pushed code changes into your branch that replace "LDTSI" with "USAFSI".  I also changed the prefix entry in ldt.config to:

"USAFSI netcdf filename prefix:"

which used not only for creating new USAFSI output files, but also for reading in previous files.

I also updated the example ldt.config files and the documentation.

**Pull request merged**
