### PR TITLE
Adds the implementation of particle filter assimilation algorithm

### LINKED ISSUE #507: Implement a particle filter data assimilation algorithm in LIS

### PR DESCRIPTION
**Pull request by sujayvkumar**
Particle Filter algorithm as another data assimilation algorithm has been added
PF is a monte carlo algorithm where assumptions of gaussianty is not required.

Resolves #507

### CODE REVIEW

**Comment by sujayvkumar** [comment]
A sample testcase is at /discover/nobackup/svkumar/LISF_testing/507

**Comment by bmcandr** [comment]
Hi Sujay,

I reviewed the code and found the following issues to review/address:

* File: `lis/dataassim/algorithm/pf/pf_Mod.F90`
    * Lines 246-251, 429-450, 460-476: remove commented out test
* File: `lis/dataassim/algorithm/pf/pf_general.F90`
    * 114-127: remove commented out test variables and test
    * 145: commented call: `!call gjinvert(N_obs,Obs_cov, Obs_cov_inv)` ?
    * 333-353: hard-coded numbers present
    * 407-408, 413-419: commented lines
    * 467, 496, 516, 539: remove comment markers from otherwise blank lines
    * 490: replace call to `print*, 'ERR:` with `write(LIS_logunit,*)`
    * 491, 514: replace call to `stop` with `LIS_endrun`
* File: `lis/plugins/LIS_lsmda_pluginMod.F90`
    * 478: should this code be uncommented? A comment on the line says "we need this for LBand DA"
* File: `lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_qc_snowobs.F90`
    * 89-102: Remove commented code (also contains hard-coded numbers)
* File: `lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_scale_snow.F90`
    * 55-69: `#if 0` block?
* File: `lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_snow_update.F90`
    * 148-154: hardcoded numbers
    * 154: vague comment `temporary setup`
    * 223, 230-237: commented block
    * 299: Remove comment with author's name
    * Code in all caps is sprinkled throughout file (e.g., 141-164). Convert to lowercase to maintain consistent style?

Once you get a chance to review I can test the changes.

-B

**Comment by sujayvkumar** [comment]
The requested changes have been made.

**Comment by bmcandr** [comment]
Thanks Sujay. The code looks good. I'm seeing slight differences between output generated by Intel and GNU compilers, but @jvgeiger and @emkemp have mentioned this is normal I believe. I have a call with them this afternoon where I will confirm. After that I will merge.

**Pull request merged**
