### PR TITLE
Fixes the bug of LVT not reading the OPT/UE outputs correctly

### LINKED ISSUE #179: LVT does not read the OPT/UE outputs correctly

### PR DESCRIPTION
**Pull request by sujayvkumar**
The LVT OPT/UE reader has been updated to work with the format of
output from LIS

Resolves #179

### CODE REVIEW

**Comment by emkemp** [comment]
Is there a test case for this?

**Comment by sujayvkumar** [comment]
You can find a test case at: 
/discover/nobackup/projects/ifloods/svkumar/SUSMAP/ISMN_testcase/OPTrun5/Analysis

**Comment by emkemp** [comment]
Can you open read permissions to the files in your testcase directory?  I can't view or copy any of them.

**Comment by sujayvkumar** [comment]
Permissions have been changed (I hope you have access to the ifloods project disk).

**Pull request merged**
