### PR TITLE
Feature/sm docs

### PR DESCRIPTION
**Pull request by karsenau**
Added new "docs" subdirectory and a "How-To" document for how to run SnowModel in LIS.  Additional information is provided about the model and how to set up a run via LDT and LIS.  Subdirectory, "docs" is found within the Snowmodel directory in LIS.

Also, a sample snowmodel.par file is provided in the new "docs" subdirectory.

This addresses issue #1290.

### CODE REVIEW

**Comment by cmclaug2** [comment]
Hi @karsenau,

This documentation looks good.  I pushed a minor typo and formatting fix.  I will take a quick look tomorrow and commit!

**Comment by karsenau** [comment]
Thanks, @cmclaug2!

BTW - In the reference section, I think you can leave the commas after the names of the journals, instead of replacing with periods.

**Comment by jvgeiger** [comment]
I suggest following the style in the Citation section of the README on NASA-LIS/LISF - (1) period after the title, (2) comma after the journal

**Comment by cmclaug2** [comment]
@jvgeiger and @karsenau,

Thank you both for your guidance.  I used the suggested citation style and Kristi's documentation is ready to be merged!

**Pull request merged**
