### PR TITLE
Feature/GLASSalbedo_reader

### PR DESCRIPTION
**Pull request by abheeralisf**
The test-case computing the RMSE and BIAS between the GLASS-albedo and JULES-Albedo can be found in the following directory "/discover/nobackup/ahazra/UK_meto/JULES_LVT/example_08_sol/".

### CODE REVIEW

**Comment by emkemp** [comment]
Hello:

I tested your branch, and I get array bounds errors detected when compiled with strict checks.  Also, the RMSE netcdf output file has garbage data in some of the COUNT_SD variables--I see this in your sample output file as well (run ncview on your RMSE netcdf file and plot the COUNT_SD for direct NIR albedo).

This will need to be fixed on your end before the pull request can be accepted.  At a minimum, it looks like the logic for setting the c1 and r1 indices is wrong, because c=1 and r=3598 yields (c1+(r1-1)*nc) value of -7196 (invalid, must be no less than 1).  

There are also some issues with the indentation of the code, but that can be addressed later.

**Comment by abheeralisf** [comment]
Hi Eric,

Thanks for the feedback. I will look into it and get back to you soon.

-Abheera

**Comment by emkemp** [comment]
No problem.  Hopefully this indexing bug will be easy to fix.

One other TODO:  You will need to update the lvt/config/lvt.config.master file to reflect the new configuration settings for GLASS ALBEDO.  Again, we can address this later.

**Comment by emkemp** [comment]
Hi Abheera:

Any estimate on when fixes will be available?

**Comment by abheeralisf** [comment]
Hi Eric,

Sorry the fixes took this long to get back to. I will try to have them completed by next week latest or let you know if I need more time.

Thanks,
Abheera

**Comment by abheeralisf** [comment]
Hi Eric,

Just wanted to update you that I have begun work on the GLASSalbedo reader, it will take me upto next week to get it completed. Hope that is okay.

Thanks,
Abheera

From: "Hazra, Abheera (GSFC-617.0)[UNIVERSITY OF MARYLAND]" <abheera.hazra@nasa.gov>
Date: Tuesday, July 23, 2019 at 5:17 PM
To: NASA-LIS/LISF <reply@reply.github.com>, NASA-LIS/LISF <LISF@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [EXTERNAL] Re: [NASA-LIS/LISF] Feature/GLASSalbedo_reader (#158)

Hi Eric,

Sorry the fixes took this long to get back to. I will try to have them completed by next week latest or let you know if I need more time.

Thanks,
Abheera

**Comment by abheeralisf** [comment]
Hi, 

The updates are in.

**Comment by dmocko** [comment]
Thanks - does the testcase need to be updated?

**Comment by abheeralisf** [comment]
Yes, my apologies, forgot to add those in.
Currently the script can read in two different sources of GLASS-albedo – MODIS or AVHRR, and the test config files are,
Monthly-mean GLASS-Albedo Modis- ‘/discover/nobackup/ahazra/UK_meto/JULES_LVT/example_09_sol/lvt_config_glassalbedo_modis_monthly_mean’
Monthly-mean GLASS-Albedo AVHRR- ‘/discover/nobackup/ahazra/UK_meto/JULES_LVT/example_09_sol/lvt_config_glassalbedo_avhrr_monthly_mean’
RMSE-Bias between JULES and GLASS-Albedo AVHRR –‘/discover/nobackup/ahazra/UK_meto/JULES_LVT/example_09_sol/lvt_config_glassalbedo_jules_bias_rmse’

**Comment by emkemp** [comment]
Below is from an e-mail sent directly from Abheera to Eric and Sujay.  It contains information relevant to this pull request, so I am copying it here to keep everything together.

***

The reader is updated in ‘/discover/nobackup/ahazra/LISF2/lvt/datastreams/GLASSalbedo/readGLASSalbedoObs.F90’. And I tried out a few simple test config files for computing the monthly means of these datasets and RMSE and BIAS wrt JULES data, they seem to look alright.
So, currently the script can read in two different sources of GLASS-albedo – MODIS or AVHRR, for any of the LVT based computation when considered separately and the test config files are,
Monthly-mean GLASS-Albedo Modis- ‘/discover/nobackup/ahazra/UK_meto/JULES_LVT/example_09_sol/lvt_config_glassalbedo_modis_monthly_mean’
Monthly-mean GLASS-Albedo AVHRR- ‘/discover/nobackup/ahazra/UK_meto/JULES_LVT/example_09_sol/lvt_config_glassalbedo_avhrr_monthly_mean’
RMSE-Bias between JULES and GLASS-Albedo AVHRR –‘/discover/nobackup/ahazra/UK_meto/JULES_LVT/example_09_sol/lvt_config_glassalbedo_jules_bias_rmse’
 
I also tried out computing the RMSE and BIAS of the two different sources of GLASS-albedo (MODIS and AVHRR) with each other,
 ‘/discover/nobackup/ahazra/UK_meto/JULES_LVT/example_09_sol/lvt_config_glassalbedo_bias_rmse’
 
but this did not work out, it completes the run without any error messages but the config file is forcing only the first defined GLASS-albedo data source (MODIS/AVHRR) in the config file to override the second file described. I may have missed some obvious logic in how LVT works or how this script is set-up. But if this particular functionality is required where both the GLASS albedo datasets can be compared I will need another day or two to figure it out or if you have any suggestions please let me know, I am happy to implement it.
 
Please let me know if you suggest any other corrections.

**Comment by abheeralisf** [comment]
Hi Eric, 

Thanks for those feedback. I will work on the issues you have mentioned and make the changes you have suggested and get back shortly.

-Abheera

**Comment by emkemp** [comment]
Hi Abheera:

Do you have any updates to this pull request?

**Comment by abheeralisf** [comment]
Hi Eric,

Not yet, I am AGU this week and could not do much. But I do plan on getting it ready as soon as I am back.

Thanks for checking,
Abheera

**Comment by emkemp** [comment]
Hi Abheera:

Do you have any updates on pull request #158?

**Comment by abheeralisf** [comment]
Hi Eric,

Working on it. Please let me get back to you with it, I recently transitioned to intel-18 and am fixing the issues.
There has been a huge amount of requests with the forecast product so could not get to the reader sooner.

**Comment by bmcandr** [comment]
Hi @abheeralisf, are you still working on this feature (pull request #158)? Just checking in as it has been in the queue for a while. If you don't think you'll get to this in the near future I may recommend closing this PR and opening a new one when the feature is ready to merge into master.

**Comment by abheeralisf** [comment]
Hi Brendan, the feature is ready, I will push it with the test case in a day or so.

**Comment by bmcandr** [comment]
Excellent, thank you Abheera!

**Comment by bmcandr** [comment]
Thanks @abheeralisf for committing the requested changes for this PR!

The code compiles without issue on Intel 18/19 and GNU4. Test runs with the Intel-based executables produced identical output, but I was unable to perform test runs with the GNU4 executable as the SLES11/GNU4 environment lacks the HDF4 support required for this feature. I did not encounter any of the seg fault errors mentioned in earlier comments.

I believe this pull request is therefore ready to merge into master.

----
A note about an issue mentioned in [an earlier comment](https://github.com/NASA-LIS/LISF/pull/158#pullrequestreview-297595074)...

Eric reported striping in the COUNT_SD_* fields of the output produced by one of the bias_rmse testcases. I also observed this striping in the same fields in the output of the *lvt_config_glassalbedo_jules_bias_rmse* testcase. The striping is present in both the target and test output (see below). Testing with the master branch also produces striped output in these fields, however, which indicates this issue is unrelated to the changes introduced in this pull request. I will open a new issue describing this.

**Pull request merged**
