### PR TITLE
Intel-based modulefile using OpenMPI for compiling LISF on discover SCU 17

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

This is the modulefile and associated changes for compiling LISF on discover SCU 17 using the Intel compilers with Intel MPI.

To use, copy env/discover/sles15/lisf_7.5_intel_2023.2.1_openmpi_5.0.0 into your ~/privatemodules directory and then run
```
module load lisf_7.5_intel_2023.2.1_openmpi_5.0.0
```

### CODE REVIEW

**Comment by emkemp** [comment]
I'm getting a link error with the new modulefile when I try compiling LDT.

ld: /discover/nobackup/projects/lis/libs/sles-15.4/gdal/3.7.2_gnu-12.3.0_intel-2023.2.1/lib//libgdal.so: undefined reference to `curl_multi_poll'
make: *** [Makefile:54: LDT] Error 1

[ERR] Compile failed
-------------------------------------------------------------------

This is with normal optimization.  I am testing on discover35 (discover-mil).

**Comment by emkemp** [comment]
I'm getting the same link error with LVT.

ld: /discover/nobackup/projects/lis/libs/sles-15.4/gdal/3.7.2_gnu-12.3.0_intel-2023.2.1/lib//libgdal.so: undefined reference to `curl_multi_poll'
make: *** [Makefile:54: LVT] Error 1

[ERR] Compile failed
-------------------------------------------------------------------

**Comment by jvgeiger** [comment]
It works for me. :-)

I will look into those libraries.

Thanks.

**Comment by jvgeiger** [comment]
Perhaps I should have said

It works for me :-(

**Comment by emkemp** [comment]
FWIW, if I disable GeoTIFF in LDT and LVT at the configure script, the executables build w/o issue.  So it's a bit of an edge case (but a serious one for USAFSI).

**Comment by jvgeiger** [comment]
@dmocko, do you get the same linking error as Eric?

**Comment by dmocko** [comment]
@jvgeiger I was going to try this after our other meeting which just ended.  I will work on this now.

**Comment by dmocko** [comment]
Could this line be the problem?  There's a typo in "stedrr".

https://github.com/jvgeiger/LISF/blob/f4ec302262394de5c3680c668cf1416dee6bf708/env/discover/sles15/lisf_7.5_intel_2023.2.1_openmpi_5.0.0#L63

**Comment by jvgeiger** [comment]
Those two warnings are expected.

That typo should have affected only `module help`.  But thanks for spotting it.  I pushed a correction.

Which discover login are you on?

**Comment by dmocko** [comment]
`discover35`

Also just made a LIS executable (no warnings).  Going to try LVT now.

**Comment by emkemp** [comment]
Okay, I just tried the latest code.  If I run my standard start-up script to load modules I still get the link error.  However, if I just load the private module by itself, LDT links w/o issue.

I'm working to identify which additional module is causing a conflict.

**Comment by emkemp** [comment]
Okay, the offending module is ncl/6.6.2.  Removing this from my module list fixes the LDT and LVT problem I observed.

**Pull request merged**
