### PR TITLE
Support for Lambert projection added to LVT LISDAobs reader.

### LINKED ISSUE #1151: LVT DAobs does not support lambert projection.
LVT DAobs does not support Lambert projection. 
Current version of LVT DAobs reader support latlon projection only.

### PR DESCRIPTION
**Pull request by LIS-navari**
### Description
LVT DAobs reader was updated to support Lambert projection. 
Resolves #1151

### Testcase
Test case for lambert projection 
/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/merra2_eu/Analysis/us_map
lvt.config.ol.da.DAobs
job.ol.da

Testcase to make sure it did not break the latlon projection. 

/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/nlads_conus/Analysis/us_map

*Before code update
lvt.config.ol.da.DAobs
job.ol.da
Output @ 
STATS.ol.da.DAobs

* After code update 
lvt.config.ol.da.DAobs.test
job.ol.da.test
Output @ 
STATS.ol.da.DAobs.test

### CODE REVIEW

**Comment by cmclaug2** [comment]
Hi Mahdi,

I was taking a look at your pull request and trying to locate the two testcases you provided.  

For both testcases, I could not find the files you are pointing to in the "*/Analysis/us_map" folders because the "*/us_map" folders do not exist; however, I was able to locate the files in the "*/Analysis/comp_scaled_smap" folders.  Can you confirm that these are the correct testcase files?

Thanks! 
Colin

**Comment by LIS-navari** [comment]
Hi Colin, 

Sorry for that.
I have renamed the directories

As you mentioned the correct directories are labeled as */Analysis/comp_scaled_smap

Test case for lambert projection
/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/merra2_eu/Analysis/comp_scaled_smap

Testcase to make sure it did not break the latlon projection.

/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/nlads_conus/Analysis/comp_scaled_smap

Thanks
Mahdi

**Comment by cmclaug2** [comment]
Hi Mahdi,

No problem!  Thank you for the clarification and I apologize for the delay in response. 

I do not have permission to access some of the data needed to completely run your testcase.  Specifically, there is data in the following folders that the group does not have permission to read or execute.

A couple dozen files in:
/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/merra2_eu/sim/output.da/DAOBS/202111

As well as the entire folder:
/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/merra2_eu/sim/output.da/DAOBS/202112

Can you grant me permission to read and execute these files?  This can be done by running the command "chmod -R g+rx ." from the following folder:
/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/merra2_eu/sim/output.da/DAOBS

I appreciate it!  Everything is looking good so far.  This is my first time working through a pull request on LISF so I want to make certain everything is squared away.

Thanks!
Colin

**Comment by LIS-navari** [comment]
Hi Colin, 

Please try now. 

Thanks
Mahdi

**Comment by emkemp** [comment]
Hi @mahdi:

Can you tell us what Intel compiler version you used for your testing?  @cmclaug2 is seeing some differences in results (on order of 1%), and we're trying to determine if this is just a compiler difference.  @cmclaug2  used Intel 21.

Also, can you provide read permission to /discover/nobackup/mnavari/SRC/master_lisf/lvt/make/configure.lvt?  (I'm assuming that is the original LVT you used before code modifications.)

**Comment by LIS-navari** [comment]
Hi Eric

I’m using

module use --append $HOME/privatemodules

#module load $HOME/privatemodules/intel_18_0_3_222

module load lisf_7_intel_19_1_3_304_traceback-work-around

I have opened permission to

/discover/nobackup/mnavari/SRC/master_lisf

Please let me know if you have access issues.

Thanks
Mahdi
From: Eric Kemp ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Thursday, September 29, 2022 at 11:28 AM
To: NASA-LIS/LISF ***@***.***>
Cc: "Navari, Mahdi (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Support for Lambert projection added to LVT LISDAobs reader. (PR #1152)


Hi @mahdi<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmahdi&data=05%7C01%7Cmahdi.navari%40nasa.gov%7Cdae984d37e3842e8962d08daa22f304f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638000620816555939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9bahU35ecHxpjUprahGmfS9aw4oWc1QC6Td%2F784IPsU%3D&reserved=0>:

Can you tell us what Intel compiler version you used for your testing? @cmclaug2<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcmclaug2&data=05%7C01%7Cmahdi.navari%40nasa.gov%7Cdae984d37e3842e8962d08daa22f304f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638000620816555939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HnW855JOiGNjkAu74vxX0HL5X2INEd14bO%2FC%2BF3tOXc%3D&reserved=0> is seeing some differences in results (on order of 1%), and we're trying to determine if this is just a compiler difference. @cmclaug2<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcmclaug2&data=05%7C01%7Cmahdi.navari%40nasa.gov%7Cdae984d37e3842e8962d08daa22f304f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638000620816555939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HnW855JOiGNjkAu74vxX0HL5X2INEd14bO%2FC%2BF3tOXc%3D&reserved=0> used Intel 21.

Also, can you provide read permission to /discover/nobackup/mnavari/SRC/master_lisf/lvt/make/configure.lvt? (I'm assuming that is the original LVT you used before code modifications.)

**Comment by emkemp** [comment]
Thanks @LIS-navari 

Can you copy your private module to your $NOBACKUP?  We don't have access to your $HOME directory.

**Comment by LIS-navari** [comment]
@emkemp 
Please check 

/discover/nobackup/mnavari/SRC/master_lisf

**Comment by cmclaug2** [comment]
Hi Mahdi,

Thank you for your help so far.

Using the data currently in the ".../merra2_eu/sim/output.da/DAOBS/" folder, can you please run your first testcase again located at "/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/merra2_eu/Analysis/comp_scaled_smap"

The reason I am asking is because, as noted by Eric above, we are noticing (marginal) differences in my output compared to yours. Looking at the dates some of your folders are updated, I am thinking the difference may be because we ran the testcase with different input.

Sorry for taking so long to get to this pull request. We hope to get this added to LISF soon.

Colin

**Comment by LIS-navari** [comment]
Hi Colin,

I have run the test case again.
/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/merra2_eu/Analysis/comp_scaled_smap/STATS.ol.da.DAobs

I have renamed the old run to “ STATS.ol.da.DAobs.old”

Please let me know if you need further simulations.

Thanks
Mahdi

From: Colin McLaughlin ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Friday, September 30, 2022 at 2:08 PM
To: NASA-LIS/LISF ***@***.***>
Cc: "Navari, Mahdi (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Support for Lambert projection added to LVT LISDAobs reader. (PR #1152)


Hi Mahdi,

Thank you for your help so far.

Using the data currently in the ".../merra2_eu/sim/output.da/DAOBS/" folder, can you please run your first testcase again located at "/discover/nobackup/projects/usaf_lis/mnavari/nrl/conus_europe/merra2_eu/Analysis/comp_scaled_smap"

The reason I am asking is because, as noted by Eric above, we are noticing (marginal) differences in my output compared to yours. Looking at the dates some of your folders are updated, I am thinking the difference may be because we ran the testcase with different input.

Sorry for taking so long to get to this pull request. We hope to get this added to LISF soon.

Colin

**Pull request merged**
