### PR TITLE
Added the support for THySM soil moisture

### PR DESCRIPTION
**Pull request by sujayvkumar**
Includes the support for THySM soil moisture data in LDT and LIS

### Description

Added support for the 1km resolution THySM soil moisture data over the CONUS domain. LDT was updated to enable the development of climatological parameters from this data. Data assimilation support for THySM was added in LIS.

### CODE REVIEW

**Comment by sujayvkumar** [comment]
Resolves #755

**Comment by bmcandr** [comment]
@sujayvkumar, was this feature was developed for the EIS project? If so, the pull request should target the _eis-freshwater_ branch. @jvgeiger can then merge it back into _master_ if its ready for primetime as well.

**Comment by sujayvkumar** [comment]
Yes, this is intended for EIS. How do I make the pull request targeting eis_freshwater?

**Comment by bmcandr** [comment]
Click the _Edit_ button on the top-right then use the drop down that reads _base: master_ to switch to the _eis-freshwater_ branch.

**Comment by sujayvkumar** [comment]
Thanks. Hopefully that does it.

**Comment by bmcandr** [comment]
Yep, looks good!

**Comment by bmcandr** [comment]
Sorry, can you also point me to a testcase?

**Comment by sujayvkumar** [comment]
Here you go:
/discover/nobackup/projects/eis_freshwater/svkumar/LIS_test_THySM

**Comment by bmcandr** [comment]
Hi @sujayvkumar, I hit a seg fault during initialization:

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
   5 Image              PC                Routine            Line        Source
   6 LIS.i19.defaults   00000000014E863A  Unknown               Unknown  Unknown
   7 libpthread-2.22.s  00002AAAB3EA9C10  Unknown               Unknown  Unknown
   8 LIS.i19.defaults   0000000000590D30  readobsdataconfig         749  LIS_dataassim_FTable.c
   9 LIS.i19.defaults   0000000000565DCD  lis_daobservation         264  LIS_DAobservationsMod.F90
  10 LIS.i19.defaults   00000000012B7D5C  retrospective_run          93  retrospective_runMod.F90
  11 LIS.i19.defaults   0000000000D3859B  MAIN__                     67  lisdrv.F90
  12 LIS.i19.defaults   0000000000413712  Unknown               Unknown  Unknown
  13 libc-2.22.so       00002AAAB45D7725  __libc_start_main     Unknown  Unknown
  14 LIS.i19.defaults   0000000000413629  Unknown               Unknown  Unknown
```

My testing directory is here: /discover/nobackup/projects/eis_freshwater/bmcandr/PR_DIR/756/testing
The _lislog_ files are in OUTPUT/ and the informative stack trace is in _R-lis-run.43356745.err_

I notice that my log file is missing the following section and wonder if that's contributing:

```sh
    [INFO] Opening constraints for prognostic state variables
    ./noah_sm_attribs.txt
  
    [INFO] Soil Moisture Layer 1                     9.9999998E-03  0.5500000
    [INFO] Soil Moisture Layer 2                     9.9999998E-03  0.5500000
    [INFO] Soil Moisture Layer 3                     9.9999998E-03  0.5500000
    [INFO] Soil Moisture Layer 4                     9.9999998E-03  0.5500000
    [INFO] Opening perturbation attributes for observations
    ./noah_sm_pertattribs.txt
    [INFO] Soil Moisture Layer 1                              0  2.0000000E-02
     0.1000000               1   10800.00      0.0000000E+00  0.0000000E+00
      1.000000      0.0000000E+00  0.0000000E+00  0.0000000E+00
    [INFO] Soil Moisture Layer 2                              0  0.0000000E+00
     0.1000000               1   10800.00      0.0000000E+00  0.0000000E+00
     0.0000000E+00   1.000000      0.0000000E+00  0.0000000E+00
    [INFO] Soil Moisture Layer 3                              0  0.0000000E+00
     0.1000000               1   10800.00      0.0000000E+00  0.0000000E+00
     0.0000000E+00  0.0000000E+00   1.000000      0.0000000E+00
    [INFO] Soil Moisture Layer 4                              0  0.0000000E+00
     0.1000000               1   10800.00      0.0000000E+00  0.0000000E+00
     0.0000000E+00  0.0000000E+00  0.0000000E+00   1.000000
    [INFO] Successfully read perturbation attributes file ./noah_sm_pertattribs.txt
```

**Comment by sujayvkumar** [comment]
@bmcandr  - can you open up the permissions on your directories?

**Comment by bmcandr** [comment]
Should be open now. Forgot to open my top-level, sorry.

**Comment by sujayvkumar** [comment]
@bmcandr - I realized that the relevant files were not committed the last time (Sorry!). It should all be there now. Please try again.

**Comment by sujayvkumar** [comment]
You can find the LDT example at: 
/discover/nobackup/projects/eis_freshwater/svkumar/LDT_test_THySM

LVT test is at: 
/discover/nobackup/projects/eis_freshwater/svkumar/IrrigAnalysis/THySM

**Comment by bmcandr** [comment]
@sujayvkumar in light of the bug fix for LVT, should I test with the lvt.config in _/discover/nobackup/projects/eis_freshwater/svkumar/IrrigAnalysis/THySM.GS/lvt.config_?

**Comment by sujayvkumar** [comment]
The older directory still applies. I reran it last night. 
/discover/nobackup/projects/eis_freshwater/svkumar/IrrigAnalysis/THySM

**Comment by bmcandr** [comment]
Update: the differences in the _THySM*.nc_ files described above are also present in the output of an executable compiled with -2 optimization. I'm able to reproduce the target output exactly using your LDT executable, however. Any ideas?

**Comment by sujayvkumar** [comment]
@bmcandr I believe the differences are due to the fact that I ran LDT before I introduced some additional checks into the QC portion of the code. If LIS runs successfully with the outputs from your LDT run, I think we can declare victory.

**Comment by bmcandr** [comment]
Gotcha. I'm running LIS once more with the LDT outputs to verify. If it looks good I'll go ahead and merge. Should be done within the hour.

**Pull request merged**
