### PR TITLE
Fixes for compiling with GNU and Cray compilers

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

This resolves compiler errors raised by both the GNU and Cray compilers.

### CODE REVIEW

**Comment by emkemp** [comment]
Hi @jvgeiger:

I tried compiling LIS with the Intel compiler *and* with Crocus.8.1 activated.  I get the following compilation error:

../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(213): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
                                       dimID=dimID, &
---------------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(219): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWSWE_ID, "SNOWSWE", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(227): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWRHO_ID, "SNOWRHO", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(235): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWHEAT_ID, "SNOWHEAT", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(242): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWALB_ID, "SNOWALB", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(248): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWGRAN1_ID, "SNOWGRAN1", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(256): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWGRAN2_ID, "SNOWGRAN2", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(264): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWHIST_ID, "SNOWHIST", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(272): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWAGE_ID, "SNOWAGE", &
-----------------------------------------^
./surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(280): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWLIQ_ID, "SNOWLIQ", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(288): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWTEMP_ID, "SNOWTEMP", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(296): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(288): error #7983: The storage extent of the dummy argument exceeds th../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(288): error #7983: The storage extent of the dummy argument exceeds that of the a../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(288): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWTEMP_ID, "SNOWTEMP", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(296): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWDZ_ID, "SNOWDZ", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(303): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, GRNDFLUX_ID, "GRNDFLUX", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(308): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNDRIFT_ID, "SNDRIFT", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(313): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, RI_n_ID, "RI_N", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(318): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, CDSNOW_ID, "CDSNOW", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(323): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, USTARSNOW_ID, "USTARSNOW", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(328): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, CHSNOW_ID, "CHSNOW", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(333): error #7983: The storage extent of the dummy argument exceeds that of the actual argument.   [DIMID]
    call LIS_writeHeader_restart(ftn, n, dimID, SNOWMAK_dz_ID, "SNOWMAK_DZ", &
-----------------------------------------^
compilation aborted for ../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90 (code 1)
Makefile:140: recipe for target 'Crocus81_writerst.o' failed
make: *** [Crocus81_writerst.o] Error 1

[ERR] Compile failed

Did you try compiling Crocus.8.1?

**Comment by LIS-navari** [comment]
Hi Eric,

[10/21 2:41 PM] Geiger, James V. (GSFC-5870)
I got the same error. That is a good start. [🙂]

[10/21 2:53 PM] Geiger, James V. (GSFC-5870)
Change line 187 to:

 187     integer :: dimID(11)

For more info, run git log and then search for "commit 661232d0a1d33aa09f7e002d2c7ad99a3a196ff3".

[10/21 2:54 PM] Geiger, James V. (GSFC-5870)
I will create a pull request to fix the bug.

Best
Mahdi



From: Eric Kemp ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Thursday, October 27, 2022 at 11:35 AM
To: NASA-LIS/LISF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Fixes for compiling with GNU and Cray compilers (PR #1225)


Hi @jvgeiger<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjvgeiger&data=05%7C01%7Cmahdi.navari%40nasa.gov%7C7bc05935ebd04d793da208dab830df71%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638024817290895385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M3MWlcnMWIkxcZvLCg4cVGekbT184HExmYKzUxapgJ8%3D&reserved=0>:

I tried compiling LIS with the Intel compiler and with Crocus.8.1 activated. I get the following compilation error:

../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(213): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
dimID=dimID, &
---------------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(219): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWSWE_ID, "SNOWSWE", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(227): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWRHO_ID, "SNOWRHO", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(235): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWHEAT_ID, "SNOWHEAT", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(242): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWALB_ID, "SNOWALB", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(248): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWGRAN1_ID, "SNOWGRAN1", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(256): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWGRAN2_ID, "SNOWGRAN2", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(264): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWHIST_ID, "SNOWHIST", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(272): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWAGE_ID, "SNOWAGE", &
-----------------------------------------^
./surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(280): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWLIQ_ID, "SNOWLIQ", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(288): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWTEMP_ID, "SNOWTEMP", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(296): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(288): error #7983: The storage extent of the dummy argument exceeds th../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(288): error #7983: The storage extent of the dummy argument exceeds that of the a../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(288): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWTEMP_ID, "SNOWTEMP", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(296): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWDZ_ID, "SNOWDZ", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(303): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, GRNDFLUX_ID, "GRNDFLUX", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(308): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNDRIFT_ID, "SNDRIFT", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(313): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, RI_n_ID, "RI_N", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(318): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, CDSNOW_ID, "CDSNOW", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(323): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, USTARSNOW_ID, "USTARSNOW", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(328): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, CHSNOW_ID, "CHSNOW", &
-----------------------------------------^
../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90(333): error #7983: The storage extent of the dummy argument exceeds that of the actual argument. [DIMID]
call LIS_writeHeader_restart(ftn, n, dimID, SNOWMAK_dz_ID, "SNOWMAK_DZ", &
-----------------------------------------^
compilation aborted for ../surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90 (code 1)
Makefile:140: recipe for target 'Crocus81_writerst.o' failed
make: *** [Crocus81_writerst.o] Error 1

[ERR] Compile failed

Did you try compiling Crocus.8.1?

**Comment by emkemp** [comment]
Ah!  Thanks @LIS-navari.  @jvgeiger has that dimID array length change in a separate pull request (#1222).  I'll apply it for testing to this pull request (#1225).

**Comment by emkemp** [comment]
Compilation tests completed on Discover (Intel and GNU) and on HPC11 (Cray), after manually adding patches for #1222 and #1226 to the checked-out source code.  Cray compiler also found a syntax error in crocus_driver.F90, which will be addressed in a future pull request.

I am satisfied with the changes in this pull request, and will approve.

**Pull request merged**
