### PR TITLE
Intel-based modulefile for compiling LISF on discover SCU 17

### PR DESCRIPTION
**Pull request by jvgeiger**
### Description

This is the modulefile and associated changes for compiling LISF on discover SCU 17 using the Intel compilers with Intel MPI.

To use, copy _env/discover/sles15/lisf_7.5_intel_2023.2.1_ into your _~/privatemodules_ directory and then run

```
module load lisf_7.5_intel_2023.2.1
```

### CODE REVIEW

**Comment by emkemp** [comment]
I'm testing the new module file on discover-mil.  So far I'm getting a linking error with LDT when I enable:
* NetCDF4
* ECCODES
* HDF4
* HDFEOS2
* HDF5
* GDAL
* LIBGEOTIFF

The error message is:

ld: warning: libjpeg.so.8, needed by /usr/lib/../lib64/libtiff.so, may conflict with libjpeg.so.62
ld: warning: libjpeg.so.8, needed by /usr/lib/../lib64/libtiff.so, may conflict with libjpeg.so.62

**Comment by jvgeiger** [comment]
Sorry, I forgot to mention that linker warning.  My testing has not raised any actual issues.  Note that we get the same linker warning on narwhal and HPC-11.

**Comment by dmocko** [comment]
@jvgeiger Has this been tested on the master branch and on the eis-freshwater2 branch yet?  Or just the public-7.5 branch?

**Comment by jvgeiger** [comment]
I tested on the master and support/lisf-public-7.5 branches.  I did not test on the eis-freshwater2 branch.

**Comment by emkemp** [comment]
@jvgeiger I continued test compiling LDT with different combinations of libraries disabled.  It appears the link warnings are associated with HDF4 and LIBGEOTIFF.  However, the binary is always created.  

I see no problem with LIS and LVT.  I will go ahead and approve the pull request.

**Pull request merged**
