### PR TITLE
update the testcase creation guide

### PR DESCRIPTION
**Pull request by bmcandr**
* Cleans up formatting
* Adds additional guidance

I've updated this guide based on my experience cleaning up existing testcases for inclusion in the test suite. Feedback welcome!

### CODE REVIEW

**Comment by jvgeiger** [comment]
Thanks.  This looks good.

I ran into an error when I tried to process this file into a PDF document.  I will look into it.

**Comment by bmcandr** [comment]
Fixed the error! The column formatting on the file table wasn't set properly for PDF conversion, but showed up fine when viewed as HTML.

**Comment by jvgeiger** [comment]
Thanks!

I prefer .ctl files, but .xdf files are acceptable.

First an .xdf file is a simpler way to write a .ctl file for NetCDF output.  An .xdf file will not work for our binary or GRIB formatted output.

I prefer .ctl files for NetCDF data because they are explicit and allow me to fully automate generating plots.  But if I have problems with an .xdf file, I can quickly create a .ctl version.

**Comment by bmcandr** [comment]
Thanks for the explanation @jvgeiger. I went ahead and removed the references to .xdfs to simplify things.

If everything else looks alright, I'll merge tomorrow morning.

**Comment by jvgeiger** [comment]
Everything looks good.

Do you prefer admonitions like "Note" and "Important" to be spell out with words or with symbols (i, !)?

**Comment by bmcandr** [comment]
I think I prefer the symbols. They take up less space and the color makes the admonitions stand out a bit.

Should I add the `:icons: font` attribute to enable them?

**Comment by jvgeiger** [comment]
Yes.  Sounds good.

**Pull request merged**
