### PR TITLE
Feature/extend da

### PR DESCRIPTION
**Pull request by sujayvkumar**

### CODE REVIEW

**Comment by sujayvkumar** [comment]
Example test case is at: 
/discover/nobackup/svkumar/LISF_testing/544

**Comment by sujayvkumar** [comment]
@bmcandr - Any update on this pull request?

**Comment by bmcandr** [comment]
@sujayvkumar I've done initial testing that has reproduced the target results, but I am still working my way through the code review. I spoke with @jvgeiger about this yesterday as well and he said he would take a look at the code as well because of the large number of changes.

I'll have my comments in by this afternoon.

**Comment by sujayvkumar** [comment]
> @sujayvkumar I've done initial testing that has reproduced the target results, but I am still working my way through the code review. I spoke with @jvgeiger about this yesterday as well and he said he would take a look at the code as well because of the large number of changes.
> 
> I'll have my comments in by this afternoon.

Thanks. Waiting for this pull request to be approved before adding the next set of updates...

**Comment by bmcandr** [comment]
Also, should any changes be made to the official docs to reflect the extension of DA beyond LSMs?

**Comment by sujayvkumar** [comment]
> Also, should any changes be made to the official docs to reflect the extension of DA beyond LSMs?

Yes, I think it'll be good to add that.

**Comment by sujayvkumar** [comment]
> @sujayvkumar the changes look good and I have successfully reproduced the target output with Intel 18/19 and GNU4. I did however notice a few more things that should be addressed before merging:
> 
> * In output file `HYMAP2_routerstats.d01.stats` "for" appears truncated in summary title: `Statistical Summary of ROUTING output fo 5/ 3/2001`
>   
>   * Solution: at line 651 `lis/core/LIS_historyMod.F90` change `format(a47...)` to `format(a51...)`? (new statement is 51 char long vs 47 char)
> * An empty EnKF folder is produced by the run; is this just a part of the DA process?
> * Both the target and test `lislog` files contain the warning `[WARN] Error in nf90_get_att: GRIDTYPE`; is this expected?

The empty EnKF is fine. The test configuration does not have any DA diagnostics enabled, which is why there is no EnKF output

The 'GRIDTYPE' warning is also fine. This entry exists only for curvilinear grids.

**Comment by bmcandr** [comment]
Thanks @sujayvkumar!  Do you plan to push changes to the docs as mentioned in your comment above? Or will those come in a separate PR?

@jvgeiger, have you had a chance to look at this PR? I've finished testing and believe I'm ready to merge barring any objections.

**Comment by sujayvkumar** [comment]
@bmcandr  Will do the changes to the main docs later.

**Comment by sujayvkumar** [comment]
@bmcandr @jvgeiger : Hey guys, can we complete the merge today?

**Comment by sujayvkumar** [comment]
@jvgeiger Hey Jim - were you able to complete your review yet?

**Comment by jvgeiger** [comment]
Hello Sujay,

The ekf_increments, enksgrace_increments, and ensrf_increments routines are empty: all logic is commented out by #if 0/#endif.  May I clean up these three routines?

**Comment by sujayvkumar** [comment]
Hi Jim, 
We should remove EKF and EnSRF altogether. These two algorithms are not fully working. Yes, please cleanup the enksgrace_increments routine. 
Thanks

**Comment by jvgeiger** [comment]
Thanks.  I will clean up the enksgrace_increments routine.  We can remove EKF and EnSRF later.

**Comment by jvgeiger** [comment]
Hello @bmcandr,

I am done with my review.  I have pushed a few commits. Would you please recompile and retest?

Please accept this PR when you are ready.

Jim

**Comment by bmcandr** [comment]
Thanks @jvgeiger! I'll recompile and kick off the test suite now.

**Comment by bmcandr** [comment]
These changes compile successfully and produce identical output to the targets provided in the test case suite. I will therefore merge.

**Comment by sujayvkumar** [comment]
Thanks guys!

**Pull request merged**
