### PR TITLE
New features in LIS for GVF DA and SMAP_E_OPL soil moisture DA

### PR DESCRIPTION
**Pull request by yhkwon81**
### Description
Codes for VIIRS GVF, CDFS GVF, and SMAP_E_OPL soil moisture DA have been added in LIS

### Testcase
SMAP_E_OPL DA: /discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noah39/noah39_CONUS_10km/DA_MCDF_SMAP_E_OPL

VIIRS GVF DA:
/discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noahmp401/noahmp401_CONUS_10km_dynamic/DA_VIIRS_GVF

CDFS GVF DA:
/discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noahmp401/noahmp401_CONUS_10km_dynamic/DA_CDFS_GVF

### CODE REVIEW

**Comment by emkemp** [comment]
Hi @yhkwon81 
I dusted off this pull request, and am having problems accessing the first test case.  Can you please open up:

/discover/nobackup/projects/usaf_lis/ykwon/SMAP_E_OPL/testcases/TEST_02_historical_L1B/SM_retrieval

?

**Comment by emkemp** [comment]
Hi @yhkwon81 

I tried running the VIIRS DA test case, and I notice the GVF names expected by LIS are different from what are in your test directory.  LIS expects:

GVF-WKL-GLB_v2r3_npp_e20210102.nc

But your directory (/discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noahmp401/noahmp401_CONUS_10km_dynamic/DA_VIIRS_GVF/VIIRS_GVF/2021/) has

GVF-WKL-GLB_v2r3_j01_e20210102.nc

So the LIS executable is not reading the VIIRS data.  I don't see anything in the lis.config file that would explain this.

**Comment by emkemp** [comment]
Disregard last message about reading VIIRS data.  I made a mistake in creating a symbolic link.  Data is being read now.

**Comment by yhkwon81** [comment]
I changed the permission. Thanks.

From: Eric Kemp ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Friday, July 29, 2022 at 3:40 PM
To: NASA-LIS/LISF ***@***.***>
Cc: "Kwon, Yonghwan (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] New features in LIS for GVF DA and SMAP_E_OPL soil moisture DA (PR #1111)


Hi @yhkwon81<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyhkwon81&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7Cf3168414b961487490e008da719a3e1b%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637947204531644894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mEPvn8hAo2ab70rAEjD%2FjbiF%2FMmDaK5dLO%2Bpre%2B%2Fas4%3D&reserved=0>
I dusted off this pull request, and am having problems accessing the first test case. Can you please open up:

/discover/nobackup/projects/usaf_lis/ykwon/SMAP_E_OPL/testcases/TEST_02_historical_L1B/SM_retrieval

?

**Comment by emkemp** [comment]
Thanks @yhkwon81.  I'm running the SMAP DA test case now.

**Comment by emkemp** [comment]
Hi @yhkwon81 

Can you open up read permissions in /discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noah39/noah39_CONUS_10km/DA_MCDF_SMAP_E_OPL/OUTPUT so I can compare my results with yours?

Thanks.

**Comment by yhkwon81** [comment]
I changed the permission for the OUTPUT directory. Please try again.

Thanks.

From: Eric Kemp ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Monday, August 1, 2022 at 10:02 AM
To: NASA-LIS/LISF ***@***.***>
Cc: "Kwon, Yonghwan (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] New features in LIS for GVF DA and SMAP_E_OPL soil moisture DA (PR #1111)


Hi @yhkwon81<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyhkwon81&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7C23b7daa710954763096008da73c66a93%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637949593277361371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yla3ImpKVxn0RwufjiqDx7nYWHomJHJTMuvgnLckMUY%3D&reserved=0>

Can you open up read permissions in /discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noah39/noah39_CONUS_10km/DA_MCDF_SMAP_E_OPL/OUTPUT so I can compare my results with yours?

Thanks.

**Comment by emkemp** [comment]
Hi @yhkwon81 

Apologies, but I don't have read permissions for the subdirectories in /discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noah39/noah39_CONUS_10km/DA_MCDF_SMAP_E_OPL/OUTPUT/SURFACEMODEL.  Can you please run chmod again, and make sure all subdirectories and their contents are readable?

**Comment by yhkwon81** [comment]
I changed the permission. Please try to access the directory again.

From: Eric Kemp ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Tuesday, August 16, 2022 at 3:54 PM
To: NASA-LIS/LISF ***@***.***>
Cc: "Kwon, Yonghwan (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] New features in LIS for GVF DA and SMAP_E_OPL soil moisture DA (PR #1111)


Hi @yhkwon81<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyhkwon81&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7C67004cbbe60b4b21625608da7fc11f29%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637962764673009915%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CCKEpuFyh31qkdnImxTJRRNxA%2FNmbTy6yEOBEd0ss4Q%3D&reserved=0>

Apologies, but I don't have read permissions for the subdirectories in /discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noah39/noah39_CONUS_10km/DA_MCDF_SMAP_E_OPL/OUTPUT/SURFACEMODEL. Can you please run chmod again, and make sure all subdirectories and their contents are readable?

**Comment by emkemp** [comment]
Thanks @yhkwon81.  I'm satisfied that my results reproduce yours.  I need to coordinate with @jvgeiger about your test cases before I accept this pull request.

**Comment by emkemp** [comment]
Actually, I spoke to soon.  You need to add documentation for the new VIIRS GVF, SMAP_E_OPL, and CDFS GVF entries in the lis.config file before we can proceed.

**Comment by emkemp** [comment]
I copied my test input and output files to /discover/nobackup/projects/lis/PR_TESTCASES/1110.  I will go ahead and approve this pull request.

**Pull request merged**
